### DISCUSSION TITLE
How can I add service annotations in the Jaeger manifest?

### DISCUSSION THREAD

**Discussion by herbguo** [jaegertracing/jaeger-operator#1338] [Q&A] [answered]
As the title say, How can I add service annotations in the Jaeger manifest ?
I want to add same annotations in the jaeger-query service , I install the jaeger through the jaeger-operator. 
the version is 1.20.0

The  jaeger offical document only have the sample to alter the deployment annotations.

I can not find how to alter the jaeger install manifest to add annotation in jaeger offical document. 

someone can help me! thanks!!!

**Comment by jpkrohling** [comment, marked as answer]
You can add annotations to components, but not directly to the underlying resources (deployments, services, ...). The annotation you add to the component is then propagated down to the resources.

**Reply by herbguo** [reply]
> You can add annotations to components, but not directly to the underlying resources (deployments, services, ...). The annotation you add to the component is then propagated down to the resources.

Thank you , but how to write it in the components?

**Reply by jpkrohling** [reply]
Something like this:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: with-annotations
spec:
  collector:
    annotations:
      myannotation: value
```
