### DISCUSSION TITLE
Jaeger CRD health status stuck on Progressing

### DISCUSSION THREAD

**Discussion by yasinahlatci** [jaegertracing/jaeger-operator#1571] [Q&A]
Hi, I deployed a jaeger operator on eks cluster. I orchestrate my cluster with ArgoCd. When operator deployed, Jaeger CRD health status stuck on Progressing. And so jaeger pod could not access to the CRD. When I edit Jaeger CRD and set the status.phase to Running, it works fine. Is this some kind of bug ? Can anyone help me about how to solve this issue ?

my argocd.yaml for Jaeger-operator:
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: ABC
          url: '${ABC}'
  template:
    metadata: 
      name: '{{cluster}}-jaeger-operator'
    spec:
      syncPolicy:
        automated:
          selfHeal: true
      destination:
        namespace: jaeger
        server: '{{url}}'
      project: default
      source:
        repoURL: 'https://jaegertracing.github.io/helm-charts'
        targetRevision: '2.24.0'
        chart: jaeger-operator
        helm:
          values: |
            jaeger:
              create: true
              spec:
                ingress:
                  enabled: false
            rbac:
              clusterRole: true
```
my Jaeger CRD log;

```
...
...
{"level":"info","ts":1632915063.6349397,"caller":"command-line-arguments/main.go:233","msg":"Starting agent"}
{"level":"info","ts":1632915063.6351511,"caller":"grpclog/component.go:71","msg":"[roundrobin]roundrobinPicker: newPicker called with info: {map[0xc0003c5f90:{{:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1632915063.6352522,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1632915063.635311,"caller":"grpc/builder.go:120","msg":"Agent collector connection state change","dialTarget":":14250","status":"READY"}
{"level":"info","ts":1632915063.6356132,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1632915063.6355627,"caller":"querysvc/query_service.go:137","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1632915063.635687,"caller":"app/flags.go:124","msg":"Archive storage not initialized"}
{"level":"info","ts":1632915063.6367002,"caller":"app/static_handler.go:181","msg":"UI config path not provided, config file will not be watched"}
{"level":"info","ts":1632915063.636939,"caller":"app/server.go:181","msg":"Query server started"}
{"level":"info","ts":1632915063.6369817,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1632915063.6370196,"caller":"app/server.go:260","msg":"Starting GRPC server","port":16685,"addr":":16685"}
{"level":"info","ts":1632915063.6370423,"caller":"app/server.go:241","msg":"Starting HTTP server","port":16686,"addr":":16686"}
```
