### DISCUSSION TITLE
Jaeger operator with custom hosts still 404 not found

### DISCUSSION THREAD

**Discussion by 4IP** [jaegertracing/jaeger-operator#1572] [Q&A]
I want add the hosts / domain in jaeger. but the domain still 404 not found, this example i setup this jaeger:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: mw-jaeger-dev
  namespace: monitoring
spec:
  strategy: allInOne
  ingress:
    hosts:
      - jaeger.example.com
    tls:
      - hosts:
          - jaeger.example.com
        secretName: jaeger-example-com-tls
```

the rule is jaeger operator -> ELB aws -> domain, the jaeger only access with ELB domain not translate front domain if i setup on above. if remove the hosts, hosts on jaeger become to *. but i want use the domain like typesense in below:

```
kubectl get ingress -n monitoring
NAME                   CLASS  HOSTS                                  ADDRESS                              PORTS     AGE
jaeger-dev-query      <none>   *                                     adecfxxxxxxx.xxxxxx.elb.amazonaws.com   80        12h
typesence-typesense   <none>   dev-typesense.com                     adecfxxxxxxx.xxxxxxx.elb.amazonaws.com  80, 443   12h
```

Thank you 🙏
