### DISCUSSION TITLE
esIndexCleaner and esRollover schedules are ignored

### DISCUSSION THREAD

**Discussion by bentcoder** [jaegertracing/jaeger-operator#2590] [Q&A]
Hi,

As you can see below `cronjob.batch/jaeger-es-index-cleaner` and `cronjob.batch/jaeger-es-rollover` schedules are not changed to what I configured above `* * * * *`.

Any reason why? Thanks.

```bash
NAME                                      SCHEDULE      TIMEZONE   SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/jaeger-es-index-cleaner     55 23 * * *   <none>     False     0        <none>          64s
cronjob.batch/jaeger-es-lookback          0 0 * * *     <none>     False     0        <none>          64s
cronjob.batch/jaeger-es-rollover          0 0 * * *     <none>     False     0        <none>          64s
cronjob.batch/jaeger-spark-dependencies   55 23 * * *   <none>     False     0        <none>          64s
```

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger

metadata:
  name: jaeger
  namespace: observability

spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: my-es-url
        version: 7
        index-prefix: prod
        use-aliases: true
      esIndexCleaner:
        enabled: true
        image: jaegertracing/jaeger-es-index-cleaner
        schedule: "* * * * *"
        numberOfDays: 0
      esRollover:
        image: jaegertracing/jaeger-es-rollover
        schedule: "* * * * *"
        conditions: "{\"max_age\": \"1m\",\"max_size\": \"1GB\"}"
    dependencies:
      enabled: true
      elasticsearchNodesWanOnly: true
```

```bash
$ kubectl -n observability describe cronjob.batch/jaeger-es-index-cleaner
Name:                          jaeger-es-index-cleaner
Namespace:                     observability
Labels:                        app=jaeger
                               app.kubernetes.io/component=cronjob-es-index-cleaner
                               app.kubernetes.io/instance=jaeger
                               app.kubernetes.io/managed-by=jaeger-operator
                               app.kubernetes.io/name=jaeger-es-index-cleaner
                               app.kubernetes.io/part-of=jaeger
Annotations:                   linkerd.io/inject: disabled
                               prometheus.io/scrape: false
                               sidecar.istio.io/inject: false
Schedule:                      55 23 * * *
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   1
Completions:                   <unset>
Pod Template:
  Labels:           app=jaeger
                    app.kubernetes.io/component=cronjob-es-index-cleaner
                    app.kubernetes.io/instance=jaeger
                    app.kubernetes.io/managed-by=jaeger-operator
                    app.kubernetes.io/name=jaeger-es-index-cleaner
                    app.kubernetes.io/part-of=jaeger
  Annotations:      linkerd.io/inject: disabled
                    prometheus.io/scrape: false
                    sidecar.istio.io/inject: false
  Service Account:  jaeger
  Containers:
   jaeger-es-index-cleaner:
    Image:      jaegertracing/jaeger-es-index-cleaner:1.56.0
    Port:       <none>
    Host Port:  <none>
    Args:
      7
      my-es-link
    Environment:
      INDEX_PREFIX:  prod
      ROLLOVER:      true
    Mounts:          <none>
  Volumes:           <none>
  Node-Selectors:    <none>
  Tolerations:       <none>
Last Schedule Time:  <unset>
Active Jobs:         <none>
Events:              <none>
```

```bash
$ kubectl -n observability describe cronjob.batch/jaeger-es-rollover
Name:                          jaeger-es-rollover
Namespace:                     observability
Labels:                        app=jaeger
                               app.kubernetes.io/component=cronjob-es-rollover
                               app.kubernetes.io/instance=jaeger
                               app.kubernetes.io/managed-by=jaeger-operator
                               app.kubernetes.io/name=jaeger-es-rollover
                               app.kubernetes.io/part-of=jaeger
Annotations:                   <none>
Schedule:                      0 0 * * *
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   1
Completions:                   <unset>
Pod Template:
  Labels:           <none>
  Annotations:      linkerd.io/inject: disabled
                    prometheus.io/scrape: false
                    sidecar.istio.io/inject: false
  Service Account:  jaeger
  Containers:
   jaeger-es-rollover:
    Image:      jaegertracing/jaeger-es-rollover:1.56.0
    Port:       <none>
    Host Port:  <none>
    Args:
      rollover
      my-es-url
    Environment:
      INDEX_PREFIX:  prod
    Mounts:          <none>
  Volumes:           <none>
  Node-Selectors:    <none>
  Tolerations:       <none>
Last Schedule Time:  <unset>
Active Jobs:         <none>
Events:              <none>
```
