### DISCUSSION TITLE
jaeger-operator install is error

### DISCUSSION THREAD

**Discussion by cuisongliu** [jaegertracing/jaeger-operator#2632] [Q&A]
k8s  1.25.x
cert-manager 1.12.3

```
kubectl logs -f -n observability jaeger-operator-cc7d8bd9c-674lv
exit status 2
```

pod manifests

```
spec:
    containers:
    - args:
      - start
      - --metrics-port=8383
      - --webhook-bind-port=9443
      env:
      - name: WATCH_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: OPERATOR_NAME
        value: jaeger-operator
      image: jaegertracing/jaeger-operator:1.52.0
...
```
