### ISSUE TITLE
How to forward jaeger-query ports

### ISSUE THREAD

**Issue by wesleyjconnorsesame** [jaegertracing/jaeger-operator#1001]
The default jaeger-query service maps ports 16686:16686 however I need a port forward on the service to 80->16686

i tried adding to the Jaeger definition
```
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
```

however it was ignored, my workaround for this is to introduce another jaeger-query service just to map this port but thats not ideal

Is there an override for port forwarding on the generated jaeger-query service?
