### ISSUE TITLE
Use Jaeger-OTEL collector in jaeger-operator

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1004]
Is our aim to swap jaeger-collector with jaeger-opentelemetry-collector in Jaeger CR (e.g. just change the collector image in https://godoc.org/github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1#JaegerCollectorSpec)? If so the main problem is configuration otel-collector is configured via configuration file and storage in Jaeger CR is configured by flags - more in https://github.com/jaegertracing/jaeger-opentelemetry-collector/issues/7

The other shade area is the relationship between jaeger-operator and otel-operator (https://github.com/open-telemetry/opentelemetry-operator). For instance if jaeger-operator will start using jaeger-otel-collector (presumably in agent and collector mode) there might not be a need to integrate with otel-collector. Alternatively, Jaeger operator could deprecate its collector and purely integrate with otel-collector.

cc) @jpkrohling

**Comment by objectiser** [comment]
Think it might be better to just support OTC via the OpenTelemetry Operator - and not embedded its configuration in the Jaeger CR. So just deprecate agent, collector and ingester parts of Jaeger CR.

Remaining responsibility of Jaeger operator would be all-in-one and query component, both requiring storage details still - which might be another reason to leverage the OTel Operator independently, so the storage details are not being duplicated in the same CR.

**Comment by pavolloffay** [comment]
I am sharing some updates:

The Jaeger OpenTelemetry collector will use opinionated configuration and always by default enable Jaeger receiver, some processors (TBD) and storage exporter. The collector can be configured via old Jaeger storage flags and also via OpenTelemetry configuration file. The configuration is merged with the default configuration and it takes precedence.

That said we will be able to use Jaeger OTEL collector with Jaeger CR by just simply overriding the image, but in addition to that we should expose OTEL configuration in each component (collector, agent, ingester) that is based on OTEL. 

One possible approach is to embed the config directly in the CR as in the following example or just reference a config map.

```yaml
```

**Comment by objectiser** [comment]
Following further discussions internally, this does seem like a good approach. It doesn't preclude the OTel Operator being used in the future, along with the Jaeger operator (CR), but taking this approach would enable Jaeger to more seamlessly transition to using OTel Collector.

**Comment by spuny** [comment]
There had to be some changes cause it does not work any further.
Pod is complaining about the LP/RP on port 14269. There is no such open port on the pod even i sticked with the health_check on this port in config.
Even tho there is config to open this port nothing is there and the probe fails so this approach is no longer available

part of pod config (from running one)
`
 livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 14269
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    name: jaeger-collector
    ports:
    - containerPort: 9411
      name: zipkin
      protocol: TCP
    - containerPort: 14267
      name: c-tchan-trft
      protocol: TCP
    - containerPort: 14268
      name: c-binary-trft
      protocol: TCP
    - containerPort: 14269
      name: admin-http
      protocol: TCP
    - containerPort: 14250
      name: grpc
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 14269
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
`
I would like to know what is the approach now cause i don't want to spin up another operator or add opentelemetry collector by itself. I would like to keep it as simple as possible.

Thanks for advice if there is any.

**Comment by jpkrohling** [comment]
@spuny, would you mind providing a Jaeger CR that exemplifies the problem you are facing?

**Comment by spuny** [comment]
@jpkrohling sure
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-dev
  namespace: services-dev
spec:
  strategy: production
  collector:
    # modify image tag to have sustainable version
    image: jaegertracing/jaeger-opentelemetry-collector:latest
    config: |
      exporters:
        jaeger_elasticsearch:
          es:
           server-urls: http://elasticsearch-dev-master:9200
           num-replicas: 2
      processors:
        attributes:
          actions:
            - key: user
              action: delete
        #queued_retry: {}
        #        batch:
        #        memory_limiter:
        #          # Same as --mem-ballast-size-mib CLI argument
        #          ballast_size_mib: 683
        #          # 80% of maximum memory up to 2G
        #          limit_mib: 1500
        #          # 25% of limit up to 2G
        #          spike_limit_mib: 512
        #          check_interval: 5s
      service:
        pipelines:
          traces:
              #receivers: [otlp, jaeger]
              #processors: [memory_limiter, batch]
            processors: [attributes]
              #processors: [queued_retry]
              #exporters: [jaeger]
    maxReplicas: 5
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  agent:
    #strategy: DaemonSet
    options:
      log-level: debug
  query:
    serviceType: NodePort
    nodePort: 30333
  storage:
    type: elasticsearch
    options:
      es:
        # be sure to provide correct url!!
        server-urls: http://elasticsearch-dev-master:9200
        num-shards: 3
        # be sure to provide correct index
        index-prefix: dev
    esIndexCleaner:
      enabled: true # turns job on and off
      numberOfDays: 7 # retention time period of trace
      schedule: "55 23 * * *" # cron expression to run it
  ingress:
    enabled: true
    hosts:
      - jaeger.taikun.dev
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-dev"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "185.22.97.99/32,192.168.50.0/24,185.22.97.248/32,195.216.230.81/32"
    tls:
    - secretName: jaeger.taikun.dev
      hosts:
        - jaeger.taikun.dev

  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 2048Mi
      cpu: 512m
```

**Comment by jpkrohling** [comment]
There's a lot going on there. Are you able to come up with the simplest CR that demonstrates the problem?

**Comment by jpkrohling** [comment]
@pavolloffay, do you remember if that image opened the health check port by default?

**Comment by spuny** [comment]
@jpkrohling ok looks like there is some problem in mine config, here is the log from simplified config i attach:
```
+ simple-prod-collector-5d6db87d75-4j6gq › jaeger-collector
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector 2021/08/19 10:04:46 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.1573496,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.157472,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.1579561,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.1590226,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.1590815,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.1989532,"caller":"config/config.go:183","msg":"Elasticsearch detected","version":7}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.5085232,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.5091746,"caller":"server/http.go:47","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.509648,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"}
simple-prod-collector-5d6db87d75-4j6gq jaeger-collector {"level":"info","ts":1629367486.5097125,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
```
config:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    config: |
      exporters:
        jaeger_elasticsearch:
          es:
            server-urls: http://elasticsearch-dev-master:9200
            num-replicas: 2
      processors:
        attributes:
          actions:
            - key: user
              action: delete
      service:
        pipelines:
          traces:
            processors: [attributes]
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-dev-master:9200
        num-shards: 3
```

The different thing is that there is no image specification. Looks like i got misleaded by all the threads i read today :D

When i change the image to image below it is not working as i described
````
jaegertracing/jaeger-opentelemetry-collector
```
 That is a problem cause i need port 4317 to be there (this is why i do this thing) cause i need to scrape jenkins via otlp.

**Comment by spuny** [comment]
In case of curiosity the original idea was from this source:
[https://medium.com/jaegertracing/jaeger-embraces-opentelemetry-collector-90a545cbc24](url)

**Comment by spuny** [comment]
Maybe there is confusion between healthcheck port on opentelemetry image:
```
2021-08-19T10:22:41.707Z	INFO	healthcheckextension/healthcheckextension.go:40	Starting health_check extension	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check", "config": {"TypeVal":"health_check","NameVal":"health_check","Port":13133}}
```
and replicase of jaeger CR which is looking for port 14269

**Comment by jpkrohling** [comment]
I thought @pavolloffay did the translation between the OpenTelemetry Collector standards and Jaeger's. In any case, you can configure the health-check extension to use the custom port. I don't remember which OpenTelemetry Collector version was used for this image, but something like this *might* work:

```
    config: | 
      extensions:
        health_check:
          port: 14269
      exporters:
        jaeger_elasticsearch:
          es:
            server-urls: http://elasticsearch-dev-master:9200
            num-replicas: 2
      processors:
        attributes:
          actions:
            - key: user
              action: delete
      service:
        extensions: [health_check]
        pipelines:
          traces:
            processors: [attributes]
```

Note that this OpenTelemetry-based Jaeger image is not supported, so, it's unlikely we'll fix any bugs caused by it. Jaeger v2, which is currently being planned, will be based on OpenTelemetry Collector though.

**Comment by spuny** [comment]
@jpkrohling thanks for your help sadly this is what i was encountering from the start

config:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    image: jaegertracing/jaeger-opentelemetry-collector:latest
    config: | 
      extensions:
        health_check:
          port: 14269
      exporters:
        jaeger_elasticsearch:
          es:
            server-urls: http://elasticsearch-dev-master:9200
            num-replicas: 2
      processors:
        attributes:
          actions:
            - key: user
              action: delete
      service:
        extensions: [health_check]
        pipelines:
          traces:
            processors: [attributes]
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-dev-master:9200
        num-shards: 3
```

Log:
```
+ simple-prod-collector-5c49bc9bd5-w4xqb › jaeger-collector
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.882Z	INFO	service/service.go:409	Starting Jaeger OpenTelemetry Collector...	{"Version": "v1.22.0", "GitHash": "5deca64aa8f72bfe4cc25f911371d708ac6459a6", "NumCPU": 16}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.882Z	INFO	service/service.go:253	Setting up own telemetry...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.884Z	INFO	service/telemetry.go:101	Serving Prometheus metrics	{"address": "localhost:8888", "level": 0, "service.instance.id": "b282dc91-d377-467b-8ff6-eaed275e0aa0"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.948Z	INFO	service/service.go:290	Loading configuration...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.975Z	INFO	service/service.go:301	Applying configuration...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.975Z	INFO	service/service.go:322	Starting extensions...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.975Z	INFO	builder/extensions_builder.go:53	Extension is starting...	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.975Z	INFO	healthcheckextension/healthcheckextension.go:40	Starting health_check extension	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check", "config": {"TypeVal":"health_check","NameVal":"health_check","Port":13133}}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:47.975Z	INFO	builder/extensions_builder.go:59	Extension started.	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:52.980Z	INFO	esclient/client.go:216	Elasticsearch detected	{"component_kind": "exporter", "component_type": "jaeger_elasticsearch", "component_name": "jaeger_elasticsearch", "version": 7}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/exporters_builder.go:306	Exporter is enabled.	{"component_kind": "exporter", "exporter": "jaeger_elasticsearch"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	service/service.go:337	Starting exporters...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/exporters_builder.go:92	Exporter is starting...	{"component_kind": "exporter", "component_type": "jaeger_elasticsearch", "component_name": "jaeger_elasticsearch"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/exporters_builder.go:97	Exporter started.	{"component_kind": "exporter", "component_type": "jaeger_elasticsearch", "component_name": "jaeger_elasticsearch"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/pipelines_builder.go:207	Pipeline is enabled.	{"pipeline_name": "", "pipeline_datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	service/service.go:350	Starting processors...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/pipelines_builder.go:51	Pipeline is starting...	{"pipeline_name": "", "pipeline_datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/pipelines_builder.go:61	Pipeline is started.	{"pipeline_name": "", "pipeline_datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.020Z	INFO	builder/receivers_builder.go:235	Receiver is enabled.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger", "datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.021Z	INFO	builder/receivers_builder.go:235	Receiver is enabled.	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp", "datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.021Z	INFO	service/service.go:362	Starting receivers...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.021Z	INFO	builder/receivers_builder.go:70	Receiver is starting...	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	builder/receivers_builder.go:75	Receiver started.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	builder/receivers_builder.go:70	Receiver is starting...	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	otlpreceiver/otlp.go:93	Starting GRPC server on endpoint 0.0.0.0:4317	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	otlpreceiver/otlp.go:130	Setting up a second GRPC listener on legacy endpoint 0.0.0.0:55680	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	otlpreceiver/otlp.go:93	Starting GRPC server on endpoint 0.0.0.0:55680	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	otlpreceiver/otlp.go:108	Starting HTTP server on endpoint 0.0.0.0:55681	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	builder/receivers_builder.go:75	Receiver started.	{"component_kind": "receiver", "component_type": "otlp", "component_name": "otlp"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	healthcheck/handler.go:128	Health Check state change	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check", "status": "ready"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T11:59:53.022Z	INFO	service/service.go:265	Everything is ready. Begin running and processing data.
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.193Z	INFO	service/service.go:278	Received signal from OS	{"signal": "terminated"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.193Z	INFO	service/service.go:445	Starting shutdown...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.193Z	INFO	healthcheck/handler.go:128	Health Check state change	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check", "status": "unavailable"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.193Z	INFO	service/service.go:378	Stopping receivers...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	service/service.go:384	Stopping processors...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	builder/pipelines_builder.go:69	Pipeline is shutting down...	{"pipeline_name": "", "pipeline_datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	builder/pipelines_builder.go:75	Pipeline is shutdown.	{"pipeline_name": "", "pipeline_datatype": "traces"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	service/service.go:390	Stopping exporters...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	service/service.go:400	Stopping extensions...
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	ERROR	jaegerreceiver/trace_receiver.go:366	http server failure	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger", "error": "http: Server closed"}
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector go.opentelemetry.io/collector/receiver/jaegerreceiver.(*jReceiver).startAgent.func1
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 	go.opentelemetry.io/collector@v0.16.0/receiver/jaegerreceiver/trace_receiver.go:366
simple-prod-collector-5c49bc9bd5-w4xqb jaeger-collector 2021-08-19T12:01:06.194Z	INFO	service/service.go:467	Shutdown complete.
```

Main problem is still with the readiness probe. But as you said it is not supported so i will stick with standalone approach of opentelemetry collector. Thanks so much and have a nice day.
Looking forward to Jaeger v2 👍
