### ISSUE TITLE
collector-tls-config-volume Not Created

### ISSUE THREAD

**Issue by chaospuppy** [jaegertracing/jaeger-operator#1029]
Summary: 
Jaeger Pods are failing to be created due to missing "\<deployments-name\>-collector-tls-config-volume" secret.

Platform:
OSE 3.11

Images:
jaegertracing/jaeger-operator:1.17.1
jaegertracing/all-in-one:1.17.1

CSV:
1.17.1

OLM Version:
0.12.0

Jaeger Custom Resource yaml:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  storage:
    type: badger
    options:
      badger:
        ephemeral: true
        directory-key: /badger/key
        directory-value: /badger/data
  volumeMounts:
  - name: data
    mountPath: /badger
  volumes:
  - name: data
    emptyDir: {}
```

What is happening:
Jaeger pods fail to start, citing the following error:
- MountVolume.SetUp failed for volume "\<deployment-name\>-collector-tls-config-volume" : secrets "\<deployment-name\>-collector-headless-tls" not found

What is expected:
Jaeger pods start successfully

Also of note:
The Custom Resource described above worked fine up until last week, when cached images refreshed, including the jaegertracing/all-in-one:1.17.1 image.
