### ISSUE TITLE
TLS trust store for kafka/storage and oauth

### ISSUE THREAD

**Issue by chlunde** [jaegertracing/jaeger-operator#1043]
The OpenShift API server, kafka and elasticsearch TLS certificates can be issued by other CA (public or private company CA) in some deployments. This is currently not supported.

In OpenShift, it is possible to request a TLS trust bundle injected into a configMap, see https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: trust
```
# Possible fix

## Producer/consumer config
```bash
        - --kafka.producer.tls.ca=/etc/trust/tls-ca-bundle.pem
[...]
        - --kafka.consumer.tls.ca=/etc/trust/tls-ca-bundle.pem

```

```yaml
        - mountPath: /etc/trust
          name: trust-volume
          readOnly: true
[...]
      - configMap:
          name: trust
        name: trust-volume
```

It might be possible to mount it over the existing TLS trust bundle to avoid custom paths like /etc/trust in this example. I did this for the oauth2-sidecar:

## Oauth config/query

```
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: trust-volume
          readOnly: true
```

```
      - configMap:
          name: trust
          items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
        name: trust-volume
```
