### ISSUE TITLE
Remote Sampling is not working as expected

### ISSUE THREAD

**Issue by Catorpilor** [jaegertracing/jaeger-operator#1071]
I'm using the latest operator, with the following configuration
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  agent:
    options:
      log-level: debug
  collector:
    options:
      log-level: debug
  sampling:
    options:
      service_strategies:
        - service: jaeger-example
          type: probabilistic
          param: 0.1
          operation_strategies:
            - operation: /getTime
              type: probabilistic
              param: 0.2
            - operation: /drivers
              type: probabilistic
              param: 0.4
      default_strategy:
        type: probabilistic
        param: 0.2
      operation_strategies:
        - operation: /health-check
          type: probabilistic
          param: 0.0
        - operation: /metrics
          type: probabilistic
          param: 0.0
        - operation: /healthz
          type: probabilistic
          param: 0.0
  storage:
    type: elasticsearch
```
I create a `tracer` using the following code in my `jaeger-example` 
```
        cfg, err := config.FromEnv()
	if err != nil {
		logger.Bg().Fatal(err.Error())
	}
	cfg.ServiceName = serviceName
	cfg.Sampler.Type = "remote"
	jaegerLogger := jaegerLoggerAdapter{logger.Bg()}
	tracer, _, err := cfg.NewTracer(
		config.Logger(jaegerLogger),
		config.Metrics(metricsFactory),
		config.Observer(rpcmetrics.NewObserver(metricsFactory, rpcmetrics.DefaultNameNormalizer)),
		config.ZipkinSharedRPCSpan(true),
	)
	if err != nil {
		logger.Bg().Fatal("cannot initialize Jaeger Tracer", zap.Error(err))
	}
	return tracer
```

`jaeger-example` **sampling** output in `simple-prod-collector`
```
bash-5.0# curl localhost:14268/api/sampling?service=jaeger-example | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
{
  "strategyType": "PROBABILISTIC",
  "probabilisticSampling": {
    "samplingRate": 0.1
  },
  "operationSampling": {
    "defaultSamplingProbability": 0.1,
    "defaultLowerBoundTracesPerSecond": 0,
    "perOperationStrategies": [
      {
        "operation": "/getTime",
        "probabilisticSampling": {
          "samplingRate": 0.2
        }
      },
      {
        "operation": "/drivers",
        "probabilisticSampling": {
          "samplingRate": 0.4
        }
      }
    ]
  }
}
```
default sampling output:
```
bash-5.0# curl localhost:14268/api/sampling?service=jaege | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    77  100    77    0     0  25666      0 --:--:-- --:--:-- --:--:-- 25666
{
  "strategyType": "PROBABILISTIC",
  "probabilisticSampling": {
    "samplingRate": 0.2
  }
}
```

and the related metrics
```
# HELP jaeger_example_jaeger_tracer_sampler_queries_total Number of times the Sampler succeeded to retrieve sampling strategy
# TYPE jaeger_example_jaeger_tracer_sampler_queries_total counter
jaeger_example_jaeger_tracer_sampler_queries_total{result="err"} 0
jaeger_example_jaeger_tracer_sampler_queries_total{result="ok"} 6
# HELP jaeger_example_jaeger_tracer_sampler_updates_total Number of times the Sampler succeeded to retrieve and update sampling strategy
# TYPE jaeger_example_jaeger_tracer_sampler_updates_total counter
jaeger_example_jaeger_tracer_sampler_updates_total{result="err"} 0
jaeger_example_jaeger_tracer_sampler_updates_total{result="ok"} 6
```
However i still see traces on `/healthz` operation.
<img width="1310" alt="Screenshot 2020-05-29 17 10 38" src="https://user-images.githubusercontent.com/558701/83242780-8501a080-a1cf-11ea-974d-5e9a11332c78.png">

and the `/drivers` using the default probabilistic not the one defined in `perOperationStrategies`
<img width="1323" alt="Screenshot 2020-05-29 17 13 17" src="https://user-images.githubusercontent.com/558701/83243027-e7f33780-a1cf-11ea-8385-508eb4cf53b1.png">
