### ISSUE TITLE
Recommended way to enable resources on Jaeger agent sidecars

### ISSUE THREAD

**Issue by AdityaBhansali1** [jaegertracing/jaeger-operator#1074]
Hello,

I am looking for the recommended way to enable resources on auto-injected Jaeger agent sidecar container. This is required for enabling metrics on my service pod and hence enable the k8s horizontal pod autoscaling for my service.

More details -
Jaeger operator is installed with below command.
```
helm install -n ops jaeger-operator jaegertracing/jaeger-operator --set rbac.clusterRole=true
```

Jaeger is installed with below definition.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
spec:
  strategy: production
  collector:
    replicas: 3
    autoscale: false    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-client:9200
    esIndexCleaner:
      enabled: false
```

Service uses the jaeger sidecar injection annotation as below
```
sidecar.jaegertracing.io/inject: true
```

Regards,
Aditya
