### ISSUE TITLE
jaeger has no endpoint

### ISSUE THREAD

**Issue by zackzhangkai** [jaegertracing/jaeger-operator#1076]
I met with some problems when  upgrade jaeger 1.13.1 to 1.17.1. The metric and tracing display faild. Then when I consult the log , and found some errors.

```
# k logs -f jaeger-query-99bc97598-7bsqv jaeger-agent

{"level":"warn","ts":1590767929.0646005,"caller":"grpc@v1.27.1/clientconn.go:1223","msg":"grpc: addrConn.createTransport failed to connect to {10.233.75.44:14250  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 10.233.75.44:14250: connect: connection refused\". Reconnecting...","system":"grpc","grpc_log":true}
```

Then I consult the IP 10.233.75.44, found no such endpoint matched.

```
jaeger-operator istio-system    1               2020-05-30 07:06:43.535284201 +0000 UTC deployed        jaeger-operator-2.14.2  1.17.1
[root@node1 ~]# k get ep | grep jaeger
jaeger-collector            10.233.102.179:9411,10.233.102.179:14268,10.233.102.179:14250 + 1 more...   5h19m
jaeger-collector-headless   10.233.102.179:9411,10.233.102.179:14268,10.233.102.179:14250 + 1 more...   5h19m
jaeger-operator             <none>                                                                      5h19m
jaeger-operator-metrics     <none>                                                                      169m
jaeger-query                10.233.71.56:16686                                                          5h19m
```

The jaeger-operator and jaeger-operator-metrics has no endpoints. I think this may be the main reason that why my problem was.

What's the matter?How can I fix it?

I installe jaeger with the chart in official repositry and consult the official steps.
https://github.com/jaegertracing/helm-charts

My version is 1.17.
```
[root@node1 ~]# helm list | grep jaeger
jaeger-operator istio-system    1               2020-05-30 07:06:43.535284201 +0000 UTC deployed        jaeger-operator-2.14.2  1.17.1
```
Here is my crd:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-05-29T11:48:03Z"
  generation: 1
  labels:
    app: jaeger-operator
  name: jaegers.jaegertracing.io
  resourceVersion: "75598"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/jaegers.jaegertracing.io
  uid: f5b7722d-0b14-41b4-b60e-a6f1b8102c05
spec:
  conversion:
    strategy: None
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Jaeger instance's status
      jsonPath: .status.phase
      name: Status
      type: string
    - description: Jaeger Version
      jsonPath: .status.version
      name: Version
      type: string
    name: v1
    served: true
    storage: true
    sub
....
```

my jaeger
```
k get jaeger -o yaml

apiVersion: v1
items:
- apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"jaegertracing.io/v1","kind":"Jaeger","metadata":{"annotations":{},"name":"jaeger","namespace":"istio-system"},"spec":{"agent":{"image":"jaegertracing/jaeger-agent:1.17"},"collector":{"image":"jaegertracing/jaeger-collector:1.17"},"query":{"image":"jaegertracing/jaeger-query:1.17"},"storage":{"dependencies":{"enabled":false},"esIndexCleaner":{"enabled":false},"options":{"es":{"index-prefix":"logstash","server-urls":"http://elasticsearch-logging-data.kubesphere-logging-system.svc.cluster.local:9200"}},"type":"elasticsearch"},"strategy":"production"}}
    ...
  status:
    phase: Running
    version: 1.17.1
kind: List
metadata:
  resourceVersion:
```

service:
```
[root@node1 ~]# k get svc|grep jaeger
jaeger-collector            ClusterIP   10.233.30.158   <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP                                                                                                       5h50m
jaeger-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP                                                                                                       5h50m
jaeger-operator             ClusterIP   10.233.52.172   <none>        8383/TCP                                                                                                                                     5h50m
jaeger-operator-metrics     ClusterIP   10.233.60.51    <none>        8383/TCP,8686/TCP                                                                                                                            3h20m
jaeger-query                ClusterIP   10.233.7.104    <none>        16686/TCP                                                                                                                                    5h50m
```

deployments:

```
[root@node1 ~]# k get deploy|grep jaeger
jaeger-collector         1/1     1            1           5h50m
jaeger-operator          1/1     1            1           3h21m
jaeger-query             1/1     1            1           5h50m
```
pods
```
[root@node1 ~]# k get po |grep jaeger
jaeger-collector-6946ff858b-527hp        1/1     Running     0          9h
jaeger-operator-fb6cbd87f-w65cb          1/1     Running     0          16m
jaeger-query-99bc97598-82cgq             2/2     Running     0          9h
```
