### ISSUE TITLE
Add k8s job TTL to cleaner jobs

### ISSUE THREAD

**Issue by jdomag** [jaegertracing/jaeger-operator#1082]
Hi, 
Would be great to implement 
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

into storage backend :

storage:
  type: elasticsearch
  esIndexCleaner:
    enabled: true                                 // turn the cron job deployment on and off
    numberOfDays: 7                               // number of days to wait before deleting a record
    schedule: "55 23 * * *"                       // cron expression for it to run
    **ttl: 10m**   -> ttlafterfinished parameter

otherwise all the cleaner jobs are hanging in k8s forever.

**Comment by jdomag** [comment]
@jpkrohling 
Thanks, finally found it

```
  spec:
    strategy: production
    storage:
      type: elasticsearch
      collector:
        autoscale: false
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
      esIndexCleaner:
        enabled: true
        numberOfDays: 1
        schedule: "0 2 * * *"
        ttlSecondsAfterFinished: 60
```
Now I'm struggling with disabling spark dependecies job. 
Is there any documentation for jaeger operator presenting all the available configuration options?
I find it very confusing that values from Jaeger helm chart:
https://github.com/jaegertracing/helm-charts/tree/master/charts/jaeger
Doesn't match value schema of operator. Looking at a Jaeger helm chart i figured that spar job is controller by .Values.spark.enabled   so i thought i disable it via setting values of operator as follows:
```
jaeger:
  create: true
  spec:
    spark:
      enabled: false
```
But it doesnt work this way.

**Comment by jpkrohling** [comment]
In a regular CR, it can be disabled by setting `.Spec.Storage.Dependencies.Enabled` to false, like:

```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  ...
  storage:
    dependencies:
      enabled: false
```

Not sure how that translates in the Helm Chart.

**Comment by jdomag** [comment]
Thanks that did a trick.
Solution for jeager-operator:

```
jaeger:
  # Specifies whether Jaeger instance should be created
  create: true

  spec:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    strategy: production
    storage:
      dependencies:
        enabled: false
      type: elasticsearch
      collector:
        autoscale: false
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
      esIndexCleaner:
        enabled: true
        numberOfDays: 1
        schedule: "0 2 * * *"
        ttlSecondsAfterFinished: 60
      options:
        es:
          server-urls: https://localhost:443
          num-shards: 1
          num-replicas: 0
```
