### ISSUE TITLE
Remote Sampling Not working when split agent and collector definition in two files.

### ISSUE THREAD

**Issue by Catorpilor** [jaegertracing/jaeger-operator#1107]
Everything works fine when define `agent` and `collector` in one file.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  agent:
    strategy: DaemonSet
    options:
      log-level: debug
  collector:
    minReplicas: 1
    maxReplicas: 5
    options:
      log-level: debug
  sampling:
    options:
      service_strategies:
        - service: jaeger-example
          type: probabilistic
          param: 0.1
          operation_strategies:
            - operation: /getTime
              type: probabilistic
              param: 0.2
            - operation: /drivers
              type: probabilistic
              param: 0.4
      default_strategy:
        type: probabilistic
        param: 0.2
        operation_strategies:
          - operation: /health-check
            type: probabilistic
            param: 0.0
          - operation: /metrics
            type: probabilistic
            param: 0.0
          - operation: /healthz
            type: probabilistic
            param: 0.0
          - operation: /ping
            type: probabilistic
            param: 0.0
    ingress:
        enable: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "700m"
  securityContext:
    runAsUser: 1000
```
However we just want to schedule `collector&query` pods  use `affinity` to specified nodes. The previous definition file not working because it also schedule the `agent` to the specified nodes.
So we use two files just follow the [example](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/agent-as-daemonset.yaml) 
the current `agent` definitions is
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod 
spec:
  strategy: production
  agent:
    strategy: DaemonSet
    options:
      log-level: debug
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "1Gi"
      cpu: "700m"
  securityContext:
    runAsUser: 1000
```
and the rest part
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    options:
      log-level: debug
  sampling:
    options:
      service_strategies:
        - service: jaeger-example
          type: probabilistic
          param: 0.1
          operation_strategies:
            - operation: /getTime
              type: probabilistic
              param: 0.2
            - operation: /drivers
              type: probabilistic
              param: 0.4
      default_strategy:
        type: probabilistic
        param: 0.2
        operation_strategies:
          - operation: /health-check
            type: probabilistic
            param: 0.0
          - operation: /metrics
            type: probabilistic
            param: 0.0
          - operation: /healthz
            type: probabilistic
            param: 0.0
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true                                 
      numberOfDays: 7                               
      schedule: "55 23 * * *"
    dependencies:
        enabled: false
    options:
      es:
        server-urls:  es-url
        num-replicas: 0
        num-shards: 1
    ingress:
        enable: false
  resources:
    requests:
      memory: "250Mi"
      cpu: "200m"
    limits:
      memory: "4Gi"
      cpu: "700m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: intend
            operator: In
            values:
            - "system"
  securityContext:
    runAsUser: 1000
```
I test the sampling strategy on the collector side and it works as expected.
```
bash-5.0# curl localhost:14268/api/sampling?service=jaeger-example | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   545  100   545    0     0   177k      0 --:--:-- --:--:-- --:--:--  177k
{
  "strategyType": "PROBABILISTIC",
  "probabilisticSampling": {
    "samplingRate": 0.1
  },
  "operationSampling": {
    "defaultSamplingProbability": 0.1,
    "defaultLowerBoundTracesPerSecond": 0,
    "perOperationStrategies": [
      {
        "operation": "/getTime",
        "probabilisticSampling": {
          "samplingRate": 0.2
        }
      },
      {
        "operation": "/drivers",
        "probabilisticSampling": {
          "samplingRate": 0.4
        }
      },
      {
        "operation": "/health-check",
        "probabilisticSampling": {
          "samplingRate": 0
        }
      },
      {
        "operation": "/metrics",
        "probabilisticSampling": {
          "samplingRate": 0
        }
      },
      {
        "operation": "/healthz",
        "probabilisticSampling": {
          "samplingRate": 0
        }
      }
    ]
  }
}
```
but on the `agent` side i get
```
bash-5.0# curl localhost:5778/sampling?service=jaeger-example | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0  12500      0 --:--:-- --:--:-- --:--:-- 12500
{
  "strategyType": "PROBABILISTIC",
  "probabilisticSampling": {
    "samplingRate": 1
  }
}
```

the `agent` pod definition 
```
- name: jaeger-agent-daemonset
      image: 'jaegertracing/jaeger-agent:1.18.0'
      args:
        - '--log-level=debug'
        - >-
          --reporter.grpc.host-port=dns:///simple-prod-collector-headless.observability:14250
        - '--reporter.type=grpc'
```

<img width="1493" alt="Screenshot 2020-06-27 11 32 13" src="https://user-images.githubusercontent.com/558701/85913746-f5045480-b869-11ea-87be-327a2c9d7169.png">

**Comment by jpkrohling** [comment]
I don't think this will actually work, and I'm surprised you have a `DaemonSet` once you apply your second YAML (the one with the collector). The operator should be removing it ;-)

We have only one CR, and that is to specify a whole Jaeger instance, including collector, query and agent (among others). When one of those components are missing from the CR, the defaults are applied.

Concrete to your case, it means that:

1. you are using two CR files with the same instance name (`simple-prod`), so that only one of them will be active at any given time, namely, the last one you applied
1. when you apply your agent CR, you are probably getting a "all-in-one" with in-memory storage
1. once you apply your collector CR, you are probably getting agent set to deployment type "sidecar"
1. you still have an agent daemonset running probably due to a bug in the operator, as it should remove things that shouldn't be deployed

To achieve your original goal, you can set the affinity expressions at the individual nodes (collector, query), like in this untested excerpt:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    options:
      log-level: debug
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: intend
              operator: In
              values:
              - "system"
  query:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: intend
              operator: In
              values:
              - "system"
```
