### ISSUE TITLE
Why is there no agent service in SVC?

### ISSUE THREAD

**Issue by kakaNo1** [jaegertracing/jaeger-operator#1149]
![image](https://user-images.githubusercontent.com/33709305/89270676-47594200-d66e-11ea-9c93-c8245e4e1ffd.png)

My profile:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: observability
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://xxxxx:9200
  ingress:
    enabled: false
  agent:
    strategy: DaemonSet
```
