### ISSUE TITLE
Kafka customization

### ISSUE THREAD

**Issue by daroga0002** [jaegertracing/jaeger-operator#1155]
I am using following definition of operator:
```
image:
  repository: jaegertracing/jaeger-operator
  tag: 1.18.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

crd:
  install: true

jaeger:
  create: true
  spec:
    strategy: streaming
    ingester:
      maxReplicas: 8
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
    storage:
      type: elasticsearch
# Disable "Deriving dependencies" feature
      dependencies:
        enabled: false 
      options:
        es:
          use-aliases: true
          server-urls: http://jeager-elasticsearch-master:9200
```

and this is creating me Kafka using Strizmi operator. Question which I have are there any parameters which can be influence current strimzi created object, especially volume size used by Kafka and zookeeper which currently create me PVC 100GB each (so totally Kafka takes 600GB).

I tried to look but didnt find any docs about this
