### ISSUE TITLE
Allow storage.options.cassandra.password to have an `existingSecret` reference to pick up cassandra password from

### ISSUE THREAD

**Issue by Hashfyre** [jaegertracing/jaeger-operator#1162]
HI,

There is ability to connect Cassandra storage with username and password through jaeger-operator, but there is no way to use a kubernetes secret for the password field and the Jaeger CR would need to have it in plaintext. This is an issue since we would store the Jaeger CR definition in git.

Even with templating through helm/kustomize, it'd mean the operator needs to store the secret somewhere in their own env. A much cleaner way would be able to refer to an existing kubernetes secret.

a `useExistingSecret: <kubernetes secret name>` would help here, since we would spin up cassandra with either the bitnami/cassandra chart or scylla-operator (among others), both of which support the `existingSecret` paradigm to create the clusters.

**Comment by jpkrohling** [comment]
You can mount a secret into env vars: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

Wouldn't that work for you?

**Comment by Hashfyre** [comment]
Secret mounting would not work for the Jaeger CustomResource.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-streaming
spec:
  ...
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra.cassandra.svc.cluster.local
        keyspace: test
        username: cassandra
        password: CASSANDRA_PASS // <- this is how the CR accepts passwords
    cassandraCreateSchema:
      datacenter: dc1
      mode: "test"
      timeout: "3m"
```
Secret mounting works on Standard K8S GVKs, not for CRs

**Comment by jpkrohling** [comment]
Sorry, you are absolutely correct, but we actually do support building env vars from secrets in a different way:

[Excerpt](https://www.jaegertracing.io/docs/1.18/operator/#external-elasticsearch) from the docs:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://quickstart-es-http.default.svc:9200
    secretName: jaeger-secret
```

The secret would then contain the env vars and values to be passed down to the collector/query/ingester. You can generate the secret like this:

```console
$ kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=changeme --from-literal=ES_USERNAME=elastic
```

While this shows the usage for ES, it should apply for Cassandra as well. I think we do need a better documentation for this, though.
