### ISSUE TITLE
gRPC flags shouldn't be added if host-port is specified by the CR

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1164]
Given the following CR:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  allInOne:
    options:
      reporter.grpc.host-port: "opentelemetrycollector-sample-collector-headless.default.svc:14250"
```

The Jaeger Operator should *not* be adding the other inferred gRPC options. Using the CR above, the following is the set of options passed to the binary:

```
        - --collector.grpc.tls.cert=/etc/tls-config/tls.crt
        - --collector.grpc.tls.enabled=true
        - --collector.grpc.tls.key=/etc/tls-config/tls.key
        - --query.ui-config=/etc/config/ui.json
        - --reporter.grpc.host-port=opentelemetrycollector-sample-collector-headless.default.svc:14250
        - --reporter.grpc.tls.ca=/etc/pki/ca-trust/source/service-ca/service-ca.crt
        - --reporter.grpc.tls.enabled=true
        - --reporter.grpc.tls.server-name=simplest-collector-headless.default.svc.cluster.local
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
```

A workaround is to manually set those flags in the CR.
