### ISSUE TITLE
Manually installed agent doesn't send spans to collector 

### ISSUE THREAD

**Issue by AlexZalyalowa** [jaegertracing/jaeger-operator#1181]
Hello.
I've installed jaeger on minikebe
```
kubectl create namespace observability
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml
```
operator was started in debug mode. Jseger was launched via AllInOne strategy

```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.19.0
    options:
      log-level: debug
```

Then I have installed jaeger-agent manually in frontend's deployment
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
#  annotations:
#    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.19.0  # The agent version should match the operator version
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
        args:
          - --reporter.grpc.host-port=dns:///jaeger-collector-headless.observability:14250
          - --log-level=debug
```

There is agent's logs
```
kubectl -n observability logs frontend-66d4f8d84d-5rj96 -c jaeger-agent 
2020/09/04 14:22:00 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
{"level":"info","ts":1599229320.6102307,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1599229320.6106718,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1599229320.6107538,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":14271"}
{"level":"info","ts":1599229320.6107972,"caller":"flags/admin.go:112","msg":"Admin server started","http.host-port":"[::]:14271","health-status":"unavailable"}
{"level":"info","ts":1599229320.6121032,"caller":"grpc/builder.go:66","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1599229320.6121604,"caller":"grpc@v1.28.0-pre/clientconn.go:106","msg":"parsed scheme: \"dns\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1599229320.6158354,"caller":"command-line-arguments/main.go:78","msg":"Starting agent"}
{"level":"info","ts":1599229320.6159358,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1599229320.6159694,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1599229320.7698443,"caller":"dns/dns_resolver.go:212","msg":"ccResolverWrapper: sending update to cc: {[{172.18.0.4:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1599229320.7699046,"caller":"grpc@v1.28.0-pre/clientconn.go:948","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1599229320.7710843,"caller":"base/balancer.go:170","msg":"roundrobinPicker: newPicker called with info: {map[0xc0003a61e0:{{172.18.0.4:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1599230482.1418839,"caller":"base/balancer.go:170","msg":"roundrobinPicker: newPicker called with info: {map[]}","system":"grpc","grpc_log":true}
{"level":"warn","ts":1599230482.1421309,"caller":"grpc@v1.28.0-pre/clientconn.go:1223","msg":"grpc: addrConn.createTransport failed to connect to {172.18.0.4:14250  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 172.18.0.4:14250: connect: connection refused\". Reconnecting...","system":"grpc","grpc_log":true}
{"level":"info","ts":1599230482.2260365,"caller":"dns/dns_resolver.go:212","msg":"ccResolverWrapper: sending update to cc: {[{172.18.0.3:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1599230482.226315,"caller":"base/balancer.go:170","msg":"roundrobinPicker: newPicker called with info: {map[]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1599230482.2273655,"caller":"base/balancer.go:170","msg":"roundrobinPicker: newPicker called with info: {map[0xc0004a0180:{{172.18.0.3:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
```

metrics are accessible from frontend's pod  via curl http://jaeger-collector-headless:14269/metrics, but there is no any sighn of frontend service in it
```
root@frontend-66d4f8d84d-5rj96:/var/www/html# curl http://jaeger-collector-headless:14269/metrics | grep frontend
root@frontend-66d4f8d84d-5rj96:/var/www/html# 
```
