### ISSUE TITLE
Configure the JaegerOperator to use the OpenTelemetry collector with the Opencensus receiver enabled

### ISSUE THREAD

**Issue by adinhodovic** [jaegertracing/jaeger-operator#1184]
How do I configure the JaegerOperator to use the OpenTelemetry collector with the OpenCensus & otlp receivers enabled? And how would I then open ports to the pod and additionally extend the default service to add that port using the operator?

I've tried the following for the first part:
```yaml
  collector:
    config:
      receivers:
        opencensus:
          address: "localhost:55678"
      extensions:
        health_check:
          port: 14269
    image: jaegertracing/jaeger-opentelemetry-collector:latest
```
Getting errors on startup:
```sh
2020/09/07 19:13:22 Failed to run the service: cannot load configuration: error reading receivers configuration for opencensus: 1 error(s) decoding: * '' has invalid keys: address
```
If I pass the first obstacle how would I then add additional container ports for the receiver?
