### ISSUE TITLE
ServiceAccount needs to be created before ES rollover job

### ISSUE THREAD

**Issue by bastianeicher** [jaegertracing/jaeger-operator#1208]
I deployed Jaeger Operator v1.19.0 and an Elasticsearch instance in the same Kubernetes namespace. I then created the following resource:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  collector:
    maxReplicas: 20
    autoScale: true
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://jaeger-elasticsearch-master:9200
        use-aliases: true
    esRollover:
      enabled: true
      conditions: "{\"max_age\": \"2d\"}"
      readTTL: 168h
      schedule: "55 23 * * *"
```

Jaeger Operator then creates a `Job` named `jaeger-es-rollover-create-mapping`. However this `Job` fails to start because it references a not-yet-existing `ServiceAccount` named `jaeger`. If I do nothing the Operator keeps waiting for this `Job` and eventually marks the `Jaeger` instance as "Failed".

```
level=debug msg="Waiting for dependency to complete" name=jaeger-es-rollover-create-mapping
level=error msg="failed to apply the changes" error="timed out waiting for the condition"
```

If I run `kubectl create sa jaeger` the `Job` succeeds, allowing Jaeger Operator to progress.
Then the Operator tries to create the `ServiceAccount` itself but fails because it already exists.

```
level=error msg="failed to apply the changes" error="serviceaccounts \"jaeger\" already exists"
```

**TL;DR:** Jaeger Operator seems to be creating `Job`s before `ServiceAccount`s but this should probably be the other way round.
