### ISSUE TITLE
jeager-operator overrides changes I made in jaeger-operator-jaeger deployment

### ISSUE THREAD

**Issue by dwertent** [jaegertracing/jaeger-operator#1211]
Hi,
I'm running the jaeger operator solution. 
I added a simple volume to the deployment (using `kubectl patch`), and I see that the jeager operator that is constantly running, overrides my changes.
Is there a way to change the deployment in a way the operator will not override my changes right away (maybe by adding an annotation/label or something to do with the kube-api configurations)?

Currently I disabled the jeager-operator from running but I must find a better solution.
Any ideas? Thank you!

**Comment by jpkrohling** [comment]
> I added a simple volume to the deployment

Which deployment are you talking about? The Jaeger Collector/Query/Ingester? You shouldn't manually change those deployments, or any other resource managed by the Operator. At each reconciliation, the Operator will build a map of what's the expected state, and what's the observed state, and apply the necessary changes to make the two match. If you don't tell which volume to mount in the CR, the operator will remove the extraneous volume.

You can specify the volumes you want mounted as part of the Jaeger CR. Here's an example:

https://github.com/jaegertracing/jaeger-operator/blob/aba6e4d640460d7b0ebcb4b24f401ec6532ddbde/deploy/examples/simple-prod-with-volumes.yaml#L2-L19

This will mount the volume in all underlying deployments (collector, query, ingester).

You can also specify the volume/volumeMounts options under the specific component that should have this:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    volumeMounts:
    - name: certs
      mountPath: /etc/certs
    volumes:
    - name: certs
      emptyDir: {}
```
