### ISSUE TITLE
jaeger-operator 1.20.0  imagepullsecrets with jaeger-collector deployment?

### ISSUE THREAD

**Issue by fxgagnon** [jaegertracing/jaeger-operator#1236]
I have jaeger operator, version 1.20.0, running on a k8s cluster.  I'm trying to use a custom repository for in the jaeger kind.  It look like this ;

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jeager-op
  namespace: jaeger-01
spec:
  ingress:
    enabled: false
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master.elasticsearch-01.svc:9200
        index-prefix: jaeger-01
    esIndexCleaner:
      image: mylocalresistry.com/jaeger-es-index-cleaner:1.20
      imagePullSecrets:
      - name: registre-images
    dependencies:    
      image: mylocalresistry.com/jaeger-spark-dependencies:latest
      imagePullSecrets:
      - name: registre-images              
  agent:
    image: mylocalresistry.com/jaeger-agent:1.20
    imagePullSecrets:
    - name: registre-images    
  ingester:
    image: mylocalresistry.com/jaeger-ingester:1.20
    imagePullSecrets:
    - name: registre-images    
  query:
    image: mylocalresistry.com/jaeger-query:1.20
    imagePullSecrets:
    - name: registre-images
    options:
      query:
        base-path: /
  collector:
    image: mylocalresistry.com/jaeger-collector:1.20
    imagePullSecrets:
    - name: registre-images
```

each images are taken from mylocalresistry.com succefully, except for the collector deployment.  It's seems that the imagePullSecret is never set, by the operator, in that specific deployement.

I've been able to workaround it by patching the collector deployment with this yaml file;

```yaml
spec:
  template:
    spec:
      imagePullSecrets:
      - name: registre-images
```

But I wonder if it's a bug or if custom repository are supported?
