### ISSUE TITLE
[Question] How to refer to standard ConfigMap or Secrets resources?

### ISSUE THREAD

**Issue by avoidik** [jaegertracing/jaeger-operator#1245]
Hello,

Could you please suggest a way on how to use configmap or secret values to configure jaeger-operator storage backend? Did I get it right, that per [Fine-Grained Configuration](https://www.jaegertracing.io/docs/1.20/operator/#finer-grained-configuration) both of these are not supported yet? Here is sample deployment, I would like to not expose password value here.

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        index-prefix: 'jaeger-op-'
        username: 'admin'
        password: 'sensitive'
```
