### ISSUE TITLE
Option to define an image prefix

### ISSUE THREAD

**Issue by johanneswuerbach** [jaegertracing/jaeger-operator#1265]
At my company we mirror all externally used images to our private registry. While you can already change the individual image names used by the jaeger components, it is currently rather tedious as you need to override each component image individually.

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: my-namspace
spec:
  strategy: production
  collector:
    image: internal-mirror/jaegertracing/jaeger-collector:1.19.2
  query:
    image: internal-mirror/jaegertracing/jaeger-query:1.19.2
...
```

Instead we would prefer to set a shared image prefix used by all images like:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: my-namspace
spec:
  strategy: production
  imagePrefix: internal-mirror/
...
```

If this would be contribution you would accept, I'll happily start working on it.
