### ISSUE TITLE
OTel agent/collector failing with duplicate volume/volumeMount

### ISSUE THREAD

**Issue by dackroyd** [jaegertracing/jaeger-operator#1266]
Using the operator to deploy the OTel variants of the Jaeger agent/collector requires adjusting the `health_check` port, which is done by supplying `config`. Minimal example from a minikube deployment (reproduced after initially hitting the issue in a full kubernetes cluster):

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: production
  agent:
    image: jaegertracing/jaeger-opentelemetry-agent:latest
    strategy: DaemonSet
    config:
      extensions:
        health_check:
          port: 14271
  collector:
    image: jaegertracing/jaeger-opentelemetry-collector:latest
    config:
      extensions:
        health_check:
          port: 14269
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://jaeger-es-http:9200
```

With this configuration in place, the operator produces a _duplicate_ `volume` and `volumeMount` for the otel config, and thus fails reconciliation repeatedly:

```
time="2020-10-20T01:46:51Z" level=error msg="failed to apply the changes" error="Deployment.apps \"simplest-query\" is invalid: spec.template.spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/etc/jaeger/otel/\": must be unique" execution="2020-10-20 01:46:51.030423915 +0000 UTC" instance=simplest namespace=observability
time="2020-10-20T01:46:52Z" level=error msg="failed to apply the changes" error="Deployment.apps \"simplest-query\" is invalid: spec.template.spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/etc/jaeger/otel/\": must be unique" execution="2020-10-20 01:46:52.101401604 +0000 UTC" instance=simplest namespace=observability
time="2020-10-20T01:46:53Z" level=error msg="failed to apply the changes" error="Deployment.apps \"simplest-query\" is invalid: spec.template.spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/etc/jaeger/otel/\": must be unique" execution="2020-10-20 01:46:53.187396068 +0000 UTC" instance=simplest namespace=observability
time="2020-10-20T01:46:54Z" level=error msg="failed to apply the changes" error="Deployment.apps \"simplest-query\" is invalid: spec.template.spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/etc/jaeger/otel/\": must be unique" execution="2020-10-20 01:46:54.272854654 +0000 UTC" instance=simplest namespace=observability
time="2020-10-20T01:46:55Z" level=error msg="failed to apply the changes" error="Deployment.apps \"simplest-query\" is invalid: spec.template.spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/etc/jaeger/otel/\": must be unique" execution="2020-10-20 01:46:55.359538151 +0000 UTC" instance=simplest namespace=observability
```

This appears to be as a result of a few factors:

* The operator state has the agent config saved back into it from previous runs
* The operator state is merged together including the config `volume`/`volumeMount` to prepare the agent
* `otelconfig.ShouldCreate` returns `true` when 'agent options' are empty, but 'agent config' is not empty, triggering `otelconfig.Update`, which adds the duplicate `volume`/`volumeMount` (first time through I assume this was fine, because the operator state didn't also have it?)
* Any de-duplication of volumes/volumeMounts occurs _before_ the OTel config is handled (during merge/CA handling)

Operator state:

`kubectl -n observability get jaegers.jaegertracing.io -oyaml`

```
...
  spec:
    agent:
      image: jaegertracing/jaeger-opentelemetry-agent:latest
      options: {}
      resources: {}
      strategy: DaemonSet
      volumeMounts:
      - mountPath: /etc/jaeger/otel/
        name: simplest-agent-otel-config
        readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config
            path: config.yaml
          name: simplest-agent-otel-config
        name: simplest-agent-otel-config
...
```
