### ISSUE TITLE
Unable to configure Kibana visualization with Jaeger CR (production strategy) using ElasticSearch as persistence

### ISSUE THREAD

**Issue by Abu0108** [jaegertracing/jaeger-operator#1283]
Latest ElasticSearch operator supports Kibana visualization also, no placeholder to configure currently. Examples or steps needed.

**Environment:** OCP 4.5

**Expected behavior**: Kibana instance created successfully and connected to Elastic instance and traces visible in KIBANA UI

NO configuration available to pass kibana parameters in Jaeger CR Instance.

```
# This CR deploys Jaeger and Elasticsearch
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 1Gi
```
