### ISSUE TITLE
jaeger-operator 1.19.0 custom serviceaccount 

### ISSUE THREAD

**Issue by eladhar** [jaegertracing/jaeger-operator#1289]
I have jaeger operator, version 1.19.0, running on a k8s cluster. I'm trying to use a custom serviceaccount for in the jaeger kind, in order to pull images from private repository.
It look like this:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  strategy: production
  serviceAccount: my-jaeger
  ingress:
    enabled: false
  agent:
    image: " mylocalresistry.com/jaegertracing/jaeger-agent:1.19.2"
  collector:
    image: " mylocalresistry.com/jaegertracing/jaeger-collector:1.19.2"
  query:
    image: " mylocalresistry.com/jaegertracing/jaeger-query:1.19.2"
    options:
      query:
        base-path: "/jaeger"
  storage:
    serviceAccount: my-jaeger
    type: elasticsearch
    options:
      es:
        server-urls: http://my-elasticsearch:9200
        index-prefix: jaeger-operator-elad
    dependencies:
      image: "artifactory.rnd-hub.com:6543/3rdparties/jaegertracing/spark-dependencies:latest"
      enabled: false
    esIndexCleaner:
      image: "artifactory.rnd-hub.com:6543/3rdparties/jaegertracing/jaeger-es-index-cleaner:1.19.2"
      enabled: false
    esRollover:
      image: "artifactory.rnd-hub.com:6543/3rdparties/jaegertracing/jaeger-es-rollover:1.19.2"
      enabled: false
```

Here is my custom serviceaccount creation (which is deployed before the kind Jaeger above):

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-jaeger
  labels:
    app.kubernetes.io/name: my-jaeger
    app.kubernetes.io/instance: my-jaeger
imagePullSecrets:
- name: my-secret
```

The problem is that the jaeger collector and query pods are not been created.

here are the errors from the jaeger-operator pod:
`
jaeger-operator-74979766c5-wwxj8 jaeger-operator time="2020-11-03T15:07:14Z" level=error msg="failed to apply the changes" error="serviceaccounts \"my-jaeger\" already exists" execution="2020-11-03 15:07:14.947162148 +0000 UTC" instance=my-jaeger namespace=jaeger-test
jaeger-operator-74979766c5-wwxj8 jaeger-operator time="2020-11-03T15:07:16Z" level=error msg="failed to store the failed status into the current CustomResource after the reconciliation" error="jaegers.jaegertracing.io \"my-jaeger\" not found" execution="2020-11-03 15:07:15.976150378 +0000 UTC" instance=my-jaeger namespace=jaeger-test
`
