### ISSUE TITLE
Sampling Strategies settings not updating in Collector without pod restart

### ISSUE THREAD

**Issue by js8080** [jaegertracing/jaeger-operator#1324]
I am deploying Jaeger via the Operator using the following Jaeger CR with sampling options shown below:

```yaml
# https://www.jaegertracing.io/docs/1.21/operator/#external-elasticsearch
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: monitoring
spec:
  strategy: production
  ingress:
    enabled: true
    hosts:
      - jaeger-query.monitoring-container-dev
  sampling:
    options:
      service_strategies:
      - service: samplewebapplication
        type: probabilistic
        param: 0.5
      default_strategy:
        type: probabilistic
        param: 0.5
        operation_strategies:
        - operation: "/health"
          type: probabilistic
          param: 0
        - operation: "/metrics"
          type: probabilistic
          param: 0
        - operation: "/healthz"
          type: probabilistic
          param: 0
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://tracing-es-http.monitoring.svc:9200
        index-prefix: monitoring
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret  # Secret which defines environment variables ES_PASSWORD and ES_USERNAME. Created by: kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=changeme --from-literal=ES_USERNAME=elastic
    esIndexCleaner:
      enabled: true            # turn the cron job deployment on and off
      numberOfDays: 7          # number of days to wait before deleting a record
      schedule: "55 23 * * *"  # cron expression for it to run
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: tracing-es-http-certs-public
```

My Jaeger Agent then picks up the sampling strategies and I can confirm the sampling strategies are being read correctly by hitting the Agent's sampling strategy service via an HTTP GET to `http://localhost:5778/sampling?service=samplewebapplication`:

```json
{
    "strategyType": "PROBABILISTIC",
    "probabilisticSampling": {"samplingRate": 0.5},
    "operationSampling": {
        "defaultSamplingProbability": 0.5,
        "defaultLowerBoundTracesPerSecond": 0,
        "perOperationStrategies": [
            {
                "operation": "/health",
                "probabilisticSampling": {"samplingRate": 0}
            },
            {
                "operation": "/metrics",
                "probabilisticSampling": {"samplingRate": 0}
            },
            {
                "operation": "/healthz",
                "probabilisticSampling": {"samplingRate": 0}
            }
        ],
        "defaultUpperBoundTracesPerSecond": 0
    }
}
```

However, if I update the Jaeger CR spec to add or remove one of my sampling strategy settings, the Collector and/or Agent don't seem to pick up the new settings until I restart the Collector pod (I've done so via `kubectl delete pod simple-prod-collector-asdf` for example).

Is this expected or am I just not being patient enough for some refresh time interval to expire and the Collector re-reads the sampling strategy settings?

**Comment by jpkrohling** [comment]
> Is this expected or am I just not being patient enough for some refresh time interval to expire and the Collector re-reads the sampling strategy settings?

There are a couple of things that might be needed:

- [ ] check that the collector will reload the strategies file when it's changed. I remember seeing a PR bringing this to the collector, just not sure if it's already there.
- [ ] check that the config map gets updated with the changed configuration
- [ ] check that the file mounted in the container based on the config map has changed

Those three pieces need to be working for the reload to happen. If you are able to confirm that, it would speed up a resolution/implementation of this. Otherwise, I can check it myself in a couple of weeks.

**Comment by js8080** [comment]
I just tested to check some of those things:
* [x]  check that the config map gets updated with the changed configuration - The config map is indeed updated when I `kubectl apply` an updated Jaeger CR spec
* [x]  check that the file mounted in the container based on the config map has changed - The file associated with the config map (`/etc/jaeger/sampling/sampling.json`) is indeed updated when I `kubectl apply` an updated Jaeger CR spec

Also, my version info for my Jaeger CR (via `kubectl describe jaeger simple-prod`):
```yaml
Status:
  Phase:    Running
  Version:  1.21.0
```

**Comment by jpkrohling** [comment]
I found the PR I was thinking about: https://github.com/jaegertracing/jaeger/pull/2188 . Looks like, a flag is needed in order to reload the config file: `--strategies-reload-interval`. You should be able to set this in the CR, under the `collector`'s options.

**Comment by js8080** [comment]
> a flag is needed in order to reload the config file: `--strategies-reload-interval`. You should be able to set this in the CR, under the `collector`'s options.

Any idea of the syntax on that? The reference for the CR options is scant. My guess (probably not accurate and not sure how to confirm):
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: monitoring
spec:
  strategy: production
  ingress:
    enabled: true
    hosts:
      - jaeger-query.monitoring-container-dev
  collector:
    options:
      strategies_reload_interval: 50ms
```

**Comment by js8080** [comment]
I figured it out through some trial and error:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: monitoring
spec:
  strategy: production
  ingress:
    enabled: true
    hosts:
      - jaeger-query.monitoring-container-dev
  collector:
    options:
      sampling:
        strategies-reload-interval: 30s
```
