### ISSUE TITLE
Volume mounts not working for Spark dependencies job

### ISSUE THREAD

**Issue by milon619** [jaegertracing/jaeger-operator#1332]
I am trying to pass a java trustStore file which contains the ES root ca cert to the Spark dependencies job to get the connection to ES work over TLS, but it looks like the volumes are not getting mounted and the job fails with the following error.

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Cannot initialize SSL - Expected to find keystore file at [file:/es-tls/trust.store] but was unable to. Make sure that it is available on the classpath, or if not, that 
you have specified a valid URI.
```

My dependencies config snippet in the Jaeger custom resource
 ```
dependencies:
      enabled: true
      javaOpts: -Djavax.net.ssl.trustStore=/es-tls/trust.store -Djavax.net.ssl.trustStorePassword='<pass>'
      resources:
        limits:
          memory: 4096Mi
        requests:
          memory: 2048Mi
      schedule: 16 05 * * *
      sparkMaster: ""
      volumeMounts:
      - mountPath: /es-tls
        name: es-tls
        readOnly: true
        subPath: ""
      volumes:
      - configMap:
          name: es-tls
        name: es-tls
```

This is what the job looks like when I describe the job and the volumemount is missing there
```
$ oc describe job jaeger-kafka-spark-dependencies-1607318160
Name:           jaeger-kafka-spark-dependencies-1607318160
Namespace:      tracing
Selector:       controller-uid=dcc93485-9db4-4251-954b-b842e98a0774
Labels:         app=jaeger
                app.kubernetes.io/component=spark-dependencies
                app.kubernetes.io/instance=jaeger-kafka
                app.kubernetes.io/managed-by=jaeger-operator
                app.kubernetes.io/name=jaeger-kafka-spark-dependencies
                app.kubernetes.io/part-of=jaeger
                controller-uid=dcc93485-9db4-4251-954b-b842e98a0774
                job-name=jaeger-kafka-spark-dependencies-1607318160
Annotations:    <none>
Controlled By:  CronJob/jaeger-kafka-spark-dependencies
Parallelism:    1
Completions:    <unset>
Start Time:     Mon, 07 Dec 2020 06:16:03 +0100Pods Statuses:  1 Running / 0 Succeeded / 3 Failed
Pod Template:
  Labels:           app=jaeger
                    app.kubernetes.io/component=spark-dependencies
                    app.kubernetes.io/instance=jaeger-kafka
                    app.kubernetes.io/managed-by=jaeger-operator
                    app.kubernetes.io/name=jaeger-kafka-spark-dependencies
                    app.kubernetes.io/part-of=jaeger
                    controller-uid=dcc93485-9db4-4251-954b-b842e98a0774
                    job-name=jaeger-kafka-spark-dependencies-1607318160
  Annotations:      linkerd.io/inject: disabled
                    prometheus.io/scrape: false
                    sidecar.istio.io/inject: false
  Service Account:  jaeger-kafka
  Containers:
   jaeger-kafka-spark-dependencies:
    Image:      jaegertracing/spark-dependencies
    Port:       <none>
    Host Port:  <none>
    Limits:
      memory:  4Gi
    Requests:
      memory:  2Gi
    Environment Variables from:
      jaeger-es-cred  Secret  Optional: false
    Environment:
      STORAGE:    elasticsearch
      JAVA_OPTS:  -Djavax.net.ssl.trustStore=/es-tls/trust.store -Djavax.net.ssl.trustStorePassword='<pass>'
      ES_NODES:   https://logging-es-http.logging.svc:9200
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  73s   job-controller  Created pod: jaeger-kafka-spark-dependencies-1607318160-bvjh7
  Normal  SuccessfulCreate  65s   job-controller  Created pod: jaeger-kafka-spark-dependencies-1607318160-ln46g
  Normal  SuccessfulCreate  55s   job-controller  Created pod: jaeger-kafka-spark-dependencies-1607318160-djsjl
  Normal  SuccessfulCreate  34s   job-controller  Created pod: jaeger-kafka-spark-dependencies-1607318160-sz2x2
```
I followed this approach after referring to - 
https://github.com/jaegertracing/jaeger-operator/issues/294#issuecomment-616642204
