### ISSUE TITLE
jaegeroperator to support nodeSelector

### ISSUE THREAD

**Issue by omerfsen** [jaegertracing/jaeger-operator#1351]
On CRD kind Jaeger

```yaml
kind: Jaeger
```

when we enter `nodeSelector:` to some specific components it is not applied. For example:

```yaml
  collector:
    config: {}
    nodeSelector:
      agentpool: service
```

so we request this to be supported so created components (collector/ingester/query) to support nodeSelector.
