### ISSUE TITLE
no jaeger-query service visible in UI when in production mode with external elasticsearch storage

### ISSUE THREAD

**Issue by hkailantzis** [jaegertracing/jaeger-operator#1390]
Hi there,

deployed Jaeger instance v1.21.0 using Jaeger Operator using an external elasticsearch cluster on kubernetes cluster. 
Everything looks fine from logs and ES indices point of view and i can see the span write index growing over time. no errors or whatsoever. collector and query pods also running fine.

I have set ```use-aliases: true``` for collector and query components. However, the only problem that I have is that I don't see the jaeger-query service in the list of services for the UI, so wondering what could be the problem or verify that everything works as expected. Is this normal behaviour ? Because, with memory storage and all-in-one installation I can see the jaeger-query in the list of services on the UI.

logs from collector below:

```2021/02/12 15:05:39 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1613142339.5422573,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1613142339.5422943,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1613142339.5429192,"caller":"flags/admin.go:121","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1613142339.542986,"caller":"flags/admin.go:127","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1613142339.543018,"caller":"flags/admin.go:113","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1613142339.780908,"caller":"config/config.go:179","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1613142339.7914138,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1613142339.7915013,"caller":"server/http.go:44","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
{"level":"info","ts":1613142339.7921262,"caller":"server/zipkin.go:49","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"}
{"level":"info","ts":1613142339.820321,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
```

Please let me know if you require any further info. Thank you!

**Comment by jpkrohling** [comment]
Could you please provide the minimal CR that is able to reproduce this problem? Also, you might want to check the metrics on the collector side, especially the "saved by service". It should show you how many spans/traces were saved for `jaeger-query`.

**Comment by hkailantzis** [comment]
hi @jpkrohling, thanks for your reply.  Please find below the spec part (with <> placeholders for relevant values):

```
spec:
    strategy: production
    collector:
      maxReplicas: 3
      options:
        es:
          use-aliases: true
    query:
      options:
        es:
          use-aliases: true
    storage:
      type: elasticsearch
      options:
        es:
          server-urls: <server-url-to-external-elasticsearch>
          username: <elasticsearch-username>
          index-prefix: "stable"
          create-index-templates: false
      secretName: <elastic-secret-name>
      esIndexCleaner:
        enabled: false
      dependencies:
        enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - <jaeger-hostname.com>
```
