### ISSUE TITLE
Jaeger ingress fails to allocate address

### ISSUE THREAD

**Issue by ivanayov** [jaegertracing/jaeger-operator#1393]
Hello,

I'm deploying jaeger, following the [openetelemtry docs (otel-collector example)](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector) and deploy the jaeger crd as shown [here](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/otel-collector/Makefile#L4), with the only difference that I'm using `kind`.

The ingress controller that was created doesn't allocate address:
```
$ kubectl get ingress --all-namespaces
NAMESPACE       NAME           CLASS    HOSTS       ADDRESS   PORTS   AGE
observability   jaeger-query   <none>   localhost             80      4h42m
```

This is why I tried to deploy Jaeger with ingress disabled afterward:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  ingress:
    enabled: false
```
and deploy my own controller:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jaeger-query
  namespace: observability
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: jaeger-query
          servicePort: 80
```
But the result was the same.
```
$ kubectl get ingress --all-namespaces
NAMESPACE       NAME           CLASS    HOSTS       ADDRESS   PORTS   AGE
observability   jaeger-query   <none>   localhost             80      4h42m
```

`localhost` is available in `/etc/hosts`:
```
$ kubectl exec jaeger-6678879fd4-b59k9 -n observability -- cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
```
And this is my cluster:
```
$ kubectl cluster-info --context kind-kind
Kubernetes master is running at https://127.0.0.1:54338
KubeDNS is running at https://127.0.0.1:54338/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
Can this be an issue with the Jaeger deployment on kind?

With kind you don't need to enable ingress and it's pretty simple to create a controller (as shown [here](https://kind.sigs.k8s.io/docs/user/ingress/)). Usually it works ok for localhost.

**Comment by jpkrohling** [comment]
I'm not familiar with ingresses with kind, but it does look strange. Would you be able to test on minikube with an ingress add-on? If it works there, it might be something that we are missing in order to make kind happy. If you can figure out what exactly it is, feel free to open a PR.

In any case, I'll mark this as a bug but might take a while for me to take a look.

**Comment by jpkrohling** [comment]
@rubenvp8510, could you take a look at this one?

**Comment by ivanayov** [comment]
@jpkrohling I don't reproduce the issue with `minikube` (tested with `hyperkit` only, because of an unresolved issue for docker on Mac).

It's reproduced with kind only. The issue with ingress address not being allocated is resolved, but jaeger is still unaccessible from outside.
It's hard to investigate the jaeger-operator container, as ssh-ing as root does not give enough privilleges though.

**Comment by rubenvp8510** [comment]
I tested with `Kind` I was not able  reproduce the issue so far, this is how my ingress looks like:

```
NAME              CLASS    HOSTS   ADDRESS     PORTS   AGE
my-jaeger-query   <none>   *       localhost   80      13m

```
Also I can reach jaeger outside the cluster. I did  a ` curl localhost` and I got a response. I followed the instructions [here](https://kind.sigs.k8s.io/docs/user/ingress/) I installed NGINX controller. Which ingress controller are you using? What version of `Kind`? This sounds more like a bug in the controller or Kind more than an operator issue.

**Comment by ivanayov** [comment]
Thank you @rubenvp8510. Can you please share how you deployed jaeger? Did you use helm or the crds from the repo? Thanks.

**Comment by rubenvp8510** [comment]
Hi @ivanayov I did it using CRDs from the repo. 

This is my Kind configuration:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
I started Kind and installed the ingress controller: 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=190s
```
Installed the operator:
kubectl create namespace observability
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml

Then I deployed a simple jaeger all-in-one CR:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  strategy: allinone
  ingress:
    enabled: true
```
