### ISSUE TITLE
Auto-injecting Jaeger Agent Sidecars not working on minikube

### ISSUE THREAD

**Issue by MKruger777** [jaegertracing/jaeger-operator#1405]
Hey there, 

I am trying to get the Jäger sidecar agent injection working, but cannot seem to get it to work properly.
I followed the steps outlined here: https://www.jaegertracing.io/docs/1.22/operator/

My setup is:
`Ubuntu 20.04`

VirtualBox (to run minikube)
`Version 5.2.20 r125813 (Qt5.12.8)`

minikube version:` v1.13.1`

kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9" 
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2"
```

I created a clean minikube (--cpus 3 --memory 6144) and install the Jaeger operator in the "observability" namespace using the commands from the instruction found here: https://www.jaegertracing.io/docs/1.22/operator/#installing-the-operator-on-kubernetes
```
kubectl create namespace observability # <1>
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml # <2>
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml
```
After this the operator was running perfectly in the observability namespace.

I then did a very simple deployment to test the Jaeger Agent Sidecars injection based on the instruction found here: https://www.jaegertracing.io/docs/1.22/operator/#auto-injecting-jaeger-agent-sidecars
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```

The deployment then starts up, but without the agent being injected (I see only 1/1 in nginx-deployment-585449566-xn587)
```
NAMESPACE       NAME                               READY   STATUS    RESTARTS   AGE
kube-system     coredns-f9fd979d6-cl26h            1/1     Running   0          18m
kube-system     etcd-jgithub                       1/1     Running   0          18m
kube-system     kube-apiserver-jgithub             1/1     Running   0          18m
kube-system     kube-controller-manager-jgithub    1/1     Running   0          18m
kube-system     kube-proxy-698zm                   1/1     Running   0          18m
kube-system     kube-scheduler-jgithub             1/1     Running   0          18m
kube-system     storage-provisioner                1/1     Running   2          18m
observability   jaeger-operator-64bc449b74-vvq9h   1/1     Running   0          16m
observability   nginx-deployment-585449566-xn587   1/1     Running   0          9m41s
```

I am probably messing something up here? I was expecting to see the injected Jaeger Agent Sidecars in my nginx-deployment-585449566-xn587 
Thanks in advance!
