### ISSUE TITLE
Operator doesn't respect priorityClassName for collector or query

### ISSUE THREAD

**Issue by majidazimi** [jaegertracing/jaeger-operator#1410]
Jaeger operator doesn't respect setting `priorityClassName` for collector and query:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  ingress:
    enabled: false
  collector:
    replicas: 1
    options:
      log-level: debug
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    priorityClassName: system-cluster-critical
  query:
    priorityClassName: system-cluster-critical
```

Setting above fields doesn't trigger any redeployment. Deleting `ReplicaSet` manually doesn't create pods with new configuration either. However, Collecotor/Query helm charts already supports this field. Am I missing something or there is really an issue?
