### ISSUE TITLE
support repetitive arguments to operand

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#1415]
For now, there is no way to supply repetitive arguments options to the operand

I am expecting the following arguments to query pod, how to specify this in jaeger CR?
```
--query.additional-headers=access-control-allow-origin:blerg
--query.additional-headers=whatever:thing
```

```yaml
spec:
  query:
    options:
      query:
         additional-headers: "whatever:thing"
```

AFAIK, in YAML we cannot supply the same key multiple times
https://github.com/jaegertracing/jaeger-operator/blob/v1.21.3/pkg/apis/jaegertracing/v1/options.go#L96~L99
