### ISSUE TITLE
Support passing Kafka username/password as K8S secrets

### ISSUE THREAD

**Issue by tonychoe** [jaegertracing/jaeger-operator#1422]
**Problem to Solve** 

I am using the existing Kafka for the `streaming` strategy. Looks like there's no option to pass the Kafka username/password as K8S secret to jaeger-collector and ingester. It would be good to support it.

**Proposed Solution** 
Passing the Kafka username/password as a K8S secret.

**More info**
This is my current config in Jsonnet. It passed the username/password as the container args which lacks protection.

```jsonnet
    topic: "jaeger-spans",
    brokers: "cell-1.streaming.us-phoenix-1.oci.oraclecloud.com:9092",
    authentication: "plaintext",
    plaintext: {
      username: $.streaming_username,
      password: $.streaming_password,
    },
    "protocol-version": "2.1.1",
    tls: {
      enabled: true,
    },
```

Before trying Jaeger Operator, I used to handle them as env vars.
```yaml
        env:
          - name: KAFKA_CONSUMER_PLAINTEXT_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: jaegerkafkaauth
          - name: KAFKA_CONSUMER_PLAINTEXT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: jaegerkafkaauth
```
