### ISSUE TITLE
jaeger not listening on zipkin port

### ISSUE THREAD

**Issue by Shohou** [jaegertracing/jaeger-operator#1425]
I'm creating Jaeger all-in-one instance according to the following config:
```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger-aio"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.22
    options:
      log-level: trace
      query:
        base-path: /jaeger
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  storage:
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
```

I see how it creates a pod and in pod describe I can see environment variable set - `COLLECTOR_ZIPKIN_HTTP_PORT:  9411`
But for some reason when I check logs I see
```
{"level":"info","ts":1617923155.6444147,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"}
```

Anything else I should add to configuration to enable zipkin port?

Jaeger operator image - `jaegertracing/jaeger-operator:1.21.2`
