### ISSUE TITLE
Incorrect Jaeger Custom Resource Version

### ISSUE THREAD

**Issue by ethernoy** [jaegertracing/jaeger-operator#1426]
Hi all,

I deployed jaeger 1.22.0 using jaeger operator 1.22.0 and it works as expected. However, when I view the CR I deployed, it has the status version = 1.21.0.

![image](https://user-images.githubusercontent.com/15870761/114124937-0fef1380-9928-11eb-8927-e4af6eb765c4.png)

Here is the CR I used when deploying jaeger:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  serviceAccount: jaeger-sa
  strategy: production
  resources:
    requests:
      cpu: "750m"
      memory: "256Mi"
    limits:
      cpu: "1500m"
      memory: "512Mi"
  agent:
    image: {{ .Values.jaeger.image.repository }}/jaeger-agent:1.22.0
    imagePullSecrets:
    - name: platform-tool-docker-repo
    podSecurityContext:
      runAsUser: 1000
    securityContext:
      runAsUser: 1000
  # ingester:
  #   image: {{ .Values.jaeger.image.repository }}/jaeger-ingester:1.22.0
  #   podSecurityContext:
  #     runAsUser: 1000
  #   securityContext:
  #     runAsUser: 1000
  query:
    image: {{ .Values.jaeger.image.repository }}/jaeger-query:1.22.0
    podSecurityContext:
      runAsUser: 1000
    securityContext:
      runAsUser: 1000
  collector:
    image: {{ .Values.jaeger.image.repository }}/jaeger-collector:1.22.0
    podSecurityContext:
      runAsUser: 1000
    securityContext:
      runAsUser: 1000
    options:
      collector.zipkin.host-port: ":9411"
  storage:
    type: cassandra
    dependencies:
      enabled: false
    options:
      cassandra:
        servers: jaeger-cassandra.observability.svc
        keyspace: jaeger_v1_datacenter
    secretName: jaeger-cassandra-sec
    cassandraCreateSchema:
      enabled: false
```
