### ISSUE TITLE
Provision a Service for Jaeger agent daemonset

### ISSUE THREAD

**Issue by tonychoe** [jaegertracing/jaeger-operator#1427]
**Problem to fix**
Spans are not received after jaeger-agent-daemonset restarts.

**Desired Solution**
Jaeger Operator provides an option to provision a Service for jaeger-agent-daemonset

**Details**
The instrumented apps are configured with
```yaml
       env:
       - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
After the agent restarts, the agent don't get spans from the instrumented apps. This issue is related to the conntrack which is the Linux kernel module that tracks connections and explained in https://github.com/jaegertracing/jaeger-client-go/issues/393#issuecomment-562416992. 

The only short-term fixes were either deleting the conntrack entries for the agent by `conntrack -D -p udp --orig-port-dst 6831` in each Kubernetes node or restart all instrumented app pods. Both are tedious and not desirable. 

If the Operator provides an option to deploy a Service for the agent, users can avoid this issue with this setting
```yaml
       env: 
       - name: JAEGER_AGENT_HOST
          value: jaeger-agent-daemonset.jaeger
```
I understand why it is optimal to use `status.hostIP` but unless I can prevent this issue, I'd like to use the Service.

**Why not reduce the timeout value for conntrack?**
Users may reduce the value of `net.netfilter.nf_conntrack_udp_timeout` (default 30 sec) by [sysctl in a Kubernetes cluster](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/). However, in the busy cluster where many apps send spans every few ms, I don't know what is the right value.

**Why not disable conntrack?**
I'd rather not. I don't know the impact.

**Any other alternative?**
Jaeger Operator may provision the init container that deletes the entries tracking the agent's connections.
```
# Init-container which will run on pod startup
initContainers:
- name: sysctl
  image: docker.io/busybox:1.33
  imagePullPolicy: ifNotPresent
  command:
  - sh
  - -c
  - conntrack -D -p udp --orig-port-dst 6831
  securityContext:
    privileged: true
```
