### ISSUE TITLE
Enabling external labels for Jaeger pods

### ISSUE THREAD

**Issue by munipravy** [jaegertracing/jaeger-operator#1429]
For enabling pod level labeling in Jaeger do we have spec recommended way  ?

**Comment by jpkrohling** [comment]
The labels you specify as part of the Jaeger CR should be propagated down to the underlying resources, including pods.

**Comment by munipravy** [comment]
I am using spec.metadata.labels to mention labels at pod level as mentioned below.

```
apiVersion: {{ .Values.apiVersion.Jaeger}}
kind: Jaeger
metadata:
  name: jaeger-cluster
spec:
  metadata:
    labels:
      foo: bar
  strategy: production
```
But labels are not reflecting at Jaeger pod level

**Comment by jpkrohling** [comment]
@rubenvp8510 , could you please take a look?

**Comment by esnible** [comment]
@munipravy should it be

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-cluster
spec:
    labels:
      foo: bar
  strategy: production
```

I don't think we have a spec.metadata.labels.

```
kubectl explain jaeger.spec.labels
...
FIELD:    labels <map[string]string>
...

kubectl explain jaeger.spec.metadata.labels

error: field "metadata" does not exist
```
