### ISSUE TITLE
Migration to 1.22 missed Zipkin port change

### ISSUE THREAD

**Issue by gsagula** [jaegertracing/jaeger-operator#1441]
**Describe the bug**
Starting on `jaegertracing/jaeger-operator:1.22.1`, jaeger-collector does not start Zipkin server automatically.

{"level":"info","ts":1619421380.7131286,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"}

CR
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: mon-jaeger
  namespace: observability
spec:
  log-level: debug
  strategy: streaming
  sampling:
    options:
      default_strategy:
        type: const
        param: 100 
  collector:
    options:
      kafka: 
        producer:
          topic: jaeger-spans
          brokers: knative-kafka-cluster.knative-kafka:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: knative-kafka-cluster.knative-kafka:9092
      ingester:
        deadlockInterval: 0s
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-es-http:9200
        index-prefix: jaeger-tracing
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elastic-es-http-certs-public
```

**Discussion**
https://github.com/jaegertracing/jaeger/discussions/2959

**To Reproduce**
1. Install operator `jaegertracing/jaeger-operator:1.22.1` with  `log-level: debug`
2. Fire a valid CR to deploy Jaeger.
3. Grab the collector's logs

You should see the message `"Not listening for Zipkin HTTP traffic, port not configured"` and Jaeger does not take any Zipking trace.

**Expected behavior**
Collector should start Zipkin server automatically.

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jaeger version: 1.22.1
 - Deployment: Kubernetes - 1.18.16-gke.502

**What troubleshooting steps did you try?**
The same CR works with the previous version `jaegertracing/jaeger-operator:1.21.3`.
```
{"level":"info","ts":1619449101.7558992,"caller":"server/zipkin.go:49","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"} 
```

cc @jpkrohling
