### ISSUE TITLE
Jaeger Rollover Elastic Search - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Dweston88** [jaegertracing/jaeger-operator#1464]
**Describe the bug**
When deploying the jaeger production operator using elastic search "use-aliases" the kubernetes pod for roll over initialization fails with SSL Certificate verification failure even though the certificate is valid and set. Configuration listed below.

**To Reproduce**
1. kubectl apply -f ./jaeger-prod.yaml -n observability
2. kubectl get pods -n observability
3. kubectl logs <rollover-pod> -n observability > output.txt
4. Review output.txt and the logs show SSL certificate verify errors

**Expected behavior**
Rollover job is successful, indexes are created, and jaeger starts up successfully

**Version (please complete the following information):**
 - OS: Ubuntu
 - Jaeger version: Latest
 - Deployment: Kubernetes
 - Cloud: Azure AKS 1.19

**What troubleshooting steps did you try?**
I have tried using different certificates, server names, setting the TLS settings directly on the cron jobs.

**Additional context**
NAME                                                                       READY  STATUS    RESTARTS   AGE
jaeger-operator-6954c97677-nc2jk                       1/1       Running          0             19h
jaeger-prod-es-rollover-create-mapping-9fk6q   0/1       Error                1              3s

Output Logs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

Jaeger Config
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
  namespace: observability
spec:
  strategy: production
  query:
    options:
      es:
        use-aliases: true
      query:
        base-path: /jaeger
  storage:
    type: elasticsearch
    options:
      log-level: debug
      es:
        server-urls: https://elasticsearch_url/elastic
        index-prefix: jaeger-
        use-aliases: true
        tls:
          enabled: yes
          ca: "/tls/es.crt"
    esIndexCleaner:
        enabled: true
        numberOfDays: 7
        schedule: "55 23 * * *"
    esRollover:
      conditions: "{\"max_age\": \"2d\"}"
      readTTL: 168h
      schedule: "55 23 * * *" 
  collector:
    log-level: debug
    options:
      es:
        use-aliases: true
    maxReplicas: 5
    zipkin:
      host-port: "9411"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    ingress:
      enabled: false
  volumeMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      configMap: jaeger-tls
      readOnly: true
  volumes:
    - name: jaeger-tls
      configMap:
        name: jaeger-tls
```

**Comment by Dweston88** [comment]
`apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
  namespace: observability
spec:
  strategy: production
  query:
    options:
      es:
        use-aliases: true
      query:
        base-path: /jaeger
  storage:
    type: elasticsearch
    options:
      log-level: debug
      es:
        server-urls: https://amer-kong-dev-manager.pwcinternal.com/elastic
        index-prefix: jaeger-
        use-aliases: true
        tls:
          enabled: yes
          ca: "/tls/es.crt"
    esIndexCleaner:
        enabled: true
        numberOfDays: 7
        schedule: "55 23 * * *"
    esRollover:
      conditions: "{\"max_age\": \"2d\"}"
      readTTL: 168h
      schedule: "55 23 * * *" 
  collector:
    log-level: debug
    options:
      es:
        use-aliases: true
    maxReplicas: 5
    zipkin:
      host-port: "9411"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    ingress:
      enabled: false
  volumeMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      configMap: jaeger-tls
      readOnly: true
  volumes:
    - name: jaeger-tls
      configMap:
        name: jaeger-tls
`

**Comment by Dweston88** [comment]
@rubenvp8510 Any update on this? I am not able to continue with deployment.

**Comment by rubenvp8510** [comment]
Hi, sorry I haven't had time to give it a try. I'll try to reproduce it tomorrow.

**Comment by rubenvp8510** [comment]
Hi @Dweston88   how do you deploy your elasticsearch? Is your certificate self-signed ?

Could you provide me some steps on how do you deploy your ES and how are you creating your certificates?

Thanks.

**Comment by Dweston88** [comment]
This is what I used for deploying elastic search HELM chart using AKS Internal load balancer. This is not a self-signed, I used a purchased SSL certificate. Also have a Nginx ingress sitting in front of elastic and jaeger to offload HTTPs.

```

#!/bin/bash
set -e

export ACTION="INSTALL"
export NAMESPACE="elastic"
export CLUSTER_NAME="my-k8s-cluster"
export KUBECONFIG=$KUBECONFIG:$CLUSTER_NAME

kubectl config use-context $CLUSTER_NAME --insecure-skip-tls-verify=true

kubectl get namespaces --insecure-skip-tls-verify=true  

kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f - --insecure-skip-tls-verify=true

helm repo add elastic https://helm.elastic.co

helm upgrade --install elasticsearch elastic/elasticsearch -f ./elastic-values.yaml -n $NAMESPACE --wait --insecure-skip-tls-verify=true

```

SSL Config Map
```

kubectl create configmap jaeger-tls --from-file=es.crt -n observability

```

Elasticsearch HELM values override.
```
---
clusterName: "elasticsearch"
nodeGroup: "master"

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: ""

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"
  ml: "true"

replicas: 3
minimumMasterNodes: 2

esMajorVersion: ""

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig: {}
#  elasticsearch.yml: |
#    key:
#      nestedkey: value
#  log4j2.properties: |
#    key = value

# Extra environment variables to append to this nodeGroup
# This will be appended to the current 'env:' key. You can use any of the kubernetes env
# syntax here
extraEnvs: []
#  - name: MY_ENVIRONMENT_VAR
#    value: the_value_goes_here

# Allows you to load environment variables from kubernetes secret or config map
envFrom: []
# - secretRef:
#     name: env-secret
# - configMapRef:
#     name: config-map

# A list of secrets and their paths to mount inside the pod
# This is useful for mounting certificates for security and for mounting
# the X-Pack license
secretMounts: []
#  - name: elastic-certificates
#    secretName: elastic-certificates
#    path: /usr/share/elasticsearch/config/certs
#    defaultMode: 0755

hostAliases: []
#- ip: "127.0.0.1"
#  hostnames:
#  - "foo.local"
#  - "bar.local"

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.13.0"
imagePullPolicy: "IfNotPresent"

podAnnotations: {}
  # iam.amazonaws.com/role: es-cluster

# additionals labels
labels: {}

esJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

initResources: {}
  # limits:
  #   cpu: "25m"
  #   # memory: "128Mi"
  # requests:
  #   cpu: "25m"
  #   memory: "128Mi"

sidecarResources: {}
  # limits:
  #   cpu: "25m"
  #   # memory: "128Mi"
  # requests:
  #   cpu: "25m"
  #   memory: "128Mi"

networkHost: "0.0.0.0"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi

rbac:
  create: false
  serviceAccountAnnotations: {}
  serviceAccountName: ""

podSecurityPolicy:
  create: false
  name: ""
  spec:
    privileged: true
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
      - secret
      - configMap
      - persistentVolumeClaim
      - emptyDir

persistence:
  enabled: true
  labels:
    # Add default labels for the volumeClaimTemplate of the StatefulSet
    enabled: false
  annotations: {}

extraVolumes: []
  # - name: extras
  #   emptyDir: {}

extraVolumeMounts: []
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true

extraContainers: []
  # - name: do-something
  #   image: busybox
  #   command: ['do', 'something']

extraInitContainers: []
  # - name: do-something
  #   image: busybox
  #   command: ['do', 'something']

# This is the PriorityClass settings as defined in
# https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: ""

# By default this will make sure two pods don't end up on the same node
# Changing this to a region would allow you to spread pods across regions
antiAffinityTopologyKey: "kubernetes.io/hostname"

# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "hard"

# This is the node affinity settings as defined in
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: {}

# The default is to deploy all pods serially. By setting this to parallel all pods are started at
# the same time when bootstrapping the cluster
podManagementPolicy: "Parallel"

# The environment variables injected by service links are not used, but can lead to slow Elasticsearch boot times when
# there are many services in the current namespace.
# If you experience slow pod startups you probably want to set this to `false`.
enableServiceLinks: true

protocol: http
httpPort: 9200
transportPort: 9300

service:
  labels: {}
  labelsHeadless: {}
  type: LoadBalancer
  nodePort: ""
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  httpPortName: http
  transportPortName: transport
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""

updateStrategy: RollingUpdate

# This is the max unavailable setting for the pod disruption budget
# The default value of 1 will make sure that kubernetes won't allow more than 1
# of your pods to be unavailable during maintenance
maxUnavailable: 1

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# How long to wait for elasticsearch to stop gracefully
terminationGracePeriod: 120

sysctlVmMaxMapCount: 262144

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

# https://www.elastic.co/guide/en/elasticsearch/reference/7.13/cluster-health.html#request-params wait_for_status
clusterHealthCheckParams: "wait_for_status=green&timeout=1s"

## Use an alternate scheduler.
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""

imagePullSecrets: []
nodeSelector: {}
tolerations: []

# Enabling this will publically expose your Elasticsearch instance.
# Only enable this if you have security enabled on your cluster
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nameOverride: ""
fullnameOverride: ""

# https://github.com/elastic/helm-charts/issues/63
masterTerminationFix: false

lifecycle: {}
  # preStop:
  #   exec:
  #     command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
  # postStart:
  #   exec:
  #     command:
  #       - bash
  #       - -c
  #       - |
  #         #!/bin/bash
  #         # Add a template to adjust number of shards/replicas
  #         TEMPLATE_NAME=my_template
  #         INDEX_PATTERN="logstash-*"
  #         SHARD_COUNT=8
  #         REPLICA_COUNT=1
  #         ES_URL=http://localhost:9200
  #         while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
  #         curl -XPUT "$ES_URL/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'{"index_patterns":['\""$INDEX_PATTERN"\"'],"settings":{"number_of_shards":'$SHARD_COUNT',"number_of_replicas":'$REPLICA_COUNT'}}'

sysctlInitContainer:
  enabled: true

keystore: []

networkPolicy:
  ## Enable creation of NetworkPolicy resources. Only Ingress traffic is filtered for now.
  ## In order for a Pod to access Elasticsearch, it needs to have the following label:
  ## {{ template "uname" . }}-client: "true"
  ## Example for default configuration to access HTTP port:
  ## elasticsearch-master-http-client: "true"
  ## Example for default configuration to access transport port:
  ## elasticsearch-master-transport-client: "true"

  http:
    enabled: false
    ## if explicitNamespacesSelector is not set or set to {}, only client Pods being in the networkPolicy's namespace
    ## and matching all criteria can reach the DB.
    ## But sometimes, we want the Pods to be accessible to clients from other namespaces, in this case, we can use this
    ## parameter to select these namespaces
    ##
    # explicitNamespacesSelector:
    #   # Accept from namespaces with all those different rules (only from whitelisted Pods)
    #   matchLabels:
    #     role: frontend
    #   matchExpressions:
    #     - {key: role, operator: In, values: [frontend]}

    ## Additional NetworkPolicy Ingress "from" rules to set. Note that all rules are OR-ed.
    ##
    # additionalRules:
    #   - podSelector:
    #       matchLabels:
    #         role: frontend
    #   - podSelector:
    #       matchExpressions:
    #         - key: role
    #           operator: In
    #           values:
    #             - frontend

  transport:
    ## Note that all Elasticsearch Pods can talks to themselves using transport port even if enabled.
    enabled: false
    # explicitNamespacesSelector:
    #   matchLabels:
    #     role: frontend
    #   matchExpressions:
    #     - {key: role, operator: In, values: [frontend]}
    # additionalRules:
    #   - podSelector:
    #       matchLabels:
    #         role: frontend
    #   - podSelector:
    #       matchExpressions:
    #         - key: role
    #           operator: In
    #           values:
    #             - frontend

# Deprecated
# please use the above podSecurityContext.fsGroup instead
fsGroup: ""

```

**Comment by Dweston88** [comment]
Here is my ingress deployment

Deploy Nginx
```

export CLUSTER_NAME="my-k8s-cluster"

export KUBECONFIG=$KUBECONFIG:$CLUSTER_NAME

kubectl config use-context $CLUSTER_NAME --insecure-skip-tls-verify=true

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

helm install nginx-ingress ingress-nginx/ingress-nginx \
    --namespace nginx \
    -f internal-ingress.yaml \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux

sleep 15

kubectl apply -f ./nginx-ingress.yaml -n nginx

```

Internal Ingress Override File
```

controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

```

Elastic Search Ingress Config
kubectl apply -f ./nginx-ingress-elastic.yaml

```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-proxy
  namespace: elastic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Origin, X-Requested-With, Content-Type, Accept"
    nginx.ingress.kubernetes.io/cors-allow-methods: "DELETE, GET, POST, PUT, OPTIONS, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
spec:
  tls:
  - hosts:
    - my-host.com
    secretName: "manager-tls-secret"
  rules:
  - host: my-host.com
    http:
      paths:
      - path: /elastic(.*)
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-master
            port:
              number: 9200

```

**Comment by Dweston88** [comment]
@rubenvp8510 Do you need any more information to replicate?

**Comment by rubenvp8510** [comment]
I think it is, I'll give it a try today and see if I can replicate.

Thank you!

**Comment by dealboy** [comment]
Hi, we are having a similar issue when using an elastic with a tls signed from our internal PKI (although we add the ca.crt in jaeger conf)

we do not get  _unable to get **local** issuer certificate_  but instead only `  unable to get issuer certificate` 

full line from logs: 

`elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1124)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1124))`

+ it works fine when using the standalone containers, with  the es.use-aliases=true 
+ it works almost fine when using jaeger operator with  the es.use-aliases=false (but it creates wrong indices in elastic!! :D )

**Comment by dealboy** [comment]
Sorry, our case was related to Python and Intermediate certificates (our ca.crt had only intermediate cert, adding the full chain makes it work fine) 
Found it https://stackoverflow.com/questions/64219172/curl-cacert-vs-python-requests-verify

**Comment by Dweston88** [comment]
@rubenvp8510 Were you able to replicate the behavior?

**Comment by jpkrohling** [comment]
ping @rubenvp8510

**Comment by Dweston88** [comment]
I just keep getting this error when the initial application deployment.

{"level":"fatal","ts":1624558328.6729038,"caller":"command-line-arguments/main.go:79","msg":"Failed to create span writer","error":"**elastic: Error 500 (Internal Server Error): String index out of range: 0** [type=**string_index_out_of_bounds_exception**]","stacktrace":"main.main.func1\n\tcommand-line-arguments/main.go:79\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:838\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\tcommand-line-arguments/main.go:137\nruntime.main\n\truntime/proc.go:204"}

**Comment by Dweston88** [comment]
Was able to get past that error. Now getting this when collector and query pods spin up

"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available"

**Comment by rubenvp8510** [comment]
Still not able to reproduce the issue SSL issue, I'll try to reproduce the error you mentioned here, but seems like there is a communication issue between your pods and the elasticsearch.

Is this URL ` https://elasticsearch_url/elastic` accurrate? Or it should be`  https://elasticsearch_url` ?

**Comment by Dweston88** [comment]
I was able to get pass the TLS issue by included the full certificate Chain. (Cert|CA|Root). I had to adjust the URL by adding elastic/ (Dont forget the slash). Now I am getting this error when the collector and query pods try to start up.

        server-urls: https://my-site/elastic/


{"level":"fatal","ts":1624622076.0722783,"caller":"command-line-arguments/main.go:75","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available","stacktrace":"main.main.func1\n\tcommand-line-arguments/main.go:75\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:838\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\tcommand-line-arguments/main.go:137\nruntime.main\n\truntime/proc.go:204"}

**Comment by Dweston88** [comment]
I was able to resolve all issues. I had to adjust the Nginx ingress to not redirect requests. Should look something like this.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-proxy
  namespace: elastic-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - my-host.com
    secretName: "tls-secret"
  rules:
  - host: my-host.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quickstart-es-http
            port:
              number: 9200
```
