### ISSUE TITLE
Need documentation on how to use private image repository

### ISSUE THREAD

**Issue by jimpete** [jaegertracing/jaeger-operator#1466]
## Requirement - what kind of business use case are you trying to solve?

As a military installation, I want documentation on how to pull the images from new locations in the Jaeger Custom Resource instance 

## Problem - what in Jaeger blocks you from solving the requirement?

I cant find the place to put the spark, esIndexCleaner, esRollover, and esLookback images.  This seems to work except for those.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master.observability.svc:9200
  volumeMounts:
  - name: elastic-data
    mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: elastic-data
    emptyDir: {}
  ingester:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-ingester
  agent:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-agent
  collector:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-collector
  query:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-query
  ingress:
    hosts:
      - jaeger.<my cluster>.<my internal domain>
      
# These do not work - need documentation how to specify these      
  spark:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/spark-dependencies
  esIndexCleaner:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-index-cleaner
  esRollover:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-rollover
  esLookback:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-rollover
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Please document the specification of the images in the CRD

**Comment by jpkrohling** [comment]
We still do not have a doc with the full CRD options, your best source of information is the Go type for it, here:

https://github.com/jaegertracing/jaeger-operator/blob/b601fc5e46ac523ba1c244befe640508e8d866ea/pkg/apis/jaegertracing/v1/jaeger_types.go

And I see the image property for the options you listed:

https://github.com/jaegertracing/jaeger-operator/blob/b601fc5e46ac523ba1c244befe640508e8d866ea/pkg/apis/jaegertracing/v1/jaeger_types.go#L582-L596

https://github.com/jaegertracing/jaeger-operator/blob/b601fc5e46ac523ba1c244befe640508e8d866ea/pkg/apis/jaegertracing/v1/jaeger_types.go#L643-L645

https://github.com/jaegertracing/jaeger-operator/blob/b601fc5e46ac523ba1c244befe640508e8d866ea/pkg/apis/jaegertracing/v1/jaeger_types.go#L619-L633

The spec is a typical Docker spec: you might need to set the version, and optionally the SHA.

**Comment by jimpete** [comment]
Very happy to hear the documentation is underway for the CRD options.
I read the specification and found my missing image specification under ```storage:```

Here is what works:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master.observability.svc:9200
    spark:
      image: docker-proxy.nexus.<my-domain>/jaegertracing/spark-dependencies
    esIndexCleaner:
      image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-es-index-cleaner
    esRollover:
      image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-es-rollover
    esLookback:
      image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-es-rollover
  volumeMounts:
  - name: elastic-data
    mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: elastic-data
    emptyDir: {}
  allInOne:
    image: docker-proxy.nexus.<my-domain>/jaegertracing/all-in-one
  ingester:
    image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-ingester
  agent:
    image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-agent
  collector:
    image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-collector
  query:
    image: docker-proxy.nexus.<my-domain>/jaegertracing/jaeger-query
  ingress:
    hosts:
      - jaeger.<my-cluster>.<my-domain>
```
