### ISSUE TITLE
Cannot catch the requests from jaeger-agent

### ISSUE THREAD

**Issue by LuChenjing** [jaegertracing/jaeger-operator#1469]
**Describe the bug**
Use the jaeger-operator to deploy jaeger tracing. Set the agent run as daemonset. After installation, only can see the requests from sidecar agent of query pod, not for the agent pods.
Operator version: 1.22.1

**To Reproduce**
Here is my operator yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-operator
  namespace: onest-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger-operator
  template:
    metadata:
      labels:
        name: jaeger-operator
    spec:
      serviceAccountName: jaeger-operator
      containers:
        - name: jaeger-operator
          image: registry.paas/onest-observer/jaeger-operator:1.22.1
          ports:
            - containerPort: 8383
              name: http-metrics
            - containerPort: 8686
              name: cr-metrics
          args: ["start", "--log-level=debug"]
          imagePullPolicy: Always
          env:
            # - name: WATCH_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "jaeger-operator"
```
Here is my jaeger manifest:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cassandra-test
  namespace: onest-observer
spec:
  strategy: production
  collector:
    image: registry.paas/onest-observer/jaeger-collector:1.22.0
    options:
      log-level: debug
  agent:
    strategy: DaemonSet
    image: registry.paas/onest-observer/jaeger-agent:1.22.0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: observer.onest.cmss/jaeger-agent
                operator: In
                values:
                - "true"
    options:
      log-level: debug
  query:
    image: registry.paas/onest-observer/jaeger-query:1.22.0
    serviceType: NodePort
    nodePort: 30686
    options:
      log-level: debug
  allInOne:
    image: registry.paas/onest-observer/all-in-one:1.22.0
  ingester:
    image: registry.paas/onest-observer/jaeger-ingester:1.22.0
  storage:
    type: cassandra
    options:
      cassandra:
        servers: 10.181.***.**
        keyspace: jaeger_v1_zhengzhou
    cassandraCreateSchema:
      datacenter: "Zhengzhou_DC"
      image: registry.paas/onest-observer/jaeger-cassandra-schema:1.22.0
      mode: "prod"
    spark:
      image: registry.paas/onest-observer/spark-dependencies:1.22.0
```
Here is the screenshots:
![image](https://user-images.githubusercontent.com/42744697/121286425-67066a00-c912-11eb-87ee-76990c2100f8.png)
![image](https://user-images.githubusercontent.com/42744697/121286501-80a7b180-c912-11eb-8413-30ff2849d40b.png)

Here is the pods' status:
![image](https://user-images.githubusercontent.com/42744697/121286724-d2e8d280-c912-11eb-91bd-970cbc8f5b35.png)

**Expected behavior**
Shown all the request from the agent pods

**Version (please complete the following information):**
 - OS: [ Linux]
 - Jaeger version: [e.g. 1.22]
 - Deployment: [Kubernetes 1.18]
