### ISSUE TITLE
Jaeger "simple-prod" is not deployed

### ISSUE THREAD

**Issue by gionapaolini** [jaegertracing/jaeger-operator#1474]
**Describe the bug**
When I try to deploy the example strategy for production:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
```
I get no error, but there is no pod deployed, and if I run `kubectl get jaeger` I get the response:
```
NAME          STATUS   VERSION
simple-prod            1.21.0
```
**To Reproduce**
1.  Deploy the jaeger operator from the helm chart https://jaegertracing.github.io/helm-charts jaeger-operator 2.21.0 
2.  Deploy the production strategy yaml example (mentioned above)

**Expected behavior**
I expect jaeger pods to be deployed

**Version (please complete the following information):**
 - OS: Cluster running on K3D under wsl2, in windows
 - Jaeger version: 1.22.1 (Chart: 2.21.0)
 - Deployment: Kubernetes with Helm

**What troubleshooting steps did you try?**
The troubleshooting only helps in application errors, this seems to be a deployment error
