### ISSUE TITLE
Issue with spark dependencies job when using elastic search cluster serving at a specific base path

### ISSUE THREAD

**Issue by tirumerla** [jaegertracing/jaeger-operator#1478]
## Requirement - what kind of business use case are you trying to solve?

Enabling tracing for our internal apps

## Problem - what in Jaeger blocks you from solving the requirement?

Running into this issue when using existing elastic search cluster which is serving at a specific path with spark dependency job. 

```
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot resolve ip for hostname: st-demo-3.xyz.io/elasticsearch                                                 │
│     at org.elasticsearch.hadoop.util.SettingsUtils.resolveHostToIpIfNecessary(SettingsUtils.java:84)                                                                                                      │
│     at org.elasticsearch.hadoop.util.SettingsUtils.qualifyNodes(SettingsUtils.java:46)                                                                                                                    │
│     at org.elasticsearch.hadoop.util.SettingsUtils.declaredNodes(SettingsUtils.java:142)                                                                                                                  │
│     at org.elasticsearch.hadoop.util.SettingsUtils.discoveredOrDeclaredNodes(SettingsUtils.java:148)                                                                                                      │
│     at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:67)                                                                 
```

I'm using Jaeger-operator helm chart and here are my configurations

```
    # -- Specifies whether Jaeger instance should be created
    create: true
    spec:
      # -- Deployment Strategy. Default is "allInOne"
      strategy: production
      storage:
        type: elasticsearch
        options:
          es:
            use-aliases: true
            server-urls: https://st-demo-3.xyz.io/elasticsearch
        # -- ES index cleaner config
        esIndexCleaner:
          enabled: true
          # -- number of days to wait before deleting a record.
          numberOfDays: 1
          # -- cron schedule. Perform Daily updates at 23:55 after waiting period.
          schedule: "55 23 * * *"
        # -- ES rollover config
        esRollover:
          # -- conditions when to rollover to a new index
          conditions: "{\"max_age\": \"2d\"}"
          # -- how long should be old data available for reading (2 days)
          readTTL: 48h
          # -- cron schedule. Perform Daily updates at 23:55 after rollover period
          schedule: "55 23 * * *"
      # -- Jaeger Collector config
      collector:
        maxReplicas: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        options:
          es:
            use-aliases: true
          # -- log-level info by default
          log-level: debug
      # -- Jaeger Query config
      query:
        options:
          query:
            base-path: /tracing
          es:
            use-aliases: true
          # -- log-level info by default
          log-level: debug
       # -- Jaeger Spark dependencies
       dependencies:
          enabled: true
          elasticsearchClientNodeOnly: true
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

* Support elastic search cluster serving at a base path with spark dependencies cron job.

Not sure if there is a workaround for this.
