### ISSUE TITLE
Operator fails to create Ingress, pathType is missing

### ISSUE THREAD

**Issue by superbiche** [jaegertracing/jaeger-operator#1482]
**Describe the bug**
Operator fails to update Ingress: 

```
time="2021-06-22T23:40:56Z" level=error msg="failed to apply the changes" error="Ingress.extensions \"jaeger-default-query\" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified" execution="2021-06-22 23:40:56.317575558 +0000 UTC" instance=jaeger-default namespace=observability
```

**To Reproduce**
1. Deploy the operator
2. Deploy a Jaeger CR
3. Check the operator logs

Here is the Jaeger definition:  

```yaml
kind: Jaeger
apiVersion: jaegertracing.io/v1
metadata:
  name: jaeger-default
  namespace: observability
spec:
  agent:
    options:
      log-level: debug
  collector:
    maxReplicas: 4
    options:
      collector.zipkin.host-port: ':9411'
    priorityClassName: apps-critical
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: jaeger-basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
    enabled: true
    hosts:
      - jaeger.mydomain.com
    security: none
    tls:
      - hosts:
          - jaeger.mydomain.com
        secretName: jaeger-default-tls
  storage:
    dependencies:
      enabled: true
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 2Gi
      schedule: 55 * * * *
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    options:
      es:
        index-prefix: jaeger
        server-urls: 'http://default-elasticsearch-es-http.logging.svc.cluster.local:9200'
    secretName: jaeger-es-secret
    type: elasticsearch
  # strategy: streaming
  strategy: production
  ui:
    options: {}
```
I previously managed to access this Ingress, which is weird. I'd say that it stopped working when I did some experiments to deploy with the `streaming` strategy, but I'm not sure at all.  

It seems that https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/ingress/query.go#L131 doesn't set the `pathType` at all. My Go knowledge is very limited so maybe I'm wrong.  

**Expected behavior**

**Version (please complete the following information):**
 - OS: CentOS 8
 - Jaeger version: NC
 - Deployment: Operator v1.23.0

**Comment by jpkrohling** [comment]
@rkukura, can you take a look at this?

**Comment by rubenvp8510** [comment]
I haven't seen this issue before, but I fixed this issue on this PR while I was trying to fix the ingress tests:

**Comment by alexandrevilain** [comment]
Hi @rubenvp8510 and @superbiche (it's a small world, even on Github 😄 )

I faced the exact same issue trying to expose jaeger UI using istio ingress gateway.
Here is an example manifest:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  agent:
    strategy: Sidecar
  ingress:
    enabled: true
    hosts:
      - my-test-domain.io
    tls:
      - hosts:
          - my-test-domain.io
        secretName: my-secret
    annotations:
      kubernetes.io/ingress.class: istio
```

Using release 1.23.0 with jaeger operator deployed with the official helm-chart, I have the same log line than @superbiche :

```
time="2021-07-01T15:50:11Z" level=error msg="failed to apply the changes" error="Ingress.extensions \"jaeger-query\" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified" execution="2021-07-01 15:50:10.936511162 +0000 UTC" instance=jaeger namespace=observability
```

So, I built my own docker image using b9d1e02 
```
$ git clone https://github.com/jaegertracing/jaeger-operator.git
$ git checkout b9d1e025b67b9afc25e79c73c9f2876c5a5e4dab
$ make docker
```

Then I pushed it to my private registry and updated the helm chart. The error log disapered, ingress is now well updated. 

It seems that #1491 fixes this issue. Perhaps it would be worth to create a 1.23.1 with this fix ?
