### ISSUE TITLE
failed to store the running status into the current CustomResource

### ISSUE THREAD

**Issue by anarcher** [jaegertracing/jaeger-operator#1483]
**Describe the bug**
I deploy fresh install of jaeger operator on K8S and a jaeger deployment but the operator can't reconcile completed.

**To Reproduce**
1. deploy fresh install of jaeger operator
2. apply jaeger CRD

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: addon-tracing
spec:
  agent: {}
  allInOne:
    options:
      collector.zipkin.host-port: "9411"
      log-level: debug
      memory.max-traces: 10000
  collector:
    maxReplicas: 1
    options:
      collector.zipkin.host-port: "9411"
      log-level: debug
  ingress:
    enabled: false
  sampling:
    options:
      default_strategy:
        param: 0.1
        type: probabilistic
  strategy: allinone
```

**Expected behavior**

`Reconciling Jaeger completed`.

**Screenshots**
![image](https://user-images.githubusercontent.com/12271/123063173-23e6e380-d448-11eb-8b7a-e56616fb4afe.png)

**Version (please complete the following information):**
 - k8s:  eks 1.18
 - Jaeger version: [e.g. 1.8]   1.22.0 (Jaeger Operator: 1.22.1) 

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

It seems that the operator can't update the status of Jaeger CRD . Unfortunately, I don't know why ..
https://github.com/jaegertracing/jaeger-operator/blob/v1.22.1/pkg/controller/jaeger/jaeger_controller.go#L195

**Additional context**
