### ISSUE TITLE
Integration with elastic.co

### ISSUE THREAD

**Issue by jkotiuk** [jaegertracing/jaeger-operator#1493]
Hi,

I'm integrating jaeger with elastic cloud APM (https://www.elastic.co/guide/en/apm/server/current/jaeger.html). Elastic requires to pass a secret as tag in order to authenticate. Currently it is not possible to mount custom secrets as env variables so I'm forced to expose it as a part of manifest.

I've also tried to do some workaround with volume mounts but it didn't work:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  agent:
    options:
      reporter.grpc.tls.enabled: true
      reporter.grpc.host-port: <endpoint>
      agent.tags: elastic-apm-auth=Bearer $(cat /go/bin/mount/apm_token)
    volumes:
      - name: apm
        secret:
          secretName: apm
    volumeMounts:
      - name: apm
        mountPath: /go/bin/mount
        readOnly: true
    strategy: DaemonSet
```

I've ended up encrypting my manifest with sops so it looks like following:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
    name: jaeger
spec:
    agent:
        options:
            reporter.grpc.tls.enabled: true
            reporter.grpc.host-port: <endpoint>
            agent.tags: ENC[AES256_GCM,data:EncryptedStringHere,type:str]
        strategy: DaemonSet
```

This is not optimal and I'd like to pass a secret as a value to `--agent.tags="elastic-apm-auth=Bearer <secret-token>"`
