### ISSUE TITLE
UI won't load with custom ingress

### ISSUE THREAD

**Issue by gionapaolini** [jaegertracing/jaeger-operator#1509]
**Describe the bug**
Title is self explanatory

**To Reproduce**
1 - Deploy the jaeger operator: 
```
helm install jaegertracing/jaeger-operator
```
2 - Deploy jaeger and custom ingress
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  ingress:
    enabled: false
  query:
    base-path: /jaeger
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master:9200

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jaeger-query
spec:
  rules:
  - http:
      paths:
      - path: /jaeger
        backend:
          serviceName: jaeger-query
          servicePort: 16686

```
( I have also tried to apply base-path to query.options.base-path with the same results)
**Expected behavior**
Go to http://{ingresscontrollerip}/jaeger and display UI

**Screenshots**
![image](https://user-images.githubusercontent.com/15687088/125630477-e68f73ab-ab60-46ad-9ca6-3a20a5efcee2.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: [e.g. 1.22.0]
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
I have looked into 2 similar issues:  https://github.com/jaegertracing/jaeger-kubernetes/issues/94 and https://github.com/jaegertracing/jaeger-kubernetes/issues/81 both of which seems to refer to an issue with rewrite target, which I don't use.

**Comment by gionapaolini** [comment]
I have resolved the issue, I needed to use:
```
allInOne:
  options:
    query:
      base-path: /jaeger
```
for when using the allInOne strategy
and
```
query:
  options:
    query:
      base-path: /jaeger
```
for when using Production strategy
