### ISSUE TITLE
Add a default CPU/memory requests and limits to the operator

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1514]
Similar to #872, but for the operator. The following should be more than sufficient even when the operator is managing hundreds of CRs.

```yaml
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
```
