### ISSUE TITLE
Support for IngressClassName for newer Ingress API

### ISSUE THREAD

**Issue by wkit23** [jaegertracing/jaeger-operator#1550]
With older version of ingress API (e.g. networking.k8s.io/v1beta1), it was usually done with annotations (e.g. kubernetes.io/ingress.class). However, with the stable version of ingress API (networking.k8s.io/v1) the annotation way is deprecated and should use the newer ingressClassName spec.

This is particular important especially in k8s 1.22 where the older API version obsoleted and we need to use the newer spec.
Example ingress
```yaml
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "example-ingress"
spec:
  ingressClassName: "external-lb"
  rules:
  - host: "*.example.com"
    http:
      paths:
      - path: "/example"
        pathType: "Prefix"
        backend:
          serviceName: "example-service"
          servicePort: 80
```

[more details](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)
