### ISSUE TITLE
Operator should allow some components to be skipped for installation 

### ISSUE THREAD

**Issue by aravindvs** [jaegertracing/jaeger-operator#1558]
## Requirement

Flexibility of Jaeger components installation with k8s operator

## Problem

When using Jaeger Kubernetes Operator, there is no option to skip a component from being installed

## Proposal
Have the ability to skip installing a component; For example update the component installation (https://www.jaegertracing.io/docs/1.26/operator/#production-strategy) to have an option like below:
```
spec:
  strategy: production
  agent:
     install: "false" # default can be "true"

```
