### ISSUE TITLE
Operator doesn't create service for agents?

### ISSUE THREAD

**Issue by rlex** [jaegertracing/jaeger-operator#1604]
**Describe the bug**
No service created when agent is deployed as daemonset

**To Reproduce**
1. Deploy operator
2. Deploy jaeger:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger-ae
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  agent:
    strategy: DaemonSet
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/jaegertracing/jaeger-clickhouse:0.8.0
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-clickhouse
        configuration-file: /plugin-config/config.yaml
        log-level: debug
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-clickhouse
```

**Expected behavior**
Service pointing to jaeger-agent should be created.
Taken from jaeger installed with non-operator chart:
```
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: jaeger
spec:
  ports:
    - name: zipkin-compact
      protocol: UDP
      port: 5775
      targetPort: zipkin-compact
    - name: jaeger-compact
      protocol: UDP
      port: 6831
      targetPort: jaeger-compact
    - name: jaeger-binary
      protocol: UDP
      port: 6832
      targetPort: jaeger-binary
    - name: http
      protocol: TCP
      port: 5778
      targetPort: http
    - name: admin
      protocol: TCP
      port: 14271
      targetPort: admin
  selector:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
  clusterIP: 192.168.170.207
  type: ClusterIP
  sessionAffinity: None
```
