### ISSUE TITLE
Issues setting up jaeger-operator (helm chart) with custom docker registry

### ISSUE THREAD

**Issue by bzlom** [jaegertracing/jaeger-operator#1621]
**Describe the bug**
When trying to setup jaeger-operator (helm chart) with a custom docker registry it fails for *allinone* strategy. Specifically it's missing the imagePullSecrets option that's required when you use a custom registry. We're using ArgoCD to deploy our helm charts on AWS EKS. 

**To Reproduce**
1. Try to create a CRD with all in one strategy:
```
          spec:
            strategy: allInOne
            allInOne:
              image: <CUSTOM_DOCKER_REGISTRY>/jaegertracing/all-in-one:1.27
              options:
                log-level: info
              imagePullSecrets:
                - name: <SOME_SECRET>
```
2. it returns an error that it can't pull the image from the registry since it's missing the required credentials

**Expected behavior**
Being able to pull the docker image from a custom docker registry

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: latest (1.27.0) using 2.26.0 helm chart
 - Deployment: Kubernetes (EKS)

**What troubleshooting steps did you try?**
Analized the code ( https://github.com/jaegertracing/jaeger-operator/blob/66e7911177f7e85d92ad10e00ac8692306da7d7c/pkg/apis/jaegertracing/v1/jaeger_types.go#L243-L284 ) to see if there is an option for `imagepullsecrets` in `allinone` strategy - couldn't find any.
