### ISSUE TITLE
Jaeger deployment issues in Kubernetes

### ISSUE THREAD

**Issue by venkataphaniv** [jaegertracing/jaeger-operator#1649]
Hi,

 I'm working to deploy Jaeger in my test env in AWS EKS. The pods to be monitored are in default namespace.

I've created the Jeager Operator (v1.28) in observability namespace, and the jaeger-operator deployment & pod are getting created successfully.

 When creating the jaeger instance from the operator of type production, the jaeger is created however neither the jaeger pod, nor the ingress are getting created. 

**Version:**
 - OS: Amazon Linux
 - Jaeger version: 1.28
 - Deployment: Kubernetes

## Yaml snippet for tracer deployment with production strategy, storage - cassandra (jtprod.yaml)
--------------------------
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegertracer
  namespace:
spec:
  strategy: production
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 0.5
  storage:
    type: cassandra
    options:
      cassandra:
        servers: internal-a1-1179306.ap-southeast-1.elb.amazonaws.com
        keyspace: tccc_jaeger
        username: cassandra
        env:
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cassandra-secret
        - name: TRACE_TTL
          value: 2629800
        - name: DEPENDENCIES_TTL
          value: 2629800
      cassandraCreateSchema:
        enabled: false
        datacenter: "dev"
        mode: "test"
  collector:
    autoscale: false
    maxReplicas: 1
    resources:
      limits:
        cpu: 30m
        memory: 128Mi
```

## Results:
----------------------

**$ kubectl apply -f  jtprod.yaml**
jaeger.jaegertracing.io/jaegertracer created

**$ kubectl get po --all-namespaaces | grep jaeger**
NAMESPACE   NAME           STATUS   VERSION   STRATEGY     STORAGE     AGE
observability   jaeger-operator-5786ff487b-xbj92          1/1     Running   0          3h32m

**Note:** _jaegertracer pod is not created_

**$ kubectl get jaegers**
NAMESPACE   NAME           STATUS   VERSION   STRATEGY     STORAGE     AGE
default     jaegertracer                      production   cassandra   24s

**$ kubectl get ingress**
No resources found

**$ kubectl -n observability get deployment jaeger-operator -o jsonpath="**
{.spec.template.spec.containers[0].env}"
[{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"OPERATOR_NAME","value":"jaeger-operator"}]

$ kubectl apply -f  jtprod.yaml
jaeger.jaegertracing.io/jaegertracer created

**Expected behavior**
Being able to create jaeger pod and connect to agents deployed as sidecars within the target pods
