### ISSUE TITLE
Do we not have a way to disable rollover job when doing ilm?

### ISSUE THREAD

**Issue by perezjasonr** [jaegertracing/jaeger-operator#1655]
Describe the bug

according to the documentation:

> In the context of the Operator it means that ILM can be used instead of rollover cron jobs. The Jaeger project does not provide a direct integration with the ILM, however the Jaeger instance can be configured to use index aliases (required by ILM) and disable index template creation and rollover cron jobs.

however in the example below this, use aliases is true, create template is false, but i cannot find any example of disabling the rollover job.

To Reproduce

1 deploy es
2 set up ilm for jaeger to manage the indices
3 deploy jaeger using operator with an es backend, have use index true and create template false

Expected behavior

as the steps above follow the "ILM" section, rollover would be handled by the ilm policy, and a rollover job would not be initialized.

Screenshots
n/a

Version (please complete the following information):

OS: linux
Jaeger version: 1.19
Deployment: k8s

What troubleshooting steps did you try?
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

i have just been scanning the docs for an example of how to disable rollover job, other things let you set to false or disable but i can't find this one

Additional context

**Comment by perezjasonr** [comment]
ive also tried explicitly setting it to false now in the jaeger object.

```
esRollover:
    enabled: false
```

its still trying to run:

`jaeger-operator-jaeger-es-rollover-create-mapping   0/1                      2m54s`

and failing with

`Error creating: pods "jaeger-operator-jaeger-es-rollover-create-mapping-" is forbidden: error looking up service account observability/jaeger-operator-jaeger: serviceaccount "jaeger-operator-jaeger" not found`


but ive already created the mapping, since you have to create the initial index for ilm (with its mapping)

**Comment by perezjasonr** [comment]
i updated the chart and now it says 

```
"message: 'error validating data: ValidationError(Jaeger.spec.storage.esRollover):
          unknown field "enabled" in io.jaegertracing.v1.Jaeger.spec.storage.esRollover'"
```

so ive taken that out, but now im back where i started 

`jaeger-operator-jaeger-es-rollover-create-mapping   0/1                      3m24s`


and

```
Error creating: pods "jaeger-operator-jaeger-es-rollover-create-mapping-" is forbidden: error looking up service account observability/jaeger-operator-jaeger: serviceaccount "jaeger-operator-jaeger" not found


[dad-user@ip-10-42-10-151 ~]$ kubectl get sa -n observability
NAME              SECRETS   AGE
default           1         17m
jaeger-operator   1         17m

```

so it seems not only to be looking for an sa that doesn't exist, but also if i have it set to:

```
es:
        create-index-templates: false
        server-urls: <URL>
        use-aliases: true
```
it appears to still be trying to do a rollover/mapping job.

**Comment by perezjasonr** [comment]
I might be closing this issue, ive now updated the chart and the operator image and i no longer see it trying to make rollup jobs so perhaps my issue is outdated.

but now running into a new issue:
https://github.com/jaegertracing/helm-charts/issues/241

if i get past this and i never see the operator try to spin up rollup jobs i will close this issue

**Comment by perezjasonr** [comment]
followup:

to get past that issue i set clusterRole to true, but its back to trying to run a rollover job:

```
Error: failed to create template: jaeger-span, request failed, status code: 403, body: {"error":{"root_cause":[{"type":"security_exce
ption","reason":"action [indices:admin/template/put] is unauthorized for user [jaeger]"}],"type":"security_exception","reason":"actio
n [indices:admin/template/put] is unauthorized for user [jaeger]"},"status":403}
```

why is it trying to create an index template when ive set that to false, heres the live jaeger object:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-operator-jaeger
  namespace: observability
spec:

  < ...omitting sections >

    dependencies:
      enabled: false
      resources: {}
    elasticsearch:
      storage: {}
    esIndexCleaner:
      enabled: false
      resources: {}
    esRollover:
      resources: {}
    grpcPlugin: {}
    options:
      es:
        create-index-templates: false 
        server-urls: <url>
        use-aliases: true
    secretName: jaeger-secret
    type: elasticsearch
  strategy: allInOne
  ui:
    options: {}
status:
  phase: Failed
  version: ""
```

create-index-templates is false in the live jaeger object why is it trying to create a template (which I've already prepared in advance for ilm).
