### ISSUE TITLE
Jaeger agent spec not passed between CRD and deployment object

### ISSUE THREAD

**Issue by goshlanguage** [jaegertracing/jaeger-operator#1699]
**Describe the bug**
Hey gang, thanks for your work on this project.

The jaeger-operator does not appear to honor or reference the `Jaeger` spec with regards to resources. I've looked at a bunch of supporting documentation and it appears that it should be a part of the CRD spec as it is for the `collector` as well as other services, eg [this doc](https://www.jaegertracing.io/docs/1.29/operator/#understanding-custom-resource-definitions), but in practice I see differing behavior for the agent specifically, preventing me from using this great project.

**To Reproduce**
1. Deploy jaeger-operator (helm chart)
2. Create a Jaeger CRD with resource defined in the agent spec (see spec below)
3. Wait for operator to create deployment and look at the deployment spec (see example below)

**Expected behavior**
Deployment should define the exact resources passed into the crd

**Screenshots**

CRD:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
  name: jaeger-agent
spec:
  agent:
    options:
      log-level: debug
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    strategy: streaming
```

Generated deployment spec, relative to resources:

```
    spec:
      containers:
        - name: jaeger
          resources: {}
```

**Version (please complete the following information):**
 - OS: flatcar
 - Jaeger version: from jaeger-operator helm chart 2.27.0
 - Deployment: bare metal, k8s 1.21.3

**What troubleshooting steps did you try?**
deployed spec, waited for the operator to create the resource, which fails for me because my environment requires resources to be defined for all pod specs.

**Additional context**
I wouldn't mind contributing a patch, though I'm unfamiliar with the codebase. Please accept my apologies as well if I'm overlooking some bit of documentation.

Thanks for any help you can provide.

**Comment by rubenvp8510** [comment]
The agent section only applies  when you are using it as a `daemonset`, you need to set your `agent.strategy=daemonset`. Otherwise the agent will be injected as a sidecar on the application pod.

On the other side, It seems that there is a mistake in your CRD, you are setting the `agent strategy=streaming.` the only possible values are `sidecar` or `daemonset`, That strategy is different from the `jaeger.spec.strategy` which can have other values like streaming, allInOne, production etc...

If what you want is to set limits on all the resources created by Jaeger operator you can try to specify it on the` Jaeger.spec`


This is an example for AllInOne strategy,

```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

In this way you can set general resources for all Jaeger components, and can override it for each one. E.g if you are using the `streaming` strategy instead of `AllInOne` you can put limits on the `ingestor`.
