### ISSUE TITLE
Jaeger instance fails after update to 1.29.1 with `no kind is registered for the type v1.ElasticsearchList in scheme "pkgruntimescheme.go:100"`

### ISSUE THREAD

**Issue by bo0ts** [jaegertracing/jaeger-operator#1722]
We run jaeger in an OpenShift 4.8 cluster, after upgrading to jaeger 1.29.1 (from a very old 1.25) our single jaeger instance started failing. Recreating the jaeger resource brought no change. The operator has been installed and upgraded via OLM/OperatorHub.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        index-prefix: tracing
        server-urls: 'http://...'
    secretName: es-jaeger-user
status:
  phase: Failed
  version: ''
```

The operator log has the following error message:

```
time="2022-01-24T10:33:47Z" level=error msg="failed to apply the changes" error="no kind is registered for the type v1.ElasticsearchList in scheme \"pkg/runtime/scheme.go:100\"" execution="2022-01-24 10:33:47.00443715 +0000 UTC" instance=tracing namespace=jaeger
2022-01-24T10:33:47.030Z	ERROR	controller-runtime.manager.controller.jaeger	Reconciler error	{"reconciler group": "jaegertracing.io", "reconciler kind": "Jaeger", "name": "tracing", "namespace": "jaeger", "error": "no kind is registered for the type v1.ElasticsearchList in scheme \"pkg/runtime/scheme.go:100\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214
```

In our cluster the following elasticsearch CRs are installed:

```
oc get crd | grep -i elasticsearches
elasticsearches.elasticsearch.k8s.elastic.co
elasticsearches.logging.openshift.io
```

ElasticSearch is provided by two different operators: the `OpenShift Elasticsearch Operator 5.3.3-4` and the `ECK Operator 1.8.0`.

Any idea what is happening here and how to fix it?
