### ISSUE TITLE
Upgrading to operator 2.27.1 and Jaeger 1.29.0 will create ES indexes with incorrect replicas

### ISSUE THREAD

**Issue by zzvara** [jaegertracing/jaeger-operator#1723]
**Describe the bug**
Jaeger 1.29.0 will create ES indexes with incorrect replicas when using Elasticsearch.

**To Reproduce**

1. Start Jaeger operator.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaeger-operator
        namespace: kube-system
      version: 2.27.1
  interval: 30m0s
  values:
    rbac:
      create: true
      clusterRole: true
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 10m
```

2. Deploy Jaeger.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-default
  namespace: development
spec:
  strategy: production
  ingress:
     enabled: false
  collector:
    maxReplicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        cpu: 200m
        memory: 350Mi
  query:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 100Mi
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elastic-es-http-certs-public
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-es-http.development:9200
        index-prefix: jaeger-development-
        tls:
          ca: /es/certificates/ca.crt
        num-shards: 1
        num-replicas: 0
    secretName: jaeger-default-elastic-credentials
    dependencies:
      enabled: false
      schedule: "55 23 * * *"
      sparkMaster:
      resources:
        requests:
          memory: 4096Mi
        limits:
          memory: 4096Mi
```

**Expected behavior**
Each index that Jaeger creates should have 1 shard and 0 replicas.

**Screenshots**

New indexes are with incorrect replica counts.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/8371789/150793007-9101b535-7cfa-4f72-9ba8-4a122a44a5ae.png">

**Version (please complete the following information):**
 - OS: Flatcar
 - Jaeger version: 1.29.0
 - Deployment: Intel HNS2600TPR Xeon E5

**What troubleshooting steps did you try?**
Checked CRD definition and examples for setting `num-shards`, but could not find any.
