### ISSUE TITLE
jaeger-operator not creating jaeger agent when creating jaeger instance after installation

### ISSUE THREAD

**Issue by sanasz91mdev** [jaegertracing/jaeger-operator#1752]
**Describe the bug**
jaeger-operator not creating jaeger agent when creating jaeger instance after installation of jaeger operator

**To Reproduce**
I am using the following file to just introduce ES storage to be used by collector and query

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod-es
spec:
  strategy: production
  storage:
    type: elasticsearch 
    options:
      es:
        server-urls: https://search-test-g7fbo7pzghdquvvgxty2pc6lqu.us-east-2.es.amazonaws.com
        index-prefix: jaeger-span
        username: test
        password: toO_b1g_to_handle_box

```
**Expected behavior**
jaeger agent, collector, query components should be created. Collector and query components are created but **jaeger agent** component is **not** being created

i then deployed my app manifest file with setting auto inject to true ... but since agent is not created hence no traces are being sent to the provided collector.

my app deployment file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
    spec:
      containers:
        - name: node-app1
          image: mycontainerstore.azurecr.io/node-web-app
          ports:
          - containerPort: 3100
            protocol: TCP
```

**Screenshots**
![image](https://user-images.githubusercontent.com/39674269/153848458-b4af02f1-55f2-47be-bd2d-d7d5ea062312.png)

**Version (please complete the following information):**
 - OS: AKS Azure kubernetes cluster service
 - Jaeger version: 1.31.0
 - Deployment: Kubernetes
