### ISSUE TITLE
Jaeger operator does not pull esIndexCleaner dependencies image from the specified repo

### ISSUE THREAD

**Issue by xichengliudui** [jaegertracing/jaeger-operator#1803]
**Describe the bug**
Jaeger operator does not pull `esIndexCleaner`、`dependencies` image from the specified repository

**To Reproduce**
Steps to reproduce the behavior: kubectl apply yaml
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod-elasticsearch
spec:
  strategy: production
  collector:
    image: abcsys.cn:5000/mesh1.8.1/jaeger-collector:1.21.0
  query:
    image: abcsys.cn:5000/mesh1.8.1/jaeger-query:1.21.0
  agent:
    image: abcsys.cn:5000/mesh1.8.1/jaeger-agent:1.21.0
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
      esIndexCleaner:
        enabled: true
        numberOfDays: 30
        schedule: "55 23 * * *"
        image: abcsys.cn:5000/mesh1.8.1/jaeger-es-index-cleaner:1.21.0
      dependencies:
        enabled: true
        image: abcsys.cn:5000/mesh1.8.1/spark-dependencies:latest
```

**Expected behavior**
esIndexCleaner and dependencies pull images from the specified repository

**Screenshots**
It can be seen that the image is not pull from the specified image repo
![image](https://user-images.githubusercontent.com/40875627/156517819-0b2b5dbb-5f74-499d-814a-2e7450ecaaf9.png)
![image](https://user-images.githubusercontent.com/40875627/156517927-dbb2c10e-d69d-4de0-ab57-9f75f212f878.png)

**Version (please complete the following information):**
 - OS: [e.g. Linux] `CentOS Linux release 7.6.1810 (Core)`
 - Jaeger version: [e.g. 1.8] `jaeger-query:1.21.0` `jaeger-collector:1.21.0` `jaeger-agent:1.21.0`
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...] kubernetes
