### ISSUE TITLE
Deployment of jaeger-operator to minikube running k8s 1.19 is blocked by webhook

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1844]
**Describe the bug**
I tried to deploy the jaeger-operator to a minikube instance running kubernetes version 1.19 and it failed

**To Reproduce**
1. Start minikube with **minikube start --memory 12288 --vm-driver hyperkit --addons "ingress,metrics-server" --kubernetes-version='1.19.0'**
2.make docker push deploy

**Expected behavior**
The operator should deploy

**Screenshots**
```
certificate.cert-manager.io/jaeger-operator-serving-cert created
issuer.cert-manager.io/jaeger-operator-selfsigned-issuer created
mutatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-mutating-webhook-configuration configured
validatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-validating-webhook-configuration configured
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "deployment.sidecar-injector.jaegertracing.io": Post "https://jaeger-operator-webhook-service.observability.svc:443/mutate-v1-deployment?timeout=10s": dial tcp 10.101.31.210:443: connect: connection refused
make: *** [deploy] Error 1
```

**Comment by frzifus** [comment]
thanks, i will give it a try!

**Comment by pavolloffay** [comment]
@kevinearls did you run `make cert-manager` before deploying the operator? Did the output indicate that the cert-manager API isready?

**Comment by kevinearls** [comment]
@pavolloffay Yes, I have a script that does all of this.  I ran the same script without the **kubernetes-version** option and it worked correctly.  (I probably should have mentioned this above but I had alread discussed it with @frzifus )

**Comment by frzifus** [comment]
what makes me a little questionable is `failed calling webhook "deployment.sidecar-injector.jaegertracing.io"`. If the webhook is registered and the operator deployment has to pass this webhook, it will not work because the operator is not active at this time. :facepalm: 
Maybe we can exclude the operator using a [objectSelector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector).

i thought of something like this. (I don't know if it works that way). Try it out later.
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
    objectSelector: # skip operator deployments
      matchExpressions:
        - key: name
          operator: NotIn
          values: ["jaeger-operator"]

```
