### ISSUE TITLE
default value for tls cipher-suites

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1879]
## Requirement - what kind of business use case are you trying to solve?

In [jaeger #3564](https://github.com/jaegertracing/jaeger/pull/3564), a new flag was introduced for configuring the cipher used. but this flag is not set by default by the operator.

## Problem - what in Jaeger blocks you from solving the requirement?

A decision if a default parameter is basically desired. If yes, we could set them in the Jaeger Collector [[pkg/config/tlscfg/flags.go](https://github.com/jaegertracing/jaeger/blob/df44af3c1967c53ed7f20bcd1b2be3cdc19540d2/pkg/config/tlscfg/flags.go#L62)] or on the operator side [[pkg/config/tls/tls.go](https://github.com/jaegertracing/jaeger-operator/blob/06bcef636327ef490609b999b8e5585a4f498bcd/pkg/config/tls/tls.go#L15)].

## Proposal - what do you suggest to solve the problem or improve the existing situation?

From my point of view a default value in the operator would be the way to go.
An extention of [tls.go](https://github.com/jaegertracing/jaeger-operator/blob/06bcef636327ef490609b999b8e5585a4f498bcd/pkg/config/tls/tls.go#L15) could look like this:
```golang
if len(util.FindItem("--collector.grpc.tls.cipher-suites=", *options)) == 0 {
	*options = append(*options,
		"--collector.grpc.tls.cipher-suites=TLS_TODO_1;TLS_TODO_2",
	)
}
```

## Any open questions to address

Which cipher should be enabled by default?

---

cc @pavolloffay @iblancasa

**Comment by frzifus** [comment]
I was wondering why the problem does not occur on kubernetes. it seems to affect only openshift [[tls.go](https://github.com/jaegertracing/jaeger-operator/blob/06bcef636327ef490609b999b8e5585a4f498bcd/pkg/config/tls/tls.go#L16)].

**Comment by frzifus** [comment]
Seems this line was causing the issue: 
https://github.com/jaegertracing/jaeger/pull/3564/files#diff-24f34a75ab1f6765a63e2361744c174c109053d88e449ce503371a4ae37b7fb1R84

But its already fixed in:
https://github.com/jaegertracing/jaeger/pull/3030/files#diff-24f34a75ab1f6765a63e2361744c174c109053d88e449ce503371a4ae37b7fb1R98

**Comment by morningspace** [comment]
I see a similar issue when deploy jaeger on OpenShift. I was not able to start jaeger pod w/ the following error in pod logs:

```console
2022/05/17 08:34:23 could not start gRPC collector failed to get cipher suite ids from cipher suite names: cipher suite  not supported or doesn't exist
```

Any idea to work around this issue? @frzifus

**Comment by frzifus** [comment]
hi @morningspace, which version are you using?

**Comment by morningspace** [comment]
@frzifus I'm using 1.33.0.

**Comment by frzifus** [comment]
mh.. makes sense. Its caused by a line that sets `` as argument.  Since its in Jaeger 1.33.0 you could try to specify the flag:
```
spec.collector.grpc.tls.cipher-suites=TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
```
Alternatives would be to install [RHOSDT 2.3](https://docs.openshift.com/container-platform/4.9/distr_tracing/distr_tracing_arch/distr-tracing-architecture.html). It is based on jaeger 1.30 or wait for the next release of 1.34. (I am working on that right now and i would like to complete it today https://github.com/jaegertracing/jaeger-operator/pull/1884)

**Comment by morningspace** [comment]
Thanks @frzifus for your time and looking forward to the v1.34.0 release. For the workaround, just to confirm, where to find the place to specify the flag, is it the jaegertracing.io/v1/jaeger CR or the deployment w/ the container args?

**Comment by frzifus** [comment]
It needs to be defined in the JaegerCR. The openshift TLS config is defined [here](https://github.com/jaegertracing/jaeger-operator/blob/06bcef636327ef490609b999b8e5585a4f498bcd/pkg/config/tls/tls.go#L39). 
I assume it should look like this (untested):
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    options:
      grpc:
         tls:
           cipher-suites: "TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200

```
