### ISSUE TITLE
es-index-cleaner does not pass TLS flags

### ISSUE THREAD

**Issue by loelu** [jaegertracing/jaeger-operator#1896]
**Describe the bug**
Since v1.34.0 Jaeger the `tls.enabled=true` flag is mandatory if other `tls.*` flags are used: https://github.com/jaegertracing/jaeger/pull/3030
But the Operator does not seem to pass the `tls.enabled` flag from the es config to the es-index-cleaner CronJob

**To Reproduce**
1. Create Jaeger instance with a secured connection to Elasticsearch
```yaml
...
    storage:
      elasticsearch:
        name: elasticsearch
      esIndexCleaner:
        enabled: true
        numberOfDays: 10
        resources: {}
        schedule: 55 22 * * *
      options:
        es:
          num-replicas: 0
          num-shards: 5
          server-urls: https://jaeger-es-http:9200
          tls:
            ca: /es/certificates/tls.crt
            enabled: true
...
```
2. Wait for execution of es-index-cleaner Job and observe the following error:
```
> kubectl logs jaeger-instance1-es-index-cleaner-1653346500-9zsp2 -n instance1
Error: es.tls.* options cannot be used when es.tls.enabled is false
Usage:
  jaeger-es-index-cleaner NUM_OF_DAYS http://HOSTNAME:PORT [flags]

Flags:
      --archive                       Whether to remove archive indices. It works only for rollover
      --es.password string            The password required by storage
      --es.tls.ca string              Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --es.tls.cert string            Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --es.tls.enabled                Enable TLS when talking to the remote server(s)
      --es.tls.key string             Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --es.tls.server-name string     Override the TLS server name we expect in the certificate of the remote server(s)
      --es.tls.skip-host-verify       (insecure) Skip server's certificate chain and host name verification
      --es.username string            The username required by storage
  -h, --help                          help for jaeger-es-index-cleaner
      --index-date-separator string   Index date separator (default "-")
      --index-prefix string           Index prefix
      --rollover                      Whether to remove indices created by rollover
      --timeout int                   Number of seconds to wait for master node response (default 120)

2022/05/23 22:55:22 es.tls.* options cannot be used when es.tls.enabled is false

```
**Expected behavior**
I expected the `tls.enabled` flag to be passed by the Operator, just like it's described [here](https://www.jaegertracing.io/docs/1.34/operator/#elasticsearch-index-cleaner-job): 

> The connection configuration is derived from the storage options.

**Version (please complete the following information):**
 - Jaeger version: 1.34.0
 - Deployment: Kubernetes
