### ISSUE TITLE
Jaeger instance upgrade with elasticsearch instance failed in v1.34

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#1916]
**Describe the bug**
jaeger instance upgrade failed. version: `v1.30` to `v1.34`

Error:
```
time="2022-05-27T12:01:10Z" level=error msg="failed to apply the changes" error="failed to delete Elasticsearch, deletion is needed for certificate migration to Elasticsearch operator: elasticsearches.logging.openshift.io \"elasticsearch\" not found" execution="2022-05-27 12:01:08.189231243 +0000 UTC" instance=jaeger-es namespace=jk
1.653652870315856e+09	ERROR	controller.jaeger	Reconciler error	{"reconciler group": "jaegertracing.io", "reconciler kind": "Jaeger", "name": "jaeger-es", "namespace": "jk", "error": "failed to delete Elasticsearch, deletion is needed for certificate migration to Elasticsearch operator: elasticsearches.logging.openshift.io \"elasticsearch\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/remote-source/jaegerop/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/remote-source/jaegerop/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
```

**To Reproduce**
1. Install jaeger-operator v1.30
2. deploy jaeger instance with self provision Elasticsearch
3. Upgrade the jaeger-operator to v1.34

**Expected behavior**
For some reason tried to delete the elasticsearch instance second time.
We can ignore the `not found` error

**Version (please complete the following information):**
 - Jaeger version: v1.30 to v1.34
 - Deployment: OpenShift 4.6

#### CR
```
# This CR deploys Jaeger and Elasticsearch
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-es
#  namespace: observability
spec:
  #ingress:
  #  security: none
  strategy: production
  storage:
    esIndexCleaner:
      enabled: false
      schedule: "*/2 * * * *"
      numberOfDays: 0
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      #storage:
      #  storageClassName: ""
      #  size: "5G"
      resources:
        requests:
          memory: "1Gi"
          cpu: "510m"
        limits:
          memory: "1Gi"
```
