### ISSUE TITLE
es-rollover doesnt work on openshift

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1932]
**Describe the bug**
Missing permission on openshift.

**To Reproduce**
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: es-rollover
spec:
  ingress:
    security: none
  strategy: production
  storage:
    esIndexCleaner:
      enabled: true
      schedule: "*/2 * * * *"
      numberOfDays: 1
    esRollover:
      schedule: "*/1 * * * *"
      conditions: '{"max_age":"10m"}'
      readTTL: 10m
    type: elasticsearch
    options:
      es.use-aliases: true
    elasticsearch:
      nodeCount: 1
      resources:
        requests:
          memory: "1Gi"
          cpu: "510m"
        limits:
          memory: "1Gi"

```

**Expected behavior**
Avoid CrashLoopBackOff.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.30 or higher
 - Deployment: Openshift

**Additional context**
```
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     ContainerCreating   0          2s
es-rollover-es-index-cleaner-27568570--1-5fsqg             0/1     ContainerCreating   0          3s
es-rollover-es-lookback-27568570--1-cjqw9                  0/1     ContainerCreating   0          3s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     Error               0          4s
es-rollover-es-lookback-27568570--1-cjqw9                  0/1     Completed           0          4s
es-rollover-es-index-cleaner-27568570--1-5fsqg             0/1     Completed           0          4s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     Error               1 (2s ago)   5s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     CrashLoopBackOff    1 (2s ago)   6s
es-rollover-es-index-cleaner-27568570--1-5fsqg             0/1     Completed           0            6s
es-rollover-es-lookback-27568570--1-cjqw9                  0/1     Completed           0            6s
es-rollover-es-index-cleaner-27568564--1-4cdps             0/1     Terminating         0            6m6s
es-rollover-es-index-cleaner-27568564--1-4cdps             0/1     Terminating         0            6m6s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     Error               2 (15s ago)   19s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     CrashLoopBackOff    2 (14s ago)   32s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     Error               3 (26s ago)   44s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     CrashLoopBackOff    3 (14s ago)   58s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     Error               4 (50s ago)   94s
es-rollover-es-rollover-27568570--1-6kw7q                  0/1     CrashLoopBackOff    4 (15s ago)   108s
es-rollover-es-index-cleaner-27568572--1-2db4v             0/1     Pending             0             0s
es-rollover-es-index-cleaner-27568572--1-2db4v             0/1     Pending             0             0s 
```

```
k logs -n testing es-rollover-es-rollover-27568570--1-6kw7q
Error: failed to create rollover target: jaeger-span-write, request failed, status code: 403, body: {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:admin/rollover] and User [name=CN=user.jaeger,OU=OpenShift,O=Logging, roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:admin/rollover] and User [name=CN=user.jaeger,OU=OpenShift,O=Logging, roles=[], requestedTenant=null]"},"status":403} 
```
