### ISSUE TITLE
[Bug]: Update the Jaeger Operator image will automatically update options es

### ISSUE THREAD

**Issue by xichengliudui** [jaegertracing/jaeger-operator#2014]
### What happened?

update `jaeger-operator:1.21.2` -> `jaeger-operator:1.25.0`, then the `/spec/storage/options` config is automatically updated
before
```yaml
spec:
    options:
      es:
          password: elastic
          server-urls: http://192.168.2.240:30029
          username: elastic
```
after
```yaml
spec:
    options:
      es.password: elastic
      es.server-urls: http://192.168.2.240:30029
      es.username: elastic
```

### Steps to reproduce

1: apply jaeger-operator:1.21.2
2: apply the Jaeger resource that contains the es config
3: update `jaeger-operator:1.21.2` -> `jaeger-operator:1.25.0`
4: watching jaeger-prod-elasticsearch

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod-elasticsearch
  namespace: kube-system
spec:
  agent:
    image: jaeger-agent:1.21.0
  collector:
    image: jaeger-collector:1.21.0
  query:
    image: jaeger-query:1.21.0
  storage:
    dependencies:
      enabled: false
    esIndexCleaner:
      enabled: false
    options:
      es:
          password: elastic
          server-urls: http://192.168.2.240:30029
          username: elastic
    type: elasticsearch
  strategy: production
```

### Expected behavior

The options config will be updated

### Operating system

centos

### Deployment model

k8s
