### ISSUE TITLE
[Bug]: Creating jaeger instance fails with service \"jaeger-operator-webhook-service\" not found

### ISSUE THREAD

**Issue by rhino-harley** [jaegertracing/jaeger-operator#2057]
### What happened?

We have a CIT environment that is used for automatically building and deploying of our solution. Jaeger operator and then a Jaeger instance are both part of that deployment. In between each build we remove all of the stuff installed by a previous run so that we start with a 'clean slate'. In our new releases we recently we upgraded the version of jaeger operator that we use from 2.24 to 2.33. Ever since that point we can no longer install our older release which still depends on 2.24. A few other points:

- In both cases we install the jaeger operator with helm
- The clean up script uninstalls the helm chart and also removes any CRDs left behind
- Installs using the 2.33 version still seem to work ok

We use ansible to create the Jaeger instance. The error we get when we try to create a Jaeger instance we get an is:
```
TASK [install-jaeger-operator : Install Jaeger] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl create -f /scm/kubernetes//jaeger-config/jaeger.yaml --namespace upf-jaeger", "delta": "0:00:00.390136", "end": "2022-09-04 21:50:17.594757", "msg": "non-zero return code", "rc": 1, "start": "2022-09-04 21:50:17.204621", "stderr": "Error from server (InternalError): error when creating \"/scm/kubernetes//jaeger-config/jaeger.yaml\": Internal error occurred: failed calling webhook \"mjaeger.kb.io\": Post \"[https://jaeger-operator-webhook-service.upf-operator.svc:443/mutate-jaegertracing-io-v1-jaeger?timeout=10s\](https://jaeger-operator-webhook-service.upf-operator.svc/mutate-jaegertracing-io-v1-jaeger?timeout=10s\)": service \"jaeger-operator-webhook-service\" not found", "stderr_lines": ["Error from server (InternalError): error when creating \"/scm/kubernetes//jaeger-config/jaeger.yaml\": Internal error occurred: failed calling webhook \"mjaeger.kb.io\": Post \"[https://jaeger-operator-webhook-service.upf-operator.svc:443/mutate-jaegertracing-io-v1-jaeger?timeout=10s\](https://jaeger-operator-webhook-service.upf-operator.svc/mutate-jaegertracing-io-v1-jaeger?timeout=10s\)": service \"jaeger-operator-webhook-service\" not found"], "stdout": "", "stdout_lines": []}
```
The contents of the /scm/kubernetes//jaeger-config/jaeger.yaml file is:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: "upf-jaeger"
spec:
  strategy: production
  collector:
    image: nrc3ldockreg01vm.am.tsacorp.com:18095/jaegertracing/jaeger-collector:1.31
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    options:
      log-level: info
  agent:
    strategy: DaemonSet
    image: nrc3ldockreg01vm.am.tsacorp.com:18095/jaegertracing/jaeger-agent:1.31
    options:
      log-level: info
      reporter:
        grpc:
          host-port: dns:///jaeger-collector-headless.upf-jaeger.svc.cluster.local:14250
    resources: {}
  query:
    image: nrc3ldockreg01vm.am.tsacorp.com:18095/jaegertracing/jaeger-query:1.31
    options:
      query:
        base-path: /IntegrationProxyWebApp/jaeger
      log-level: info
    resources: {}
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-es-http.upf-elasticsearch.svc.cluster.local:9200
        timeout: 120s
```
I have had a bit of a look online and no-one else seems to be reporting the same issue. We don't have a service called jaeger-operator-webhook-service running in the namespace where the jaeger operator was installed (or any other namespace).

### Steps to reproduce

Not sure how easy this will be do reproduce

### Expected behavior

Jaeger instance should be created

### Jaeger backend version

1.31

### SDK

N/A

### Operating system

RHEL

### Deployment model

Kubernetes using helm charts
