### ISSUE TITLE
[Bug]: Query Ingress not properly created with streaming strategy

### ISSUE THREAD

**Issue by erdody** [jaegertracing/jaeger-operator#2088]
### What happened?

If you define a path in jaeger query, that path is used for the ingress in deployment strategy == production.
The same doesn't happen if you switch to deployment strategy == streaming.

https://github.com/jaegertracing/jaeger-operator/blob/v1.38.0/pkg/ingress/query.go#L86

### Steps to reproduce

1. Create a Jaeger with production strategy, and set a base path in query. Something like:

```
spec:
  strategy: production
  query:
    options:
      query:
        base-path: /jaeger
...
```

you'll see an ingress with a rule similar to this:
```
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: jaeger-query
            port:
              number: 16686
        path: /jaeger
        pathType: ImplementationSpecific
```

2. Do the same with `strategy: streaming`

Now the ingress only has a default backend service:

```
spec:
  defaultBackend:
    service:
      name: jaeger-query
      port:
        number: 16686
```

### Expected behavior

The ingress should not be different. 

### Jaeger backend version

1.38.0

### Deployment model

kubernetes
