### ISSUE TITLE
[Bug]: operator clashes with calico-system namespace

### ISSUE THREAD

**Issue by ViliusS** [jaegertracing/jaeger-operator#2116]
### What happened?

I have a deployed namespaced jaeger-operator to standard Kubernetes 1.23 cluster. Cluster networking runs on Calico which was deployed using pretty standard [Tigera operator](https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico).

Every few minutes Jaeger operator pod crashes with errors pointing to `calico-system` namespace. My WATCH_NAMESPACE variable is only set to watch one other namespace with my custom application. Nothing points to `calico-system`.

[Full logs](https://github.com/jaegertracing/jaeger-operator/files/9990381/logs-from-jaeger-operator-in-jaeger-operator-59d488c8c7-98kcr.log) and
[deployment YAMLs](https://github.com/jaegertracing/jaeger-operator/files/9990412/jaeger-operator-deployment.txt) attached. The deployment scripts will deploy Jaeger operator itself into `jaeger-operator` namespace (I've made changes from `observability`), and it will also deploy needed role to the custom `myapp` namespace.

### Steps to reproduce

1. Install Calico using [Tigera operator](https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico) on your Kubernetes cluster.
2. Install namespaced Jaeger operator.
3. Watch the logs.

### Expected behavior

Jaeger operator should not crash or have anything requests to Calico namespace.

### Relevant log output

```shell
1.668170281347599e+09	INFO	verify deployment	{"namespace": "calico-system"}
W1111 12:38:01.359861       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger-operator:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
E1111 12:38:01.359912       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger-operator:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
1.668170291340387e+09	ERROR	failed to get the namespace for the deployment, skipping injection based on namespace annotation	{"namespace": "calico-system", "error": "Timeout: failed waiting for *v1.Namespace Informer to sync"}
github.com/jaegertracing/jaeger-operator/controllers/appsv1.(*deploymentInterceptor).Handle
	/workspace/controllers/appsv1/deployment_webhook.go:84
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/webhook.go:169
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/http.go:98
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.1/prometheus/promhttp/instrument_server.go:56
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.1/prometheus/promhttp/instrument_server.go:142
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.1/prometheus/promhttp/instrument_server.go:104
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2462
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2916
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1966
```

**Comment by iblancasa** [comment]
Taking a look to the logs and your CRs, I think something is not properly set. I cannot see this in your CRs:
```yaml
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
```
This is set in the `./bundle/manifests/jaeger-operator.clusterserviceversion.yaml` file, that is the one used to deploy the operator. So, the operator is trying to reach all the namespaces in your cluster.

Also, is not a crash: it's just a timeout.

**Comment by ViliusS** [comment]
There is:
```
        envFrom:
        - configMapRef:
            name: jaeger-config
```
which points to ConfigMap containing only WATCH_NAMESPACE: myappnamespace

**Comment by Jeansen** [comment]
I have something similar. Bare metal kubernetes, Calico and Jaeger. I have not tried the namespace-scoped deployment. Cluster-wide deployment is fine. But as soon as I create a CR, I see something like this in the operator logs:

```
1.677246481830629e+09	ERROR	Reconciler error	{"controller": "jaeger", "controllerGroup": "jaegertracing.io", "controllerKind": "Jaeger", "Jaeger": {"name":"jaeger","namespace":"default"}, "namespace": "default", "name": "jaeger", "reconcileID": "1a110673-aea2-4a19-bac7-997882ced9a0", "error": "Internal error occurred: failed calling webhook \"validate.nginx.ingress.kubernetes.io\": failed to call webhook: Post \"https://ingress-nginx-controller-admission.default.svc:443/networking/v1/ingresses?timeout=10s\": dial tcp 10.110.210.159:443: connect: no route to host"}
```

Here's my CR:

```
t <<EOF | kubectl apply -f -
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://quickstart-es-http:9200
        version: 7
        create-index-templates: false
        tls:
          ca: /es/certificates/ca.crt
        num-shards: 1
        num-replicas: 0
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: quickstart-es-http-certs-public
EOF
```

I checked DNS is fine, and it is. Inside a temporary pod, I can nslookup the server above. Also, other services, e.g. elasic, do not seem to have a problem here ...
