### ISSUE TITLE
[Bug]: Admin ports of the agent, collector, and query deployments are not exposed.

### ISSUE THREAD

**Issue by thomaspaulin** [jaegertracing/jaeger-operator#2203]
### What happened?

As a Jaeger operator
I want to monitor the health of my Jaeger installation
so that I am alerted when something goes awry.

### Steps to reproduce

1. Install the Jaeger operator via the [Helm Charts](https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger-operator).
2. Write a Jaeger CRD spec which uses `production` strategy.
3. Describe the agent, collector, and query **deployments** and notice that the admin ports are exposed there.
4. Then describe the agent, collector, and query **services** e.g. `kubectl describe service {{jaeger-name}}-collector` and note that the [admin ports](https://www.jaegertracing.io/docs/1.43/monitoring/) are not listed in the service description.

### Expected behavior

I expected the admin ports to be exposed via the service so I can use Prometheus to scrape the `/metrics` endpoint on that port.

### Additional context

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
  namespace: default
spec:
  strategy: production
  collector:
    image: jaeger/jaegertracing/jaeger-collector:1.39.0
    resources:
      limits:
        cpu: 2
        memory: 2048Mi
  ingress:
    enabled: true
    hosts:
      - jaeger.{{my-cluster-url}}
  query:
    image: jaeger/jaegertracing/jaeger-query:1.39.0
    options:
      prometheus:
        server-url: "http://{{my-prometheus}}:9090"
    metricsStorage: 
      type: prometheus
  agent:
    image: jaeger/jaegertracing/jaeger-agent:1.39.0
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://{{my-elk-stack}}:9200
        index-prefix: jaeger-index
    esIndexCleaner:
      image: jaeger/jaegertracing/jaeger-es-index-cleaner:1.39.0
      enabled: true
    dependencies:
      image: jaeger/jaegertracing/spark-dependencies/spark-dependencies:latest
```

### Jaeger backend version

v1.39.0

### Pipeline

OTEL automatic instrumentation -> Jaeger Collector (production strategy) -> Elasticsearch

### Stogage backend

Elasticsearch v6.8.6

### Operating system

Linux

### Deployment model

Helm Chart to deploy the jaeger-operator, then Jaeger CRD to deploy Jaeger itself
