### ISSUE TITLE
[Feature]: Add PROMETHEUS_SERVER_URL to jaeger query spec

### ISSUE THREAD

**Issue by thomaspaulin** [jaegertracing/jaeger-operator#2207]
### Requirement

 As a Jaeger operator with an independently deployed Prometheus
 I want to specify where my Prometheus lives
 so that I make use of Service Performance Monitoring of my services from within the Jaeger UI

### Problem

[We can specify that we should be using Prometheus, but not how to reach Prometheus](https://github.com/jaegertracing/jaeger-operator/blob/f3eb6284d3bcd3bde75f01820bbd4ca6c7af00e6/pkg/deployment/query.go#L159), despite it being to the `metricsStorage` option.

### Proposal

Add the PROMETHEUS_SERVER_URL setting at the same level as METRICS_STORAGE_TYPE one, a la
```
query:
  metricsStorage: 
    type: prometheus
    server-url: <my-prometheus-here>:9090
```

**Comment by iblancasa** [comment]
Would you like to send a PR?

**Comment by antoniomerlin** [comment]
Hi, if this is not assigned can i take it.

**Comment by antoniomerlin** [comment]
Hi, @iblancasa is the spec structure is fine:-
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
spec:
  allInOne:
    metricsStorage:
      type: prometheus
      server-url: http://prometheus.devhawkstudio.duckdns.org:9090 // This would be attach to container as PROMETHEUS_SERVER_URL env variable.

```

**Comment by antoniomerlin** [comment]
Hi, just a query if i use this definition :-
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
spec:
  query:
    metricsStorage:
      type: prometheus
```
I am unable to any value in ```q.jaeger.Spec.Query.MetricsStorage.Type``` in pkg/deployment/query.go line no. 131
