### ISSUE TITLE
[Bug]: securityContext and imagePullPolicy is not set for EsIndexCleaner container

### ISSUE THREAD

**Issue by michalschott** [jaegertracing/jaeger-operator#2208]
### What happened?

Here's some configuration I'm using:

```
➜  k explain jaeger.spec.storage.esIndexCleaner.containerSecurityContext
KIND:     Jaeger
VERSION:  jaegertracing.io/v1

RESOURCE: containerSecurityContext <Object>

DESCRIPTION:
     <empty>

FIELDS:
   allowPrivilegeEscalation	<boolean>

   capabilities	<Object>

   privileged	<boolean>

   procMount	<string>

   readOnlyRootFilesystem	<boolean>

   runAsGroup	<integer>

   runAsNonRoot	<boolean>

   runAsUser	<integer>

   seLinuxOptions	<Object>

   seccompProfile	<Object>

   windowsOptions	<Object>
```

Jager instance config:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  storage:
    type: elasticsearch
    esIndexCleaner:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
      enabled: true
      imagePullPolicy: "Always"
```

Created cronjob template does not have securityContext set:

```
➜ k -n jaeger get cj jaeger-es-index-cleaner -o jsonpath='{.spec.jobTemplate.spec.template.spec}' | grep -i nonroot

➜ k -n jaeger get cj jaeger-es-index-cleaner -o jsonpath='{.spec.jobTemplate.spec.template.spec}' | grep -i securityco
ntext
{"containers":[{"args":["7","https://jaeger-es-http:9200"],"env":[{"name":"INDEX_PREFIX","value":"jaeger"},{"name":"ES_TLS_ENABLED","value":"true"},{"name":"ES_TLS_CA","value":"/es/certificates/ca.crt"}],"envFrom":[{"secretRef":{"name":"jaeger-es-auth"}}],"image":"jaegertracing/jaeger-es-index-cleaner:1.43.0","imagePullPolicy":"IfNotPresent","name":"jaeger-es-index-cleaner","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/es/certificates/","name":"certificates","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Never","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"jaeger","serviceAccountName":"jaeger","terminationGracePeriodSeconds":30,"volumes":[{"name":"certificates","secret":{"defaultMode":420,"secretName":"jaeger-es-http-certs-public"}}]}
```

Query, collector and agent are also affected.

### Steps to reproduce

* Install operator (I'm on 1.43.0)
* Provide jaeger instance config with securityContext keys
* This is not set

### Expected behavior

Ability to set securityContext
