### ISSUE TITLE
[Bug]: Ingress jaeger-query has not IngressClass

### ISSUE THREAD

**Issue by Jeansen** [jaegertracing/jaeger-operator#2225]
### What happened?

When I deploy jaeger the operator also createas an Ingress 'jaeger-query'. Although my kubernes IngressClass is configured as default (there is only one Ingress in my setup) and I also set it to watch for Ingress deployments without an IngressClass, the jaeger Ingress always has an IngressClass of '<none>'. 

When I delete the Ingress and recreate it, it has the default IngressClass 'nginx'. But after a while, it is overwritten with '<none>' again. Happens only with jaeger . Other, manually created Ingresses, work just fine!

### Steps to reproduce

1. Prepare a kubernetes Cluster. Mine runs 1.27
2. Install Ingress, like so:  
```
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update
    helm upgrade --install  ingress-nginx ingress-nginx/ingress-nginx  --set watchIngressWithoutClass=true --set controller.ingressClassResource.default=true --namespace ingress-nginx --create-namespace
```
3. Install Jaeger, follow the documentation at https://www.jaegertracing.io/docs/1.18/operator/. The 'AllInOne' Setup should be fine, though I use the production strategey.
4. Check the jaeger-query is there. It should have an IngressClass of 'nginx'.
5. Wait an hour or so....check again. Now it should how an IngressClass of '<none>'.
6. Save the Ingress to to a yaml file: `kubectl get ingress jaeger-query -o yaml > /tmp/ingerss.yaml`
7. Create the Ingress again: `kubectl replace -f /tmp/ingress.yaml --force`
8. Repeat Steps 4 and 5

### Expected behavior

Ingress jaeger-query should always have a default IngressClass 'nginx'.

### Jaeger backend version

v1.44.0

### Stogage backend

Open-Search

### Operating system

Linux, Debian 11

### Deployment model

Kubernetes

**Comment by iblancasa** [comment]
@Jeansen could you provide the CR used to create your Jaeger instance?

**Comment by Jeansen** [comment]
```
cat <<EOF | kubectl apply --force -f -
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: $ns
spec:
  collector:
    autoscale: false
  strategy: production
  agent:
    strategy: DaemonSet
  storage:
    type: elasticsearch
    options:
      log-level: debug
      query:
        base-path: /jaeger
      es:
        server-urls: https://${clusterName}.${ns}:9200
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: ${clusterName}-http-cert

```
