### ISSUE TITLE
[Bug]: `prometheus` storage backend not supported

### ISSUE THREAD

**Issue by tsunamaru** [jaegertracing/jaeger-operator#2244]
### What happened?

Title. Issue similar to https://github.com/jaegertracing/jaeger-operator/issues/564

### Steps to reproduce

1. Set `spec.storage.type` to `prometheus`
2. `k apply -f ...`
3. Watch the logs :)

### Expected behavior

Use `prometheus` as storage backend.

### Relevant log output

```shell
2023-06-26T11:59:01Z	INFO	The provided storage type is unknown. Falling back to 'memory'	{"instance": "jaeger-dev", "namespace": "jaeger", "storage": "prometheus", "known-options": ["memory","cassandra","elasticsearch","kafka","badger","grpc-plugin"]}
```

### Additional context

Prometheus storage description in jaeger docs: https://www.jaegertracing.io/docs/1.46/cli/#jaeger-all-in-one-prometheus

### Jaeger backend version

1.45.0

### Stogage backend

Prometheus

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-dev
  namespace: jaeger
spec:
  strategy: allInOne
  storage:
    type: prometheus
    options:
      prometheus:
        server-url: http://prometheus.default.svc:8428
```

**Comment by iblancasa** [comment]
Hi @tsunamaru.
The Prometheus storage is used for the metrics, not for the traces. You need to specify the metrics storage in the `.spec.metricsStorage` field. There is an example in the [`examples` folder](https://github.com/jaegertracing/jaeger-operator/blob/main/examples/all-in-one-with-metrics-query.yaml):
```yaml
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: debug
      query:
        base-path: /jaeger
      prometheus:
        server-url: "http://prometheus:9090"
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000
```
