### ISSUE TITLE
[Bug]: Jaeger operator ignores --es.num-replicas=0

### ISSUE THREAD

**Issue by ankitcharolia** [jaegertracing/jaeger-operator#2321]
### What happened?

I have externally setup **single node** elasticsearch using `eck-stack` operator and am trying to ingrate jaeger with elasticsearch storage. I see that `jaeger-span-*` and `jaeger-service-*` indices are created with default replica count of `1`. That means `--es.num-replicas: 0`   is being ignored.

I believe that this is happening due to this line: https://github.com/jaegertracing/jaeger-operator/blob/main/pkg/storage/elasticsearch.go#L263

### Steps to reproduce

Jager instance yaml file
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-simple
spec:
  strategy: production
  collector:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      redundancyPolicy: ZeroRedundancy
    options:
      es:
        server-urls: "https://elasticsearch-es-http:9200"
        version: 7                                      # Necessary as it doesn't work with 8 yet
        create-index-templates: false       # Necessary as it doesn't work with 8 yet
        tls:
          ca: /es/certificates/ca.crt
        num-shards: 1
        num-replicas: 0                     
    secretName: jaeger-elasticsearch-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elasticsearch-es-http-certs-public
```

### Expected behavior

`es.num-replicas=0` should be respected.

### Screenshot

![Screenshot from 2023-09-10 13-15-54](https://github.com/jaegertracing/jaeger-operator/assets/6585879/3844e91a-ece7-44b6-acd9-63769b0fcd48)

### Jaeger backend version

1.46.0

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes
