### ISSUE TITLE
[Feature]: Add the option to disable the Jaeger Agent component installation  until it is removed completely from code-base 

### ISSUE THREAD

**Issue by raviranjanelastisys** [jaegertracing/jaeger-operator#2322]
### Requirement

Since the Jaeger Agent is depreciated and Jaeger can accept the traces directly via OTEL SDK , Add the option to disable the Jaeger Agent component installation  until it is removed completely from code-base . Because it is sitting around on the node and using the node resources.

Ex- 

```
jaeger:
  create: true
  spec:
    agent:
      enabled: false  # > This Flag should be present in the Jaeger Operator
```

### Problem

There is no flag `enabled: false` to disable the individual component installation specially `Jaeger-agent`

### Proposal

Add the flag `enabled: false`
