### ISSUE TITLE
[Bug]: On Openshift, jaeger-operator does not respect hosts set in ingress section

### ISSUE THREAD

**Issue by xmj** [jaegertracing/jaeger-operator#2334]
### What happened?

According the Jaeger CRD, and the PR merged in 
https://github.com/jaegertracing/jaeger-operator/pull/749
it should be possible to set dynamic hostnames for the ingress resource.

On openshift, this is not the case: the hostname of the route is always a composite of the jaeger instance name and the namespace it is deployed into. 

See https://github.com/jaegertracing/jaeger-operator/blob/main/pkg/route/query.go#L48

Could you please enhance jaeger-operator to respect the hosts: / tls[].hosts lists?

Thank you!

### Steps to reproduce

Deploy jaeger operator and configure instance like so:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: openshift-distributed-tracing.jaeger-operator
  name: jaeger
  namespace: openshift-distributed-tracing
spec:
<snip>
  strategy: production
<snip>
  ingress:
    hosts:
      - {{ .Values.jaeger.hostname }}
    tls:
      - hosts:
          - {{ .Values.jaeger.hostname }}
        secretName: jaeger-jaeger-elasticsearch
    openshift:
        {"namespace": "openshift-distributed-tracing", "resource": "pods",
        "verb": "get"}
    options: {}
    resources: {}
    security: oauth-proxy
<snip>
```

You can use any FQDN instead of `{{ .Values.jaeger.hostname }}`, as per the `route/query.go` configuration it will be ignored anyway.

### Expected behavior

Ingress route is created with FQDN specified in the ingress.hosts / ingress.tls.hosts values.

### Jaeger backend version

v1.47.0-2 (RH/Openshift edition)

### Stogage backend

ElasticSearch

### Operating system

Openshift / RHEL

### Deployment model

k8s
