### ISSUE TITLE
[Bug]: Badger cannot create directory error: mkdir /badger/key: permission denied

### ISSUE THREAD

**Issue by yasharne** [jaegertracing/jaeger-operator#2400]
### What happened?

Deployed jaeger with Badger but the pod cannot create the directory

### Steps to reproduce

pvc manifest:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-data
  namespace: observability
spec:
  storageClassName: "standard-rwo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

Jaeger manifest:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
        span-store-ttl: 168h
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  volumeMounts:
  - name: data
    mountPath: /badger
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: jaeger-data
```

### Expected behavior

Jaeger start working with the PVC

### Relevant log output

```shell
2023/12/14 11:24:43 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
2023/12/14 11:24:43 applicatio version: git-commit=9866eba85aed1b0a66a77c8c6928a372edc5040f, git-version=v1.52.0, build-date=2023-12-06T09:43:23Z
{"level":"info","ts":1702553083.274908,"caller":"flags/service.go:119","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1702553083.275028,"caller":"flags/service.go:125","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1702553083.2754045,"caller":"flags/admin.go:129","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1702553083.275485,"caller":"flags/admin.go:143","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1702553083.2756839,"caller":"flags/admin.go:121","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1702553083.2758367,"caller":"grpc@v1.59.0/clientconn.go:489","msg":"[core][Channel #1] Channel created","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2759068,"caller":"grpc@v1.59.0/clientconn.go:1845","msg":"[core][Channel #1] original dial target is: \"localhost:4317\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.275949,"caller":"grpc@v1.59.0/clientconn.go:1852","msg":"[core][Channel #1] parsed dial target is: {URL:{Scheme:localhost Opaque:4317 User: Host: Path: RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2759652,"caller":"grpc@v1.59.0/clientconn.go:1866","msg":"[core][Channel #1] fallback to scheme \"passthrough\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2759922,"caller":"grpc@v1.59.0/clientconn.go:1874","msg":"[core][Channel #1] parsed dial target is: {URL:{Scheme:passthrough Opaque: User: Host: Path:/localhost:4317 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.276007,"caller":"grpc@v1.59.0/clientconn.go:2007","msg":"[core][Channel #1] Channel authority set to \"localhost:4317\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2762573,"caller":"grpc@v1.59.0/resolver_conn_wrapper.go:246","msg":"[core][Channel #1] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"localhost:4317\",\n      \"ServerName\": \"\",\n      \"Attributes\": null,\n      \"BalancerAttributes\": null,\n      \"Metadata\": null\n    }\n  ],\n  \"Endpoints\": [\n    {\n      \"Addresses\": [\n        {\n          \"Addr\": \"localhost:4317\",\n          \"ServerName\": \"\",\n          \"Attributes\": null,\n          \"BalancerAttributes\": null,\n          \"Metadata\": null\n        }\n      ],\n      \"Attributes\": null\n    }\n  ],\n  \"ServiceConfig\": null,\n  \"Attributes\": null\n} (resolver returned new addresses)","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2765443,"caller":"grpc@v1.59.0/balancer_conn_wrappers.go:180","msg":"[core][Channel #1] Channel switches to new LB policy \"pick_first\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.276599,"caller":"grpc@v1.59.0/balancer_conn_wrappers.go:298","msg":"[core][Channel #1 SubChannel #2] Subchannel created","system":"grpc","grpc_log":true}
{"level":"info","ts":1702553083.2766745,"caller":"grpc@v1.59.0/clientconn.go:592","msg":"[core][Channel #1] Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"fatal","ts":1702553083.2800155,"caller":"all-in-one/main.go:110","msg":"Failed to init storage factory","error":"Error Creating Dir: \"/badger/key\" error: mkdir /badger/key: permission denied","stacktrace":"main.main.func1\n\tgithub.com/jaegertracing/jaeger/cmd/all-in-one/main.go:110\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tgithub.com/jaegertracing/jaeger/cmd/all-in-one/main.go:243\nruntime.main\n\truntime/proc.go:267"}
```
```


### Screenshot

_No response_

### Additional context

Environment: GKE
Jaeger operator: 1.52.0

### Jaeger backend version

1.52.0

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

Badger

### Operating system

_No response_

### Deployment model

Kubernetes

### Deployment configs

_No response_
