### ISSUE TITLE
[Bug] Running jaeger with ingress behind an application gateway

### ISSUE THREAD

**Issue by sanasz91mdev** [jaegertracing/jaeger-operator#2402]
### What happened?

jaeger ingress does not work with custom path 

### Steps to reproduce

1- Create an application gateway with backend pointing to IP of load balancer provisioned by ingress
2- configure the /jaeger rule in application gateway
3- create an ingress as below:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: query-ingress
    app.kubernetes.io/instance: prod-jaeger-es
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: prod-jaeger-es-query
    app.kubernetes.io/part-of: jaeger
  name: prod-jaeger-es-query
  namespace: observability
  ownerReferences:
  - apiVersion: jaegertracing.io/v1
    controller: true
    kind: Jaeger
    name: prod-jaeger-es
    uid: 52db4ff1-6acd-4b75-aac8-8d97a0ac4ad6
  annotations:
     # replace all paths with /
    konghq.com/strip-path: 'true'
    konghq.com/protocols: "http,https"
spec: 
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: prod-jaeger-es-query
                port:
                  number: 16686
```
you will see when you hit IP: you will see internal resources not being loaded!

![image](https://github.com/jaegertracing/jaeger-operator/assets/39674269/aa44e742-369c-4542-b1e8-ab34ecaa32de)

### Expected behavior

One shpuld be able to view Jaeger UI correctly

### Screenshot

![image](https://github.com/jaegertracing/jaeger-operator/assets/39674269/27a2c576-4c35-4c23-b1aa-0ebcee1224b0)
  this is the problem. internal resources dont load

### Jaeger backend version

v1.52

### SDK

Opentelemetry

### Deployment model

Kubernetes
