### ISSUE TITLE
unable to delete jaeger services in OpenShift

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#243]
Jaeger Operator: jaegertracing/jaeger-operator:1.10.0

OpenShift Master: v3.10.14
Kubernetes Master: v1.10.0+b81c8f8
OpenShift Web Console: v3.10.14

#### jaeger-operator.yaml:
```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  strategy: production
  ingress:
    security: none
  collector:
    image: jaegertracing/jaeger-collector:1.10
    size: 1
    options:
      metrics-backend: expvar
  query:
    image: jaegertracing/jaeger-query:1.10
    size: 1
    options:
      metrics-backend: expvar
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
```

Steps followed,
```
$ oc apply -f jaeger-automation.yaml 
jaeger "jaegerqe" created

$ oc delete -f jaeger-automation.yaml 
jaeger "jaegerqe" deleted
```

All the jaeger services are running after deletion too,

![image](https://user-images.githubusercontent.com/1004403/53569708-d36a5e80-3b8a-11e9-9599-588e8b932506.png)

Operator log: [jaeger-operator-57fb7cd5f5-kvhl9.log](https://github.com/jaegertracing/jaeger-operator/files/2915168/jaeger-operator-57fb7cd5f5-kvhl9.log)
