### ISSUE TITLE
[Bug]: jaeger-operator v1.57.0 query.base-path is broken when strategy is production

### ISSUE THREAD

**Issue by yanqi27** [jaegertracing/jaeger-operator#2593]
### What happened?

I tried to deploy a jaeger instance with strategy=production and custom query.base-path.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  query:
    options:
      query:
        base-path: /jaeger
```
I couldn't access the query UI through web browser. I notice two things that may explain why it doesn't work.
[1] The jaeger container command argument misses `--query.base-path=/jaeger`.
```
...
spec:
  containers:
  - args:
    - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
    env:
    - name: SPAN_STORAGE_TYPE
      value: memory
``` 
[2] The ingress doesn't have the expected rules for `path=/jaeger`.
```
...
spec:
  defaultBackend:
    service:
      name: jaeger-query
      port:
        number: 16686
```

### Steps to reproduce

1. kubectl apply -f jaeger.yaml (contents shown in the above section)
2. review the generated deployment and ingress. (also shown in the above section)

### Expected behavior

The command argument includes `--query.base-path=/jaeger`
