### ISSUE TITLE
How to find my k8s service in jaeger-query UI?

### ISSUE THREAD

**Issue by sunyl527** [jaegertracing/jaeger-operator#262]
![image](https://user-images.githubusercontent.com/33956935/53794385-d5596680-3f6a-11e9-9ae2-ed623aebf8fd.png)
Hello,I annotationed my deployment and service with the sidecar of jaeger instance,updated the ingress as well. Where was wrong?I could not see my service in the jaeger-query UI dashboard.
Here are details:
```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-client:9200
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: simplest-query
spec:
  rules:
    - host: jaeger.test.env
      http:
        paths:
          - backend:
              serviceName: simplest-query
              servicePort: 16686
            path: /
```
the annotation of my deployment and service
```
annotations:
    inject-jaeger-agent: "simplest"
    sidecar.jaegertracing.io/inject: "simplest"
```
Thanks for any help!
