### ISSUE TITLE
Query service is headless

### ISSUE THREAD

**Issue by adinunzio84** [jaegertracing/jaeger-operator#264]
I created a Jaeger instance with:
```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  ingress:
    enabled: false
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
```

This created headless services for the query and collector service. [Istio has trouble routing to headless services](https://github.com/istio/istio/issues/5005#issuecomment-403498879) with VirtualServices, so I was not able to route to the Jaeger UI with one. I disabled ingresses on the Jaeger object because Istio uses Gateways/VirtualServices instead of the Kubernetes Ingress object.
