### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by yatakoi** [jaegertracing/jaeger-operator#2734]
### What happened?

I used the example https://github.com/jaegertracing/jaeger-operator/blob/main/examples/ingress-with-host-pathType.yaml and here is the final manifest

After applying it, the operator reports an error:
```
2024-11-12T08:49:34Z    ERROR    failed to apply the changes    {"instance": "jaeger", "namespace": "observability", "execution": "2024-11-12T08:49:34Z", "error": "Ingress.extensions \"jaeger-query\" is invalid: spec.rules[0].http.paths[0].path: Invalid value: \"\": must be an absolute path"}
```

What am I doing wrong?

### Steps to reproduce

```
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  allInOne:
    image: nexus.xxxxx:8444/devops/jaeger/all-in-one:1.46.0
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
        span-store-ttl: "16h"
  volumeMounts:
  - name: data
    mountPath: /badger
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: jaegerpvc
  query:
    options:
      base-path: "/"
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - xxxxx
```

### Expected behavior

Applying ingress.

### Relevant log output

```shell

```

### Deployment configs

```shell

```
