### ISSUE TITLE
[Bug]: missing `apiVersion` for `CronJob` and `HorizontalPodAutoscaler` in generate mode

### ISSUE THREAD

**Issue by chlunde** [jaegertracing/jaeger-operator#2767]
### What happened?

In generate mode, the `apiVersion` for `CronJob` and `HorizontalPodAutoscaler` (HPA) is missing in the YAML manifest.

### Steps to reproduce

1. go run .  generate --cr examples/simple-prod.yaml  | grep -E '(Horiz|CronJob)' -A 1 -B 1

```
---
kind: CronJob
metadata:
--
---
kind: CronJob
metadata:
--
---
kind: HorizontalPodAutoscaler
metadata:
```

notice: no `apiVersion`

### Expected behavior

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
--
apiVersion: batch/v1
kind: CronJob
metadata:
--
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
```

### Relevant log output

```shell

```

### Deployment configs

```shell

```
