### ISSUE TITLE
Support TLS for spark dependencies

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#294]
Spark dependencies job uses Java keystore for certificates. The docker image allows to configure java opts with ssl configuration - `JAVA_OPTS=-Djavax.net.ssl.`. 

The certs can be mounted via volume and volume mounts which are part of `JaegerCommonSpec`.  The issue that these certs have to be imported into java keystore/thruststore. 

https://developers.redhat.com/blog/2017/11/22/dynamically-creating-java-keystores-openshift/ suggests using init container for the job.

Todos: 
- [ ]  allow configuring JAVA_OPTS to point to keystore/thruststore
- [ ]  import certs into keystore/thruststore

**Comment by pavolloffay** [comment]
Dependent issue in spark-dependencies https://github.com/jaegertracing/jaeger-operator/issues/294

**Comment by pavolloffay** [comment]
@jpkrohling this is not ES specific. The dependency job supports multiple backends.

**Comment by jorgex1** [comment]
Hi @pavolloffay are there any updates on this?

**Comment by pavolloffay** [comment]
There aren't ane news. If anybody has free cycles feel free to take it.

**Comment by jorgex1** [comment]
Spent a bit doing some digging through things and came across this page https://hub.helm.sh/charts/jaegertracing/jaeger

The page mentions that in order to have a version of the spark job working one would need to get the certificates from the elasticsearch cluster and do
```
$ keytool -import -trustcacerts -keystore trust.store -storepass <some pass> -alias es-root -file <es.pem>

$ kubectl create configmap jaeger-tls --from-file=trust.store --from-file=<es.pem>
```

And then use the `jaeger-tls` configmap within the spark job definition as such:
```yaml
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jaeger-spark
            args:
              - --java.opts=-Djavax.net.ssl.trustStore=/tls/trust.store -Djavax.net.ssl.trustStorePassword=<some pass>
            volumeMounts:
              - name: jaeger-tls
                mountPath: /tls
                subPath: 
                readOnly: true
          volumes:
            - name: jaeger-tls
              configMap:
                name: jaeger-tls
          ...
```

Which all sounds like it is in accordance with the issue description.
Is all that right?
