### ISSUE TITLE
jaeger operator crashed, E0312

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#298]
I installed jaeger-operator in OpenShift,
OpenShift Master: v3.11.92
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.92

Image: jaegertracing/jaeger-operator:master
Image ID: docker-pullable://docker.io/jaegertracing/jaeger-operator@sha256:323655a9aaa94630cdb51543f1439ffe1acf55efda94c6223297cd90f5d7cb0a

Try to install the ES cluster via jaeger operator. It was failed. I kept the instance as is. After sometime jaeger-operator stopped working.

I see the following issue in the log,
```
E0312 09:57:42.073743       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
```
[jaeger-operator-545c69455d-8dxm9.log](https://github.com/jaegertracing/jaeger-operator/files/2956285/jaeger-operator-545c69455d-8dxm9.log)

**Comment by jkandasa** [comment]
Crashed right after the first jaeger-services deployment with ES.

log file: 
[jaeger-operator-545c69455d-vrc68.log](https://github.com/jaegertracing/jaeger-operator/files/2956622/jaeger-operator-545c69455d-vrc68.log)

**Comment by jkandasa** [comment]
This issue exactly happening, when we disable oauth-proxy,
 ie: 
```
 ingress:
    security: none
```
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  ingress:
    security: none
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      resources:
    esIndexCleaner:
      enabled: false
      schedule: "*/30 * * * *"
      numberOfDays: 1
```
