### ISSUE TITLE
Switch to disable the ingress resource

### ISSUE THREAD

**Issue by secat** [jaegertracing/jaeger-operator#30]
Is it currently possible to disable the creation of the ingress resource?

If not, I think it would be a good feature to update the CRD spec with an ingress configuration section.

**Comment by jpkrohling** [comment]
Would you like to give it a shot? Should be relatively easy to do.

**Comment by secat** [comment]
Yes, sure I can implement the feature.

For the switch specification, I was thinking of something like:
```yaml
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  ingress:
    enabled: false
```

What do you think about it?

**Comment by jpkrohling** [comment]
Right now, the ingress is applied only to the query deployment. So, to avoid any ambiguity, it would be better to have it as a child of the JaegerQuery struct.

**Comment by secat** [comment]
Should I close this issue?

**Comment by jpkrohling** [comment]
I'm closing. Thanks for the PR!

**Comment by sneko** [comment]
Hi @secat @jpkrohling, I tried to disable ingress but it doesn't work:
```
spec:
  strategy: all-in-one
  all-in-one:
    image: jaegertracing/all-in-one:1.7
    options:
      log-level: info
      memory:
        max-traces: 10000
  query:
    ingress:
      enabled: false

```

Could you help me please? Thanks
