### ISSUE TITLE
integer values should be passed as is

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#302]
when we specify options(collector, query, agent) in CR files when creating actual service, options(integer values) are passed in `scientific notation format`, specific jaeger service throws an exception,

CR file:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:latest
    options:
      metrics-backend: expvar
      collector:
        num-workers: 50
        queue-size: 2000
      es:
        bulk:
          size: 5000000
          workers: 1
          flush-interval: 200ms
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:latest
    options:
      metrics-backend: expvar
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:latest
    options:
      metrics-backend: expvar
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```

Exception in collector:
```
Error: invalid argument "5e+06" for "--es.bulk.size" flag: strconv.ParseInt: parsing "5e+06": invalid syntax
invalid argument "5e+06" for "--es.bulk.size" flag: strconv.ParseInt: parsing "5e+06": invalid syntax
```
