### ISSUE TITLE
Updating via kubectl -f apply does not handle options properly

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#304]
Changing options (storage, query, collector..) in yaml CR and applying change via `kubectl applye` does not work as expected. The updated options get duplicated:

```yaml
    options:
      es:
        bulk:
          flush-interval: 200ms
          size: 10
          workers: 1
      es.bulk.flush-interval: 200ms
      es.bulk.size: "5"
      es.bulk.workers: "1"
```

Created CR - first with `es.bulk.size=5` then changed to 10
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        bulk:
          size: 10
          workers: 1
          flush-interval: 200ms
    elasticsearch:
      nodeCount: 1
      resources:
    esIndexCleaner:
      enabled: true
      schedule: "*/30 * * * *"
      numberOfDays: 1
```
