### ISSUE TITLE
jaeger-collector and query services are keep on "Rolling update in progress...."

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#307]
I installed jaeger services via jaeger-operator and ES cluster via template.
Jaeger-collector and query service keep on "Rolling update in progress...." (keep on deleting and creating collector and query pods)

Image: `jaegertracing/jaeger-operator:master`
Image ID: `docker-pullable://docker.io/jaegertracing/jaeger-operator@sha256:448fd68152858a53d7925cc026fa399eb91561f3b618cf1df8c4adb94a386b9e`

OpenShift Master: v3.11.95
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.95

debug log from jaeger operator: 
[jaeger-operator-545c69455d-5v2j8.log](https://github.com/jaegertracing/jaeger-operator/files/2961284/jaeger-operator-545c69455d-5v2j8.log)

![Screenshot from 2019-03-13 15-44-21](https://user-images.githubusercontent.com/1004403/54276876-63110380-45b4-11e9-8723-999cebca49d5.png)

**Comment by objectiser** [comment]
It seems to be trying to retrieve metrics from 14268, but I believe the metrics are now obtained from the health check port 14269?

**Comment by jkandasa** [comment]
@objectiser I had that hint. I deleted jaeger-operator(to get up jaeger-collector service) and tried with 14268 port from ES pod, It works well.

```
sh-4.2$ curl http://10.128.0.123:14268/metrics
{
"cmdline": ["/go/bin/collector-linux","--es.bulk.flush-interval=200ms","--es.bulk.size=5000000","--es.bulk.workers=1","--metrics-backend=expvar","--collector.num-workers=50","--collector.queue-size=2000","--es.server-urls=http://elasticsearch:9200","--sampling.strategies-file=/etc/jaeger/sampling/sampling.json"],
"jaeger.bulk_index.attempts": 0,
"jaeger.bulk_index.errors": 0,
"jaeger.bulk_index.inserts": 0,
"jaeger.bulk_index.latency-err.p50": 0,
"jaeger.bulk_index.latency-err.p90": 0,
"jaeger.bulk_index.latency-err.p95": 0,
"jaeger.bulk_index.latency-err.p99": 0,
"jaeger.bulk_index.latency-ok.p50": 0,
"jaeger.bulk_index.latency-ok.p90": 0,
"jaeger.bulk_index.latency-ok.p95": 0,
"jaeger.bulk_index.latency-ok.p99": 0,
"jaeger.collector.batch-size.host_jaegerqe-collector-75ddf69996-btpkd": 0,
"jaeger.collector.in-queue-latency.host_jaegerqe-collector-75ddf69996-btpkd.p50": 0,
"jaeger.collector.in-queue-latency.host_jaegerqe-collector-75ddf69996-btpkd.p90": 0,
"jaeger.collector.in-queue-latency.host_jaegerqe-collector-75ddf69996-btpkd.p95": 0,
"jaeger.collector.in-queue-latency.host_jaegerqe-collector-75ddf69996-btpkd.p99": 0,
"jaeger.collector.queue-length.host_jaegerqe-collector-75ddf69996-btpkd": 0,
"jaeger.collector.save-latency.host_jaegerqe-collector-75ddf69996-btpkd.p50": 0,
"jaeger.collector.save-latency.host_jaegerqe-collector-75ddf69996-btpkd.p90": 0,
"jaeger.collector.save-latency.host_jaegerqe-collector-75ddf69996-btpkd.p95": 0,
"jaeger.collector.save-latency.host_jaegerqe-collector-75ddf69996-btpkd.p99": 0,
"jaeger.collector.spans.dropped.host_jaegerqe-collector-75ddf69996-btpkd": 0,
"jaeger.collector.spans.received.debug_false.format_jaeger.svc_other-services": 0,
"jaeger.collector.spans.received.debug_false.format_unknown.svc_other-services": 0,
"jaeger.collector.spans.received.debug_false.format_zipkin.svc_other-services": 0,
"jaeger.collector.spans.received.debug_true.format_jaeger.svc_other-services": 0,
"jaeger.collector.spans.received.debug_true.format_unknown.svc_other-services": 0,
"jaeger.collector.spans.received.debug_true.format_zipkin.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_false.format_jaeger.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_false.format_unknown.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_false.format_zipkin.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_true.format_jaeger.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_true.format_unknown.svc_other-services": 0,
"jaeger.collector.spans.rejected.debug_true.format_zipkin.svc_other-services": 0,
"jaeger.collector.spans.saved-by-svc.debug_false.result_err.svc_other-services": 0,
"jaeger.collector.spans.saved-by-svc.debug_false.result_ok.svc_other-services": 0,
"jaeger.collector.spans.saved-by-svc.debug_true.result_err.svc_other-services": 0,
"jaeger.collector.spans.saved-by-svc.debug_true.result_ok.svc_other-services": 0,
"jaeger.collector.spans.serviceNames.host_jaegerqe-collector-75ddf69996-btpkd": 0,
"jaeger.collector.traces.received.debug_false.format_jaeger.svc_other-services": 0,
"jaeger.collector.traces.received.debug_false.format_unknown.svc_other-services": 0,
"jaeger.collector.traces.received.debug_false.format_zipkin.svc_other-services": 0,
"jaeger.collector.traces.received.debug_true.format_jaeger.svc_other-services": 0,
"jaeger.collector.traces.received.debug_true.format_unknown.svc_other-services": 0,
"jaeger.collector.traces.received.debug_true.format_zipkin.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_false.format_jaeger.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_false.format_unknown.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_false.format_zipkin.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_true.format_jaeger.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_true.format_unknown.svc_other-services": 0,
"jaeger.collector.traces.rejected.debug_true.format_zipkin.svc_other-services": 0,
"jaeger.collector.traces.saved-by-svc.debug_false.result_err.svc_other-services": 0,
"jaeger.collector.traces.saved-by-svc.debug_false.result_ok.svc_other-services": 0,
"jaeger.collector.traces.saved-by-svc.debug_true.result_err.svc_other-services": 0,
"jaeger.collector.traces.saved-by-svc.debug_true.result_ok.svc_other-services": 0,
"jaeger.index_create.attempts": 0,
"jaeger.index_create.errors": 0,
"jaeger.index_create.inserts": 0,
"jaeger.index_create.latency-err.p50": 0,
"jaeger.index_create.latency-err.p90": 0,
"jaeger.index_create.latency-err.p95": 0,
"jaeger.index_create.latency-err.p99": 0,
"jaeger.index_create.latency-ok.p50": 0,
"jaeger.index_create.latency-ok.p90": 0,
"jaeger.index_create.latency-ok.p95": 0,
"jaeger.index_create.latency-ok.p99": 0,
"memstats": {"Alloc":5627408,"TotalAlloc":13742352,"Sys":72546552,"Lookups":0,"Mallocs":116088,"Frees":84866,"HeapAlloc":5627408,"HeapSys":65536000,"HeapIdle":58482688,"HeapInuse":7053312,"HeapReleased":0,"HeapObjects":31222,"StackInuse":1572864,"StackSys":1572864,"MSpanInuse":104728,"MSpanSys":114688,"MCacheInuse":41472,"MCacheSys":49152,"BuckHashSys":1445821,"GCSys":2379776,"OtherSys":1448251,"NextGC":6363040,"LastGC":1552478891249574422,"PauseTotalNs":790153,"PauseNs":[169238,192200,184120,122562,122033,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1552478891182376417,1552478891197629243,1552478891213045217,1552478891234898944,1552478891249574422,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":5,"NumForcedGC":0,"GCCPUFraction":0.010201917081040575,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":4154,"Frees":3230},{"Size":16,"Mallocs":43267,"Frees":31559},{"Size":32,"Mallocs":16012,"Frees":10937},{"Size":48,"Mallocs":9954,"Frees":6719},{"Size":64,"Mallocs":3031,"Frees":1982},{"Size":80,"Mallocs":926,"Frees":364},{"Size":96,"Mallocs":776,"Frees":492},{"Size":112,"Mallocs":4194,"Frees":3372},{"Size":128,"Mallocs":1949,"Frees":776},{"Size":144,"Mallocs":205,"Frees":81},{"Size":160,"Mallocs":3952,"Frees":2762},{"Size":176,"Mallocs":266,"Frees":194},{"Size":192,"Mallocs":81,"Frees":45},{"Size":208,"Mallocs":589,"Frees":362},{"Size":224,"Mallocs":118,"Frees":87},{"Size":240,"Mallocs":33,"Frees":24},{"Size":256,"Mallocs":121,"Frees":61},{"Size":288,"Mallocs":4665,"Frees":3339},{"Size":320,"Mallocs":127,"Frees":91},{"Size":352,"Mallocs":86,"Frees":48},{"Size":384,"Mallocs":209,"Frees":11},{"Size":416,"Mallocs":208,"Frees":165},{"Size":448,"Mallocs":29,"Frees":20},{"Size":480,"Mallocs":13,"Frees":10},{"Size":512,"Mallocs":1400,"Frees":1001},{"Size":576,"Mallocs":2621,"Frees":921},{"Size":640,"Mallocs":1437,"Frees":1005},{"Size":704,"Mallocs":52,"Frees":39},{"Size":768,"Mallocs":10,"Frees":4},{"Size":896,"Mallocs":204,"Frees":127},{"Size":1024,"Mallocs":55,"Frees":44},{"Size":1152,"Mallocs":87,"Frees":63},{"Size":1280,"Mallocs":77,"Frees":34},{"Size":1408,"Mallocs":34,"Frees":25},{"Size":1536,"Mallocs":63,"Frees":60},{"Size":1792,"Mallocs":94,"Frees":69},{"Size":2048,"Mallocs":36,"Frees":32},{"Size":2304,"Mallocs":74,"Frees":17},{"Size":2688,"Mallocs":50,"Frees":26},{"Size":3072,"Mallocs":41,"Frees":23},{"Size":3200,"Mallocs":6,"Frees":1},{"Size":3456,"Mallocs":13,"Frees":13},{"Size":4096,"Mallocs":93,"Frees":60},{"Size":4864,"Mallocs":72,"Frees":63},{"Size":5376,"Mallocs":34,"Frees":18},{"Size":6144,"Mallocs":13,"Frees":10},{"Size":6528,"Mallocs":6,"Frees":1},{"Size":6784,"Mallocs":6,"Frees":4},{"Size":6912,"Mallocs":0,"Frees":0},{"Size":8192,"Mallocs":14,"Frees":6},{"Size":9472,"Mallocs":30,"Frees":1},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":0,"Frees":0},{"Size":10880,"Mallocs":3,"Frees":2},{"Size":12288,"Mallocs":10,"Frees":5},{"Size":13568,"Mallocs":2,"Frees":2},{"Size":14336,"Mallocs":1,"Frees":1},{"Size":16384,"Mallocs":12,"Frees":2},{"Size":18432,"Mallocs":2,"Frees":1},{"Size":19072,"Mallocs":1,"Frees":0}]}
}
```

**Comment by jkandasa** [comment]
@objectiser I guess I found the root cause, actually I change `metrics-backend: expvar` in all services, to get json output for reporting. So metrics exposed as json format. Does this cause this issue?

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    options:
      metrics-backend: expvar
      collector:
        num-workers: "50"
        queue-size: "2000"
      es:
        bulk:
          size: "5000000"
          workers: "1"
          flush-interval: "200ms"
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    options:
      metrics-backend: expvar
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    options:
      metrics-backend: expvar
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```

**Comment by objectiser** [comment]
@jkandasa yeah just tried it aswell, and it is still on the http port - must have just been a discussion I was thinking about.

**Comment by objectiser** [comment]
@jkandasa I believe the operator would be expecting metrics in prometheus format.

**Comment by jkandasa** [comment]
@objectiser I switch to prometheus format, but still collector and query pod get restarts.
metric file: [collector.txt](https://github.com/jaegertracing/jaeger-operator/files/2961452/collector.txt)
operator log: 
[jaeger-operator-545c69455d-xzgvl.log](https://github.com/jaegertracing/jaeger-operator/files/2961457/jaeger-operator-545c69455d-xzgvl.log)

**Comment by objectiser** [comment]
@jkandasa Is it possible to get the logs from the jaeger-query/collector?

**Comment by jkandasa** [comment]
@objectiser 

Please have a look in [jaeger-service-log.txt](https://github.com/jaegertracing/jaeger-operator/files/2961830/jaeger-service-log.txt)

**Comment by objectiser** [comment]
Have reproduced the issue - still narrowing down the cause, but found that a simplified CR worked ok:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    image: jaegertracing/jaeger-collector:1.11
  query:
    image: jaegertracing/jaeger-query:1.11
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```
Will report back when have identified the underlying cause - but would be good if you could also try this simplified CR to see if it works for you.

**Comment by objectiser** [comment]
@jkandasa Seems like the issue is around the `es.bulk.size` property, but will need to take another look tomorrow - but in the meantime if you could try the following:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    options:
      es:
        bulk:
          workers: 1
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    options:
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```
