### ISSUE TITLE
Queries to self provisioned Elasticsearch are slow resulting in UI timeouts

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#310]
Steps to reproduce,

* Install jaeger services with the following CR,
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    options:
      metrics-backend: prometheus
      collector:
        num-workers: "50"
        queue-size: "2000"
      es:
        bulk:
          size: "5000000"
          workers: "1"
          flush-interval: "200ms"
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    options:
      metrics-backend: prometheus
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    options:
      metrics-backend: prometheus
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
* launch jaeger UI and select a service(example: `jaeger-query`)
* click on `Find Traces` often, throws "HTTP Error: Search service failed: no available connection: no Elasticsearch node available",

![image](https://user-images.githubusercontent.com/1004403/54219279-3a85fc80-4515-11e9-97c2-a8fc3767b4a9.png)

Log files:
* jaeger-query: [jaegerqe-query-84ddcc9654-kph2f_jaeger-query.log](https://github.com/jaegertracing/jaeger-operator/files/2961995/jaegerqe-query-84ddcc9654-kph2f_jaeger-query.log)
* jaeger-agent: [jaegerqe-query-84ddcc9654-kph2f_jaeger-agent.log](https://github.com/jaegertracing/jaeger-operator/files/2961997/jaegerqe-query-84ddcc9654-kph2f_jaeger-agent.log)
* jaeger-collector: [jaegerqe-collector-6976478cc5-54ngv.log](https://github.com/jaegertracing/jaeger-operator/files/2961998/jaegerqe-collector-6976478cc5-54ngv.log)
* elasticsearch-clientdatamaster-0-1: [elasticsearch-clientdatamaster-0-1-9b575665-pfrgb_elasticsearch.log](https://github.com/jaegertracing/jaeger-operator/files/2961999/elasticsearch-clientdatamaster-0-1-9b575665-pfrgb_elasticsearch.log)
* elasticsearch-clientdatamaster-0-1 proxy: [elasticsearch-clientdatamaster-0-1-9b575665-pfrgb_proxy.log](https://github.com/jaegertracing/jaeger-operator/files/2962005/elasticsearch-clientdatamaster-0-1-9b575665-pfrgb_proxy.log)
Other files: [other files.zip](https://github.com/jaegertracing/jaeger-operator/files/2962014/other.files.zip)
