### ISSUE TITLE
Argument order gets changed causing a collector re-deployment

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#334]
Affected services: Jaeger-collector, Jaeger-query

Issue 1:  
   When we deploy jaeger services by the operator, immediate redeploy is happening 
Issue 2: 
   Jaeger services get redeployed by the operator in a random interval (approx: 10 minutes)

CR:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 4
    image: jaegertracing/jaeger-collector:1.11
    options:
      log-level: debug
      metrics-backend: expvar
      collector:
        num-workers: 50
        queue-size: 20000
      es:
        bulk:
          size: 5000000
          workers: 10
          flush-interval: 200ms
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    options:
      log-level: debug
      metrics-backend: expvar
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    options:
      log-level: debug
      metrics-backend: expvar
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```

##### logs:
* [jaeger-operator.log](https://github.com/jaegertracing/jaeger-operator/files/2986856/operator.log)
* [watch-pods.log](https://github.com/jaegertracing/jaeger-operator/files/2986859/watch-pods.log)
* [query.log](https://github.com/jaegertracing/jaeger-operator/files/2986876/query.log)
* [collector.log](https://github.com/jaegertracing/jaeger-operator/files/2986881/collector.log)

Similar issue: https://github.com/jaegertracing/jaeger-operator/issues/307
