### ISSUE TITLE
Resource limits not applied for jaeger-agent sidecar

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#342]
I applied resource limits for all the services. Limits applied for collector and query service.
But limits not applied for jaeger-agent sidecar.

![image](https://user-images.githubusercontent.com/1004403/54763571-3b591580-4c1c-11e9-8f67-c6cf28dc1ad1.png)

[query-pod-describe.txt](https://github.com/jaegertracing/jaeger-operator/files/2992764/query-pod-describe.txt)

My CR:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "1Gi"
    options:
      log-level: debug
      metrics-backend: expvar
      collector:
        num-workers: 100
        queue-size: 20000
      es:
        bulk:
          size: 500000
          workers: 50
          flush-interval: 220ms
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: debug
      metrics-backend: expvar
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: debug
      metrics-backend: expvar
      processor:
        jaeger-compact:
          server-queue-size: 100000
          workers: 101
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```
