### ISSUE TITLE
Failed to deploy es cluster

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#358]
Tried to deploy ES cluster via elasticsearch-operator from jaeger-operator.
Jaeger-operator failed to deploy and throws the following error,
```
time="2019-04-03T15:39:22Z" level=error msg="failed to apply the changes" error="no matches for kind \"Elasticsearch\" in version \"logging.openshift.io/v1alpha1\"" execution="2019-04-03 15:39:17.005511739 +0000 UTC" instance=jaegerqe namespace=openshift-logging
```

CR File:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 20
        queue-size: 20000
      es:
        bulk:
          size: 1048576
          workers: 1
          flush-interval: 200ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 5000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```

jaeger-operator log: [jaeger-operator.log](https://github.com/jaegertracing/jaeger-operator/files/3039807/jaeger-operator.log)

Rootcause maybe: There is a [recent change](https://github.com/openshift/elasticsearch-operator/blob/master/manifests/04-crd.yaml#L14) in ES operator. Jaeger-operator needs to be updated to [this change](https://github.com/openshift/elasticsearch-operator/blob/master/manifests/04-crd.yaml#L14).
