### ISSUE TITLE
Operator fails to deploy es-cluster 

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#365]
If we deploy jaeger services with es-cluster creation, failing with following error,
```
time="2019-04-05T11:01:46Z" level=error msg="failed to apply the changes" error="no kind is registered for the type v1.ElasticsearchList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:61\"" execution="2019-04-05 11:01:46.431175724 +0000 UTC" instance=jaegerqe namespace=openshift-logging
```

Jaeger Operator log file: [jaeger-operator-545c69455d-nw8cx.log](https://github.com/jaegertracing/jaeger-operator/files/3047603/jaeger-operator-545c69455d-nw8cx.log)

CR File:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 20
        queue-size: 100000
      es:
        bulk:
          size: 524288
          workers: 3
          flush-interval: 1000ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 100000
          workers: 1000
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
