### ISSUE TITLE
collector failed to connect to ES cluster(the auto-provisioning)

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#368]
Collector service keeps on failing. When we using auto-provisioning ES cluster
Image: `jaegertracing/jaeger-operator:master`

Collector log: [jaegerqe-collector-865f744799-clz2c.log](https://github.com/jaegertracing/jaeger-operator/files/3054459/jaegerqe-collector-865f744799-clz2c.log)
ES instance log: 
[elasticsearch-cdm-396ldl7m-1-7694b6dcf5-92kfd_proxy.log](https://github.com/jaegertracing/jaeger-operator/files/3054464/elasticsearch-cdm-396ldl7m-1-7694b6dcf5-92kfd_proxy.log)
[elasticsearch-cdm-396ldl7m-1-7694b6dcf5-92kfd_elasticsearch.log](https://github.com/jaegertracing/jaeger-operator/files/3054465/elasticsearch-cdm-396ldl7m-1-7694b6dcf5-92kfd_elasticsearch.log)

![image](https://user-images.githubusercontent.com/1004403/55727415-97e76d80-5a2f-11e9-9ff1-15883652aa1a.png)

CR:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 20
        queue-size: 100000
      es:
        bulk:
          size: 524288
          workers: 3
          flush-interval: 1000ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 100000
          workers: 1000
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
