### ISSUE TITLE
if es-index-cleaner job fails, keep on creating new jobs for a random number of times

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#418]
if `es-index-cleaner` job fails, keep on creating new jobs for a random number of times
**NOTE:** this issue happens for `spark-dependencies` job too(on failure).

![image](https://user-images.githubusercontent.com/1004403/57859789-40e46d80-7811-11e9-9ea4-2fae938d79e0.png)

CR file:
```yaml:
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true
      schedule: "*/10 * * * *"
      completedTTL: 1200
    elasticsearch:
      nodeCount: 3
      resources:
```

Image ID: docker-pullable://docker.io/jaegertracing/jaeger-es-index-cleaner@sha256:b9331c7a0e10c29d1a728df9c70aaf1e4f9fff8fc86a284bcec4d6c2ae0934b7
