### ISSUE TITLE
Expose collector/agent outside of the cluster

### ISSUE THREAD

**Issue by atmosx** [jaegertracing/jaeger-operator#420]
Hello! I'd like to ask if collector service type and annotations are accessible through the config, e.g.:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  collector:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        external-dns.alpha.kubernetes.io/hostname: "my.hostname.com"
      type: LoadBalancer
```

The above config doesn't work, I don't see `annotations` or `type` to `collector` service.

Ty!
