### ISSUE TITLE
Sidecar injection - Do I need to restart deployment?

### ISSUE THREAD

**Issue by pzheng64** [jaegertracing/jaeger-operator#427]
I'm working on creating customized version of Helm chart for deploying Jaeger operator and instance to my cluster.

When I do sidecar injection in the following order, the `jaeger` resources (jaeger-query, jaeger-collector, jaeger-agent) are not created.
- Existing deployment has already annotation `"sidecar.jaegertracing.io/inject": "jaeger"`
- Install Jaeger operator and an instance (name=jaeger) using Helm chart.
  https://github.com/helm/charts/tree/master/stable/jaeger-operator
- Create a Jaeger instance using all-in-one.yaml.

It does not create services in the target namespace of Jaeger instance. Should I switch to Jaeger DaemonSet for this purpose?

**Comment by objectiser** [comment]
@pzheng64 I tried installing a Jaeger instance using the referenced helm chart with these steps:
```
minikube start --vm-driver kvm2 --memory 16384 --cpus 8
helm init
kubectl create ns observability
helm install stable/jaeger-operator --name jaeger --namespace observability
kubectl apply -f simplest.yaml 
```
where `simplest.yaml` is found [here](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml).
However the final step produced this error:
```
error: unable to recognize "deploy/examples/simplest.yaml": no matches for kind "Jaeger" in version "jaegertracing.io/v1"
```
Did you see this error? It would explain why the query, collector, etc are not being created?

If so, then you will need to create an issue against the helm chart.

In terms of ordering - I believe the sidecar injected agent would only occur if the operator was already installed before the app with the label was deployed. @jpkrohling can confirm.

**Comment by pzheng64** [comment]
```
  apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    name: jaeger
  spec:
    strategy: allInOne
    allInOne:
      image: jaegertracing/all-in-one:latest
      options:
        log-level: debug
    storage:
      type: memory 
      options:
        memory:
          max-traces: 100000
    ingress:
      enabled: false
```
I have applyed the above YAML after installed Jaeger-operator, but I could not find the service `jaeger-query` and `jaeger-collector`.  It is said that all-in-one strategy is for running all the services inside single executable, but I don't quite get it.
Here is the custom ingress YAML I added for jaeger-query:
```
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: jaeger-query
    namespace: jx-staging # My namespace
  spec:
    rules:
    - host: jaeger-ui.k8.devfactory.com  # My domain for Jager UI
      http:
        paths:
        - path: /
          backend:
            serviceName: jaeger-query # Look here
            servicePort: 16686
```
Notice `serviceName: jaeger-query` here.  As I can't see the service `jaeger-query` running in my namespace, it does not show UI.

In a word, my question is:
- Does all-in-one strategy create services for jaeger-query and jaeger-collector?
- What is jaeger-zipkin used for?  I thought Zipkin is just an alternative for Jaeger, so confused about this.
- What can I do to re-inject into an existing deployment where sidecar injection was done before? As the deployment YAML definition shows `jaeger-agent` container inside it, I don't know how to remove it.
