### ISSUE TITLE
Custom annotation/labels

### ISSUE THREAD

**Issue by arnitolog** [jaegertracing/jaeger-operator#439]
Hello,

is there any way to set custom annotation and label for kind:Ingress. I need to do this in order to provide a type of the ingress controller and type of traffic (internal/external) to our kubernetes cluster.

**Comment by objectiser** [comment]
You can define annotations against the ingress:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-ingress
spec:
  ingress:
    annotations:
      key1: value1
```
However currently labels are not configurable. Could you provide an example of the type of annotations/labels you are looking to provide? Are they specific to your use case or generally required?
