### ISSUE TITLE
OpenShift OAuth Proxy not logging out users on login page?

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#447]
In Kiali, an issue has been reported that the OpenShift OAuth Proxy isn't logging users out when the login page is opened. We also use this approach in Jaeger, so, we might also be affected.

@jkandasa: we need to add this scenario to the test case list. Once you can confirm we are affected by this bug, I'll change this issue from `question` to `bug`.

**Comment by jkandasa** [comment]
@jpkrohling I enabled OpenShift’s OAuth service in Jaeger and performed the following actions.
Seems all looks ok. and authentication works well.

Browser: Google Chrome, Version 74.0.3729.157 (Official Build) (64-bit)
OpenShift Master: v3.11.98
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.98

I believe this issue might be reported in OpenShift 4.x in Kiali?

Test 1:
* login with Openshift credentials
* list traces
* clicked logout
* tried to open (https://jaegerqe-<private>.redhat.com/)
* redirected to login page as shown here,
![image](https://user-images.githubusercontent.com/1004403/58550237-f4def300-822a-11e9-8032-ec46845280a8.png)

Test 2:
* login with Openshift credentials
* list traces
* Opened new tab (https://jaegerqe-<private>.redhat.com/) and lists traces
* clicked logout on first tab
* list traces on the second tab throws an error

![image](https://user-images.githubusercontent.com/1004403/58550444-5a32e400-822b-11e9-89ff-46b042114659.png)

CR file: 
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  strategy: production
  collector:
    replicas: 1
    image: docker.io/jaegertracing/jaeger-collector:1.12
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 1
        queue-size: 20000
      es:
        bulk:
          size: 524288
          workers: 3
          flush-interval: 50ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: docker.io/jaegertracing/jaeger-query:1.12
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: docker.io/jaegertracing/jaeger-agent:1.12
    resources:
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 10000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
