### ISSUE TITLE
Support custom annotations/labels

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#45]
We should provide a way for admins to label the resources that are being created. Something like:

```yaml
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simple-prod
  labels:
    tenant: acme
spec:
  strategy: all-in-one
  all-in-one:
    annotations:
      prometheus.io/scrape: "false"
```

Note that some labels/annotations might clash with the ones we supply in the operator itself, like the prometheus ones. Because of that, we should always honor what the user specified in the CR.
