### ISSUE TITLE
CR "metadata.name" invalid format should throw exception on the user console

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#466]
When a user supplies unsupported `metadata.name` Jaeger operator should throw an exception on user console.

```
$ oc create -f jaeger-services-final.yaml 
jaeger.jaegertracing.io/jaegerqe.test created
```

Current flow: 
* deploys ES cluster 
* try to deploy jaeger services(throws an exception on the jaeger-operator log)

Expected flow:
* validate CR file
* continue to deploy if the user supplied a valid CR file.

Operator log: [jaeger-operator-545c69455d-j7zjg.log](https://github.com/jaegertracing/jaeger-operator/files/3264602/jaeger-operator-545c69455d-j7zjg.log)

CR file:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: "jaegerqe.test"
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.12
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 1
        queue-size: 20000
      es:
        bulk:
          size: 524288
          workers: 1
          flush-interval: 200ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.12
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.12
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 10000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
