### ISSUE TITLE
CR file invalid chars/failures should be reported on the console

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#467]
This issue somehow related to #466, however this may need a different fix

Invalid CR files error should be reported to the user console. And should not keep on trying to deploy the CR file.

I changed the boolean value to string (eg: `true >> "true"`) and integer to string (ex: `10 >> "10"`)
deployed the CR file. on the console, it looks all ok. But on the operator-log keep on throwing an exception.

Expected behavior:
* The error should be thrown on the user console [OR] the client side
* AFAIK, There is no use to keep on trying to deploy the invalid CR file. Stop it on the first failure
* I believe if we read everything as a string and convert it to the specific format may avoid most of the format issues.

No exception on the console.
```
$ oc create -f jaeger-services-final.yaml 
jaeger.jaegertracing.io/jaegerqe created
```

```yaml
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true
      schedule: "*/10 * * * *"
      numberOfDays: "2"
```

operator log file: [jaeger-operator-545c69455d-4clq5.log](https://github.com/jaegertracing/jaeger-operator/files/3264686/jaeger-operator-545c69455d-4clq5.log)

CR file:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: "jaegerqe"
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.12
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 1
        queue-size: 20000
      es:
        bulk:
          size: 524288
          workers: 1
          flush-interval: 200ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.12
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: "info"
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.12
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 10000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true
      schedule: "*/10 * * * *"
      numberOfDays: "2"      
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```
