### ISSUE TITLE
Connect to cassandra with credentials

### ISSUE THREAD

**Issue by mfrembs** [jaegertracing/jaeger-operator#469]
Hello,

I'm trying to use jaeger with cassandra. Cassandra is secured by username and password. When I try to create a jaeger instance with the jaeger operator, jaeger cannot connect to cassandra. I get the following error message / logs:

`Connection error: ('Unable to connect to any servers', {'IP': AuthenticationFailed('Remote end requires authentication.',)})
Cassandra is still not up at jaeger-cassandra.cassandra-system.svc.cluster.local. Waiting 1 second.`

I use the following configuration:
```apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cass-test
spec:
  strategy: production
  storage:
    type: cassandra
    options:
      cassandra:
        servers: jaeger-cassandra.cassandra-system.svc.cluster.local
        username: cassandra
        password: ***
        keyspace: jaeger_v1_datacenter3
  ingress:
    enabled: true´´´

How is the correct configuration with username and password for cassandra?

**Comment by pavolloffay** [comment]
Hi @mfrembs the username/pass configuration looks good. Try adding configuration for create schema script

**Comment by mfrembs** [comment]
Thanks. I tried that with no luck. Here is the full configuration, the error message remains the same:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cass-test
spec:
  strategy: production
  storage:
    type: cassandra
    options:
      cassandra:
        servers: jaeger-cassandra.cassandra-system.svc.cluster.local
        username: cassandra
        password: ***
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      datacenter: "datacenter3"
      mode: "test"
  ingress:
    enabled: true
```

I used the bitnami/cassandra helm chart for the cassandra deployment. The installation should be fine.

```
kubectl exec -it --namespace cassandra-system $(kubectl get pods --namespace cassandra-system -l app=cassandra,release=jaeger -o jsonpath='{.items[0].metadata.name}') nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.100.104.169  189.7 KiB  256          100.0%            4ed75cef-f43f-423e-ab2e-fe4b9c8668bf  rack1
```

I also tried configurations with datacenter1 on jaeger-side.

**Comment by pavolloffay** [comment]
what is the result of create schema script? Did it create the schema?

**Comment by mfrembs** [comment]
I don't know if the create schema script was issued. How can i check this? I can only see the following pod:

```
kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
cass-test-cassandra-schema-job-wp577              1/1     Running   0          12s
```

I also tried to create a keyspace manually in cassandra (named jaeger_v1_datacenter1). I used this and "datacenter1" for keyspace and datacenter in the Jaeger-yaml.

**Comment by pavolloffay** [comment]
`cass-test-cassandra-schema-job-wp577  ` is the schema creation pod. Check the output for details. It should indicate that schema has been created.

**Comment by mfrembs** [comment]
```
kubectl logs cass-test-cassandra-schema-job-glmjk
Connection error: ('Unable to connect to any servers', {'10.200.39.151': AuthenticationFailed('Remote end requires authentication.',)})
Cassandra is still not up at jaeger-cassandra.cassandra-system.svc.cluster.local. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'10.200.39.151': AuthenticationFailed('Remote end requires authentication.',)})
Cassandra is still not up at jaeger-cassandra.cassandra-system.svc.cluster.local. Waiting 1 second.
[...]
``` 

(I created a new pod because the old one gets deleted after a short time)

**Comment by pavolloffay** [comment]
Can you please paste here description of the pod? It seems user/pass are not passed to the create schema job, so it fails to init the database and then jaeger components fail to connect to it.

**Comment by pavolloffay** [comment]
It seems that schema script does not support user/pass parameters https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/docker.sh. First the `docker.sh` has to support it in order to add it to the operator.

would you be interested in submitting a patch for it?

**Comment by mfrembs** [comment]
Thanks for looking into that! Unfortunately I don't have the time to submit a patch :-( I would be happy if someone would implement it. Otherwise I have to check if it is possible to use cassandra without credentials (it is inside a K8s cluster. Maybe it is possible) or switch to elasticsearch.

I let the the issue open in case someone want to overtake it?

**Comment by arpitjindal97** [comment]
The issue could be related to schema.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: cass-test
spec:
  strategy: production
  storage:
    type: cassandra
    options:
      cassandra:
        servers: jaeger-cassandra.cassandra-system.svc.cluster.local
        username: cassandra
        password: ***
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      datacenter: "datacenter3"
      mode: "test"
  ingress:
    enabled: true
```

In above yaml, `cassandraCreateSchema` will create schame `jaeger_v1_test` by default. But, Collector will correctly pick the value specified from yaml i.e. `jaeger_v1_datacenter3`

There is a PR #837 which will fix this issue. 

`cassandraCreateSchema` will then pick `storage.options.cassandra.keyspace` from yaml.

As a workaround, You have to deploy schema creation Job manually passing the keyspace as `jaeger_v1_datacenter3` and disable `cassandraCreateSchema` from above yaml
