### ISSUE TITLE
"sidecar.jaegertracing.io/inject": "true" annotation causes two pods to be started

### ISSUE THREAD

**Issue by marcindulak** [jaegertracing/jaeger-operator#477]
I have jaeger-operator 2.6.0 installed with helm https://github.com/helm/charts/commit/0007ebb1587b3858c0bfb25a2210824a86434d3f
that provides `jaegertracing/jaeger-operator:1.12.0`.

Elasticsearch is a single container

```
kubectl create namespace observability
kubectl -n observability run elasticsearch --image=docker.elastic.co/elasticsearch/elasticsearch:6.7.2 --env="discovery.type=single-node" --port=9200
kubectl -n observability expose deployment elasticsearch --type=ClusterIP --name=elasticsearch
```

The jaeger `1.12` components are installed in the `observability` namespace:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-elasticsearch
  namespace: observability
spec:
  agent:
    #strategy: DaemonSet  # inject jaeger-agent as a sidecar
    options:
      log-level: debug
  ingress:
    enabled: false
  resources:
    limits:
      memory: 192Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
  strategy: production
```

```
kubectl -n observability get pod -l app=jaeger -oyaml | grep "image:" | sort | uniq
      image: jaegertracing/jaeger-agent:1.12
      image: jaegertracing/jaeger-collector:1.12
      image: jaegertracing/jaeger-query:1.12
```

The jaeger-agent sidecar is injected in the deployments in the `observability` namespace.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-elasticsearch
  name: nginx-deployment
  namespace: production  # sidecar injected in observability namespace
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

however, two pods are started, with one, short-lived single-container pod is terminated quickly

```
kubectl -n observability apply -f deployment.yaml
kubectl -n observability get pod
NAME                                              READY     STATUS        RESTARTS   AGE
elasticsearch-c46d956fb-rgdtj                     1/1       Running       1          3h
jaeger-elasticsearch-collector-76f485d9d8-w66r4   1/1       Running       4          1h
jaeger-elasticsearch-query-d9fdbf68f-g9np5        2/2       Running       4          1h
jaeger-operator-7bb8f65994-6zj22                  1/1       Running       3          4h
nginx-deployment-669bbd857-5qv5c                  2/2       Running       0          1s
nginx-deployment-75675f5897-8dbzg                 1/1       Terminating   0          1s
```

Is this the expected behaviour?
```
