### ISSUE TITLE
[Question] Disable es index cleaner job 

### ISSUE THREAD

**Issue by cfontes** [jaegertracing/jaeger-operator#488]
Is there a way to completelly disable it?  I've searched in the operator but couln't find an option to skip it's deploy.

We recreate our cluster every morning and we have unlimited storage for Jaeger, I would like to disable this so I don't have to worry about it.

**Comment by cfontes** [comment]
Nevermind, just found it in the code

Just in case someone needs it you disable it like this:

```
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
```
