### ISSUE TITLE
Spark Dependencies & ES-Index-cleaner ImagePullBackoff

### ISSUE THREAD

**Issue by jungopro** [jaegertracing/jaeger-operator#499]
Hi

Both pods are in ImagePullBackOff

Reason: trying to pull the images from a private repo with no success. The error is: `pod is waiting to start: trying and failing to pull images`
The standard Jaeger components (query, controller) are using a pre-defined service account with an attached imagePullSecret, but I think the es components don't pick up the same account.
I tried various ways to "push" the `serviceAccount` configuration to the es components as well but post-deployment, I don't see any `serviceAccount` in the specs of the `cronJob, Job or Pod`:

_(since I'm in a dark site with no internet, I only added the config parts which I believe are relevant)_

```yaml
kind: jaeger
spec:
  strategy: production
  serviceAccount: my-service-account
storage:
  serviceAccount: my-service-account
  type: elasticsearch
  options:
    es:
  dependencies:
    image: privaterepo/dependencies:latest
  esIndexCleaner:
    image: privaterepo/cleaner:1.12.0
```

How do I configure the use of a custom serviceaccount / imagepullsecret to pull the es-related images from a private repo?

Thank you

Omer

**Comment by jpkrohling** [comment]
We currently do not have support for custom image pull secret, even though we talked about that (#80), and even got a PR lined up (#404). I think your use case is valid and we might indeed need support for that. @objectiser might add this to our queue, but it probably won't be done in the next couple of weeks. If you can send a PR (#404 can serve as a starting point), we can probably merge it very soon.

**Comment by jungopro** [comment]
Hi @jpkrohling 
Thanks for all the hard work, really appreciate it.
Honestly, I was trying to follow the changes and PRs and I'm unclear as to what was implemented and if there is a new flow one should follow to implement it

Can you provide a simple example maybe?

Thank you
Omer

**Comment by jpkrohling** [comment]
Sure: you can either set the "serviceAccount" node to the top-level:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customsa
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: custom-serviceaccount
spec:
  serviceAccount: customsa # this is created and managed externally to the operator
```

Or specific to a component, such as the Agent:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: agent-as-daemonset
spec:
  agent:
    strategy: DaemonSet
    serviceAccount: jaeger-agent-daemonset
```

Or, you can omit the `serviceAccount` properties and let the Operator create/manage them for you. Once the accounts are created, you can then `kubectl edit serviceaccount customsa` and add your custom `ImagePullSecrets` to it. The operator should not override this property anymore (starting from the next release).
