### ISSUE TITLE
ES AutoProvisioner Should Work With Elastic Operator

### ISSUE THREAD

**Issue by youngnicks** [jaegertracing/jaeger-operator#518]
The Elasticsearch auto provisioner should work with [Elastic's Operator](https://github.com/elastic/cloud-on-k8s). Currently the Jaeger Operator is setting the `es-provision` flag to false even though the Elastic Operator is installed.

The check to see if the operator is available is looking for `apiGroups[i].Name == "logging.openshift.io"`.

To be more flexible, I believe it should be looking for `apiGroups[i].Kind == "Elasticsearch"`.

**Comment by jpkrohling** [comment]
That's a great idea. I don't think it's that easy, as the CRs are probably not that compatible, but we would certainly welcome a PR to add support to it.

Here's how the CR for ECL's OpenShift looks like: https://github.com/jaegertracing/jaeger-operator/blob/1dfbda696644aaed751bf7de64791cb4d727eda2/pkg/storage/elasticsearch.go#L133-L158

Before implementing this, I'd suggest sharing your plan here in this issue, so that we can agree on a strategy. If well implemented, this could be a great way to add further auto-provisioning schemes, especially now that Jaeger supports external storage plugins.

**Comment by youngnicks** [comment]
According to the [Elastic Documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html#k8s-persistent-storage), here is what is needed to create a persisted Elasticsearch cluster with the Elastic Operator. The `volumeClaimTemplates` section is optional.

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: jaeger
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        #storageClassName: standard # can be any available storage class
```

When I get some spare time, I'll try and think of a pluggable solution. If someone else gets to this before me, I won't be offended :)
