### ISSUE TITLE
Monitoring Jaeger

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#538]
Opening this in the Operator repository instead of the main repo, as the outcome might involve changes to the operator.

Currently, the Jaeger Operator adds some annotations to the Jaeger deployments it creates (Collector, Agent's DaemonSet, Query), like:

https://github.com/jaegertracing/jaeger-operator/blob/83aafae113f63c2bf4808c44471f610dbe38d5ee/pkg/deployment/all-in-one.go#L48-L53

While this works out of the box with the Prometheus instance brought by Istio, it requires extra configuration when the [Prometheus Operator](https://github.com/coreos/prometheus-operator) is used, even with [kube-prometheus](https://github.com/coreos/kube-prometheus).

Right now, the only way I could get it working with Prometheus from `kube-prometheus` is by manually creating a `ServiceMonitor` resource, with an accompanying extra `Service` (with `simplest` as the Jaeger instance):

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest-collector
    app.kubernetes.io/part-of: jaeger
  name: simplest-collector-monitoring
  namespace: monitoring
spec:
  ports:
  - name: admin-http
    port: 14269
    protocol: TCP
    targetPort: 14269
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest
    app.kubernetes.io/part-of: jaeger
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simplest-pm
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: admin-http
  selector:
    matchLabels:
      app: jaeger
```

Questions:

- Is the current state enough? Is it acceptable to ask users to create a `Service` + `ServiceMonitor` in order to monitor Jaeger with `kube-prometheus`? 
- Should we create an extra service automatically? Should we create a `ServiceMonitor` automatically if the CRD is present in the cluster?
- @objectiser mentioned that Istio [is transitioning to Prometheus Operator](https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml), so, a properly configured `ServiceMonitor` could be sufficient, without requiring an extra service

**Comment by metalmatze** [comment]
>  @objectiser mentioned that Istio is transitioning to Prometheus Operator, so, a properly configured ServiceMonitor could be sufficient, without requiring an extra service

If the Service is shipped with Isitio in the future, then yes, you might not need to create that, but you obviously need _some_ Service to use ServiceMonitors. 

As a user, I'd probably would be fine with adding a ServiceMonitor manually for now, given you provide and example. That's pretty much how the entire kube-prometheus project works.

**Comment by objectiser** [comment]
If we can get it to work, looks like PodMonitors would be better, as would enable scraping of sidecars (e.g. jaeger agent) - based on discussion here: https://discuss.istio.io/t/prometheus-operator-podmonitor/2695

**Comment by metalmatze** [comment]
Yes. Indeed, if you would only need the Service for metrics and for nothing else, then you can skip that step with PodMonitors now. Make sure you have Prometheus Operator v0.31+ available, before starting to work on that.

**Comment by jpkrohling** [comment]
With the help from @metalmatze, I was able to get `PodMonitor` working, once a fix similar to https://github.com/coreos/kube-prometheus/pull/159 was applied. 

We have then two ways to monitor Jaeger:

1. When Istio is present, it builds the proper configuration to scrape data out of Jaeger based on the pod annotations
1. Manually creating a `PodMonitor` like the following:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: simplest
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - interval: 5s
    port: "admin-http"
  selector:
    matchLabels:
      app: jaeger
```

Right now, there's no action to be taken from the Jaeger Operator's perspective, so, I'm closing this one.
