### ISSUE TITLE
Option values for storage breaks after update

### ISSUE THREAD

**Issue by Demonian** [jaegertracing/jaeger-operator#551]
HI,

I have encountered strange behavior if `options` for storage are set in two ways (flat structure with dot as a key and normal yaml structure) in the same `Jaeger` manifest.
E.g.:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
  namespace: istio-system
spec:
  ingress:
    enabled: false
  allInOne:
    options:
      query:
        base-path: /jaeger
  strategy: allInOne
  storage:
    type: cassandra
    cassandraCreateSchema:
      enabled: false
    options:
      # should set this key like this because it is impossible to enable `tls` if yaml structure for
      # for options is used
      cassandra.tls: true  
      cassandra:
        servers: cassandra.default.svc.cluster.local
        port: 9042
        keyspace: zipkin_traces
        tls:
          ca: {some value}
          cert: {some value}
          key: {some value}
          server-name: jaeger
          verify-host: false
```
**STR:**
1. Apply manifest with structure above.
2. Wait until operator will create `jaeger-tracing` deployment
3. Investigate applied `Jaeger` manifest with `kubectl get jaeger jaeger-tracing -o yaml --export` you will see smth like this:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  annotations:
{many other keys here}
    options:
      cassandra.keyspace: zipkin_traces
      cassandra.port: 9042
      cassandra.servers: cassandra.default.svc.cluster.local
      cassandra.tls: true
      cassandra.tls.ca: {some value}
      cassandra.tls.cert: {some value}
      cassandra.tls.key: {some value}
      cassandra.tls.server-name: jaeger
      cassandra.tls.verify-host: false
```
4. At this point everything looks fine. Now lets change this value:
```
  options:
     cassandra:
       tls:
         verify-host: true
```
5. Apply new manifest with changed value of `verify-host`
6. Investigate changed `Jaeger` manifest with `kubectl get jaeger jaeger-tracing -o yaml --export`, now we will see that the structure is broken and there it is inconsistent now:
```
options:
      cassandra:
        keyspace: zipkin_traces
        port: 9042
        servers: cassandra.default.svc.cluster.local
        tls:
          ca: {some value}
          cert: {some value}
          key: {some value}
          server-name: jaeger
          verify-host: true
      cassandra.keyspace: zipkin_traces
      cassandra.port: "9042"
      cassandra.servers: cassandra.default.svc.cluster.local
      cassandra.tls: true
      cassandra.tls.ca: {some value}
      cassandra.tls.cert: {some value}
      cassandra.tls.key: {some value}
      cassandra.tls.server-name: jaeger
      cassandra.tls.verify-host: "false"
```

The only possible way to fix this is to delete manifest and reapply it again.

**Workaround:**
If all keys will be written in flat structure (with dot) there will be no problem.

**Expected Result**
There should be ability to enable `tls` with normal yaml structure of keys. 

**Proposal**
1. If yaml structure of keys is used we need to set `tls` to true if this key exists in manifest.
2. Do not change the structure of keys in `Jaeger` manifest after operator parsing it.
3. Merge old and new values (the hardest way, because it will be hard to analyze what value is new)
