### ISSUE TITLE
Resource Limits for Jaeger allInOne

### ISSUE THREAD

**Issue by clyang82** [jaegertracing/jaeger-operator#562]
I saw the example of all-in-one, there has defined `max-traces: 100000`. what is proposed memory limits for allInOne? considering the memory occupation of 100000 traces, jaeger query and jaeger collector, etc. Thanks.

```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.13
    options:
      log-level: debug
      query:
        base-path: /jaeger
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking: 
        gaID: UA-000000-2
      menu:
        - label: "About Jaeger"
          items:
            - label: "Documentation"
              url: "https://www.jaegertracing.io/docs/latest"
  storage:
    options:
      memory:
max-traces: 100000
```

/cc @jpkrohling @objectiser I did not find such data after searched the document and issues. Do you have such data? Thanks.
