### ISSUE TITLE
How to connect to a ES cluster that is TLS/authentication enable?

### ISSUE THREAD

**Issue by eroji** [jaegertracing/jaeger-operator#591]
I can't seem to find any documentation on how to leverage the jaeger-operator to create an instance using a secured ES cluster that is TLS and authentication enabled. Can someone provide some guidance on how to get this to work? This is what I have right now. Furthermore, the cleaner job will also need to be able to authenticate. The URL for ES is https://jaeger-es-http:9200 using a self-signed cert.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://jaeger-es-http:9200
    esIndexCleaner:
      enabled: true
      numberOfDays: 30
      schedule: "55 23 * * *"
      image: jaegertracing/jaeger-es-index-cleaner
  agent:
    strategy: DaemonSet
  sampling:
    options:
      default_strategy:
        type: const
        param: 1
```
