### ISSUE TITLE
spark-dependencies cronjob doesn't use configured ES secret as env vars

### ISSUE THREAD

**Issue by camelpunch** [jaegertracing/jaeger-operator#611]
When switching from a self-hosted ES to a cloud-based one, I noticed that the `jaeger-spark-dependencies` cronjob doesn't get set up with the `ES_USERNAME` and `ES_PASSWORD` stored in the configured `storage.secretName`. So I get 401s when this job runs.

I can get around it with a script that patches the cronjob with something like:

```
---
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jaeger-spark-dependencies
            env:
            - name: ES_USERNAME
              value: "$username"
            - name: ES_PASSWORD
              value: "$password"
```
It'd be great if the cronjob generator conditionally provided a `envVarFrom` instead.

**Comment by pavolloffay** [comment]
Could you please paste here Jaeger CR?

**Comment by camelpunch** [comment]
```yaml
---
kind: Jaeger
apiVersion: jaegertracing.io/v1
metadata:
  name: jaeger
  namespace: tools
spec:
  strategy: production
  ingress:
    enabled: false
  storage:
    type: elasticsearch
    secretName: elasticsearch
    options:
      es:
        server-urls: https://redacted.europe-west1.gcp.cloud.es.io:9243
    dependencies:
      enabled: true
      elasticsearchNodesWanOnly: true
  agent:
    resources:
      requests:
        memory: 9Mi
        cpu: 100m
      limits:
        memory: 128Mi
        cpu: 500m
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: priority
            operator: In
            values: [noncritical]

  tolerations:
  - key: priority
    operator: Equal
    value: noncritical
    effect: NoSchedule
```
