### ISSUE TITLE
[Question] Pass parameters to Jaeger Client using operator

### ISSUE THREAD

**Issue by cfontes** [jaegertracing/jaeger-operator#613]
Hello,

I would like to know if it's possible to pass Jaeger Client parameters like `- --es.max-span-age=2880h` to the Jaeger-Query created with this operator?

I searched for it but couldn't find a way to do it.

Thanks

**Comment by jpkrohling** [comment]
All options for the collector and/or query can be specified under the `options` node, like:

https://github.com/jaegertracing/jaeger-operator/blob/9cdd514655654a92de5a70b58fda2797d6a6a32b/deploy/examples/simple-prod.yaml#L6-L13

In your case, it would be like:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.default.svc:9200
        max-span-age: 2880h
```
