### ISSUE TITLE
"LogOut" options missing in the default all-in-one cr config

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#644]
`Log Out` menu option is missing in the default CR file.
This file provided by jaeger-operator.

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
  namespace: jkandasa
spec:
  strategy: allInOne
  allInOne:
    image: 'registry.redhat.io/distributed-tracing/jaeger-all-in-one-rhel7:1.13'
    options:
      log-level: debug
      query:
        base-path: /jaeger
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking:
        gaID: UA-000000-2
      menu:
        - label: About Jaeger
          items:
            - label: Documentation
              url: 'https://www.jaegertracing.io/docs/latest'
  storage:
    options:
      memory:
        max-traces: 100000
```

![image](https://user-images.githubusercontent.com/1004403/64314329-4a663100-cfcc-11e9-8e20-bb037696f80d.png)
