### ISSUE TITLE
Agent daemonset should be started with hostNetwork

### ISSUE THREAD

**Issue by sebbonnet** [jaegertracing/jaeger-operator#676]
When using the `daemonset` stragegy for the agent, the agent pods should be created with `hostNetwork: true` to make it possible for tracing clients to reference their IP using the following container spec:
```
env
- name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

`hostNetwork` is enabled in the kubernetes production template too, so this looks like a small  oversight: https://github.com/jaegertracing/jaeger-kubernetes/blob/master/jaeger-production-template.yml#L217
