### ISSUE TITLE
Handling UI configuration in a json file

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#68]
Currently the CR enables options (name value pairs) to be specified which are converted to arguments supplied to the executable.

However[ UI configuration](https://www.jaegertracing.io/docs/1.7/deployment/#ui-configuration) requires the specification of a separate file.

Wondering whether all options should be defined in a configmap per jaeger instance?

**Comment by jpkrohling** [comment]
I completely missed this part. Is this config file new?

I did consider a configmap for the other parts, similar to what we have for Kubernetes/OpenShift, but I then realized that the CR *is* the configuration source. It's unclear what would be the behavior if someone changes a configmap that is managed by the operator.

In that sense, I think I would do the same here: we could have a construct similar to `Options` (or even just reuse it, I think it might work), and convert it to JSON. Like:

```yaml
apiVersion: "io.jaegertracing/v1alpha1"
kind: "Jaeger"
metadata:
  name: "ui-options"
spec:
  strategy: all-in-one
  ui:
    tracking: 
      gaID: UA-000000-2
```
