### ISSUE TITLE
Unable to connect to ECL Elasticsearch used by cluster logging

### ISSUE THREAD

**Issue by agvikashsagar** [jaegertracing/jaeger-operator#682]
I have deployed Jaeger-Operator in Openshift, where elasticsearch is already running with https. Created a simple-prod CRD to connect with Jaeger operator.
Getting below error,

`  | {"level":"info","ts":1570072149.773908,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
  | {"level":"info","ts":1570072149.7740974,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
  | {"level":"info","ts":1570072149.774141,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
  | {"level":"info","ts":1570072149.7741497,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
  | {"level":"fatal","ts":1570072154.8943825,"caller":"collector/main.go:91","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: Head https://logging-es.openshift-logging.svc.cluster.local:9200:  x509: certificate signed by unknown authority: no Elasticsearch node available","errorVerbose":"no Elasticsearch node available\ngithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.init.ializers\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/client.go:88\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:188\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337\nhealth check`

I am using the following crd.
**simple-prod.yaml:**
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://logging-es.openshift-logging.svc.cluster.local:9200
        tls:
          skip-host-verify: true
  annotations:
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  agent:
    strategy: DaemonSet
  serviceAccount: jaeger-agent-daemonset
  securityContext:
    runAsUser: 1026690000

```
Jaeger unable to vertify elasticsearch certs, since it is selfsigned. Is there any way to skip the cert check or how to include elasticsearch certs to Jaeger?
Note: i have already added es.tls.skip-host-verify: true
