### ISSUE TITLE
how to ignore server certificate check when connect to a self signed existing ES cluster 

### ISSUE THREAD

**Issue by yuecong** [jaegertracing/jaeger-operator#685]
I have one existing ES cluster( 7.x) and running in https mode with a self-signed cert.
I can connect it using 
```
 curl https://13.x.x.x:9200/_cluster/health -u username:password -k
```
I configured the ES backend as 
```
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: "https://13.x.x.x:9200"
        username: username
        password: password
        tls:
          skip-host-verify: true
      es-provision: false
```

But I got the error as
```
"failed to create primary Elasticsearch client: health check timeout: Head https://xx.xxx.xxx.xxx:9200: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs: no Elasticsearch node available
```
How can I config jaeger to connect to a self-signed ES server? My server also supports client cert authenticate if it is the only way to do so.

Thanks

**Comment by yuecong** [comment]
Also, how can I map the options from the cli options to the options to be specified inside the operator?
https://www.jaegertracing.io/docs/1.14/cli/#jaeger-collector-elasticsearch

**Comment by jpkrohling** [comment]
It should be sufficient to use `es.tls.skip-host-verify` as you did. Could you check whether the underlying deployment is being created with this option? Something like:

`kubectl describe deployment {the-jaeger-collector-deployment-name} `

The `options` block from the CR are translated as CLI parameters to the underlying component. Like:

```yaml
options:
  es:
    server-urls: https://13.x.x.x:9200
```

becomes:

```
--es.server-urls="https://13.x.x.x:9200"
```
