### ISSUE TITLE
Operator sometimes take minutes to create a new deployment after I delete the old jaeger 

### ISSUE THREAD

**Issue by yuecong** [jaegertracing/jaeger-operator#687]
I found several times that jarger-operator does not trigger to create a new jaeger deployment after I delete the old one and recreate a new one. Is there a way I can enable the debug level for the jarger-operator so that I can get more info about what is happening inside the operator?
Here is the step to repro
```
 kubectl delete -f production-with-es.yaml
 kubectl apply -f production-with-es.yaml
```

When I do 
```
k get jaeger
NAME        AGE
jaeger-es   8m
```
but there is still no deployment and pods for jarger components.

**Comment by jpkrohling** [comment]
You can add `--log-level=debug` to the `args`. More concretely, change this line:

https://github.com/jaegertracing/jaeger-operator/blob/bc81d4a9cc17c99cbadad91235d74fedc38df71c/deploy/operator.yaml#L23

With this:

```yaml
          args: ["start", "--log-level=debug"]
```

**Comment by yuecong** [comment]
Thanks. will enable it and share the outputs here when next time I had the issue again

**Comment by jpkrohling** [comment]
@yuecong are you still having this problem? Are you able to provide the debug logs with the problem you are facing?

**Comment by mohit-chawla** [comment]
@jpkrohling i use the following `operator.yaml`

```
# source: https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger-operator
  template:
    metadata:
      labels:
        name: jaeger-operator
    spec:
      serviceAccountName: jaeger-operator
      containers:
      - name: jaeger-operator
        image: jaegertracing/jaeger-operator:1.17.0
        ports:
        - containerPort: 8383
          name: metrics
        args: ["start"]
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "jaeger-operator"

```

and still i dont see any events when i do this 
`kubectl describe deployments -n <namespace> jaeger-operator`

All i see is:

```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     jaeger-operator-799dfbdd89 (0/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  4m34s  deployment-controller  Scaled up replica set jaeger-operator-799dfbdd89 to 1

```
I was expecting some reconciliation logs as I am trying to debug why deployment status is 0/1 and no pods are being created.
