### ISSUE TITLE
Create an issue on other repos when operator.yaml changes

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#726]
As we've seen in #721, changing the resources we deploy as part of the Operator (operator.yaml, role.yaml, ...) has an effect in other downstream projects, like the Helm Chart.

GitHub Workflow is a great way to address this kind of problem. A new workflow could be triggered when a certain path has changed, like this:

```yaml
on:
  push:
    branches:
      - master
    paths:
      - 'deploy/operator.yaml'
      - 'deploy/role.yaml'
```

And then create an issue in the Helm Chart repository about it, possibly making a REST call via a shell script.
