### ISSUE TITLE
all-in-one with non-memory storage (Kubernetes)

### ISSUE THREAD

**Issue by emailtovamos** [jaegertracing/jaeger-operator#740]
I could find an [example](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/all-in-one-with-options.yaml) of `all-in-one` Jaeger instance with `in-memory` storage. But there is no such example for doing it with `elasticsearch`. 
Where can I find it? 
I understand one has to have elasticsearch running already and THEN one can incorporate corresponding changes in the above yaml file. But is there a simple way/file to have both the Jaeger instance AND elasticsearch from same file? 

For someone like me who is mainly worried about having a persistent storage(with default options) and not having to figure out/manage details of elasticsearch, this would really help.

**Comment by objectiser** [comment]
There is another example that uses [Badger local storage](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/with-badger-and-volume.yaml) - this should give you what you are looking for. We need to update the documentation to clearly outline this option.

**Comment by emailtovamos** [comment]
Thanks, I will try it out. But is there any other setting up needed for Badger? Like creating volume separately? Or your example takes care of it already?

**Comment by emailtovamos** [comment]
Thanks @objectiser - I tried the Badger storage as per the file you mentioned. It worked fine as I could see my services in the UI. But just to test the persistence nature, I deleted the jaeger instance pod. Another pod sprung back on as expected. But this time I could no longer see my services in the UI. Is this expected behaviour? I was expecting it to still show stuff.

**Comment by jpkrohling** [comment]
For production purposes, you probably would want to provision the storage yourself and specify the volume mount/volume in the Jaeger CR. The Jaeger Operator will only create `emptyDir` volumes, which effectively makes it just a bit better than ephemeral.

**Comment by emailtovamos** [comment]
You mean like the options shown here: https://www.jaegertracing.io/docs/1.14/operator/#storage-options ?

**Comment by jpkrohling** [comment]
The example that @objectiser mentioned and that you are probably using is the right way, just replace `emptyDir` in the volume definition with a production-quality concrete storage: https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes

**Comment by emailtovamos** [comment]
Ok So I created a `pvc`: 
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jaegerpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "my-storageclass"
```
Then gave it in the jaeger instance with badger: 
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec: 
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
    volumeMounts:
    - name: data
      mountPath: /badger
    volumes:
    - name: data
      persistentVolumeClaim:
            claimName: jaegerpvc
```
I can see the pvc and pv running fine when I do e.g. `kubectl get pv --all-namespaces`
I was expecting the pod to restart and/or have a mention of the `pvc`. But nothing changed. How can I make sure it is working the way expected? Or am I missing any other step?

**Comment by jpkrohling** [comment]
The indentation looks odd. Do you get any error messages when you try to apply this resource? Could you please start the operator with `--log-level=debug` and share the logs?

**Comment by emailtovamos** [comment]
```
{"level":"debug","ts":1572625156.8930852,"caller":"app/span_processor.go:124","msg":"Span written to the storage by the collector","trace-id":"65c73a5837feb416","span-id":"65c73a5837feb416"}
{"level":"debug","ts":1572625157.892143,"caller":"processors/thrift_processor.go:116","msg":"Span(s) received by the agent","bytes-received":331}
{"level":"debug","ts":1572625157.8931003,"caller":"app/span_processor.go:124","msg":"Span written to the storage by the collector","trace-id":"5e915efb5e9f8483","span-id":"5e915efb5e9f8483"}
{"level":"debug","ts":1572625158.8920205,"caller":"processors/thrift_processor.go:116","msg":"Span(s) received by the agent","bytes-received":329}
{"level":"debug","ts":1572625158.892912,"caller":"app/span_processor.go:124","msg":"Span written to the storage by the collector","trace-id":"23c6edea6faf6a10","span-id":"23c6edea6faf6a10"}
```

**Comment by emailtovamos** [comment]
The above logs look as expected right? I just deleted the pod and it restarted. But in the UI I could no longer see the older traces.

**Comment by objectiser** [comment]
@emailtovamos Can you try with the modified indentation as below:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec: 
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
 volumeMounts:
 - name: data
   mountPath: /badger
 volumes:
 - name: data
   persistentVolumeClaim:
       claimName: jaegerpvc
```
The `volumes` and `volumeMounts` should be at the same level as `storage`.
