### ISSUE TITLE
Badger not cleaning data in expected manner

### ISSUE THREAD

**Issue by emailtovamos** [jaegertracing/jaeger-operator#755]
I'm using `all-in-one` with badger storage in google Kubernetes. 
My file is: 

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec: 
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest 
    # options:
    #   log-level: debug
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
        span-store-ttl: 24h0m0s 
        truncate: true
  volumeMounts:
  - name: data
    mountPath: /badger
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: jaegerpvc4
```

This means I expect the old traces to be deleted in 24 hours. I searched for the old traces, I couldn't find them which is the expected behaviour. So far all good.

But the thing I am worried about is the constant increase of the disk space. I was expecting it to stay around the level which it reached at the end of the first 24 hours but it has almost always been increasing except a few drops. So no matter how much space I assign, there is always a chance of hitting the limit!

What am I doing wrong?

![image](https://user-images.githubusercontent.com/18745859/68592465-0fc8bb00-048b-11ea-9c53-928a7cd7d641.png)
