### ISSUE TITLE
How to add volumes and volumeMounts

### ISSUE THREAD

**Issue by clyang82** [jaegertracing/jaeger-operator#76]
I want to this yaml file can be able to apply by jaeger-operator.
```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: istio-jaeger
spec:
  strategy: production
  collector:
    image: jaegertracing/jaeger-collector:latest
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/config/tls
      name: certs
      readOnly: true
  query:
    image: jaegertracing/jaeger-query:latest
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/config/tls
      name: certs
      readOnly: true
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: es-certs
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        tls: true
        tls.cert: /usr/share/elasticsearch/config/tls/elasticsearch-router.crt
        tls.key: /usr/share/elasticsearch/config/tls/elasticsearch-router.key
        tls.ca: /usr/share/elasticsearch/config/tls/ca.crt

```

Check the source code and cannot find any struct defined for `volumes` and `volumeMounts`
