### ISSUE TITLE
jaeger collector sampling not working with Envoy

### ISSUE THREAD

**Issue by christine-gong** [jaegertracing/jaeger-operator#764]
I am using Jaeger 1.13. with Envoy 1.12
According to issue https://github.com/jaegertracing/jaeger-operator/issues/696 i set the sampling directly in the CR
```
sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 100
      service_strategies:
      - service: svc1
        type: probabilistic
        param: 100
        operation_strategies: 
        - operation: metrics
          type: probabilistic
          param: 0
        - operation: healthcheck
          type: probabilistic
          param: 0
```
And i checked the configmap got updated. 
but those metrics and healthcheck traces are still traced in Jaeger.
Any idea how to fix or debug that? Thanks!

**Comment by objectiser** [comment]
@christine-gong Which tracer are you using in envoy?

**Comment by christine-gong** [comment]
Hi @objectiser i'm using zipkin tracer

**Comment by objectiser** [comment]
@christine-gong The sampling configuration in the CR is used to configure Jaeger tracers, via the jaeger agent.

It may be better to use the sampling configuration (per route) in Envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-route

**Comment by christine-gong** [comment]
@objectiser so that sampling config in CR is not applied at collector but at agent? Even if https://github.com/jaegertracing/jaeger-operator/issues/696 fixes the collector strategy file, it wont work with Envoy?

**Comment by christine-gong** [comment]
btw: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-route works 
```
tracing:
   overall_sampling:
       numerator: 0
       denominator: HUNDRED
```
thanks @objectiser

**Comment by saivishalvangala** [comment]
Hi @christine-gong  can you tell me how it got solved

**Comment by christine-gong** [comment]
@saivishalvangala in envoy i did something on the route level like this:
```
                            - match:
                                case_sensitive: true
                                path: /healthcheck
                              route:
                                cluster: cluster1-health
                              decorator:
                                operation: healthcheck
                              tracing:
                                overall_sampling:
                                  numerator: 0
                                  denominator: HUNDRED
```
Does istio support similar config?
