### ISSUE TITLE
Add support for k8s secrets

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#79]
As discussed https://github.com/istio/istio/pull/9508#issuecomment-435593826 it would be good to support k8s secrets, to enable (for example) username and password to be passed to Elasticsearch and Cassandra.

**Comment by objectiser** [comment]
Due to recent PR https://github.com/jaegertracing/jaeger-operator/pull/82, we now have support for volumes/mounts which can be used to provide access to the secrets. This should be adequate for situations where the secrets are accessed via files (e.g. certificates).

However we still have the case where the secrets are being passed as parameters (e.g. ES/Cassandra passwords).

An example of how a container can be defined to pass such details is [here](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-environment-variables).

This shows the values being passed as environment variables, which is an option with the Jaeger executables - instead of as parameters. We just need to provide a similar definition, that could sit alongside the `options` nodes, which instead captures the environment variable name (possibly lower case form automatically converted to appropriate uppercase representation), the secret name and key.

**Comment by objectiser** [comment]
A possible configuration:
```
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
    secureOptions:
      - name: es.password
        secret: my-secret
        key: es-password
```
thoughts @jpkrohling ?
