### ISSUE TITLE
Using Kafka buffer without a storage or Kafka as a storage

### ISSUE THREAD

**Issue by bbarn3y** [jaegertracing/jaeger-operator#790]
Hi,

We are trying to get Jaeger working with Seldon models and with Kafka as storage. We read that Kafka can only be used as a buffer, but we are not sure if that also means that Kafka can't be used without another storage present.

We have consumers running separately that'd like to read the traces from the same Kafka topic that Jaeger writes the traces to. The problem is that no matter how we try to configure Jaeger, the traces never arrive. We can see in the Seldon model's logs that the traces were sent.

We used this documentation mainly: https://www.jaegertracing.io/docs/1.15/operator/

This is one of the yaml's that we tried:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-streaming
spec:
  strategy: streaming
  collector:
    options:
      kafka: # <1>
        producer:
          topic: jaeger-spans
          brokers: my-cluster-kafka-brokers.kafka:9092
  ingester:
    options:
      kafka: # <1>
        consumer:
          topic: jaeger-spans
          brokers: my-cluster-kafka-brokers.kafka:9092
      ingester:
        deadlockInterval: 0 # <2>
```

We tried all variations of this configuration that made sense to use, tried all 3 strategies (allInOne, production, streaming), different storages (memory, kafka), different ingester and collector options, but the traces never reached Kafka.

When we set the storage Kafka with allInOne strategy, we received the following exception:
```
{"level":"fatal","ts":1574863495.3816724,"caller":"all-in-one/main.go:109","msg":"Failed to create span reader","error":"kafka storage is write-only","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:109\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:171\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/runtime/proc.go:203"}
```

We installed the strimzi custom resource definitions, however we used our own Kafka that we installed using helm. When we tried to install Jaeger with faulty broker url and Kafka set as a storage, it failed during initialization otherwise it starts, so our Kafka broker URL should be correct.

Can Jaeger send the traces to Kafka without having another storage defined? We don't need elasticsearch or Cassandra. Memory would be fine in case of allInOne, but that didn't work for us either. We don't see any obvious errors in the Jaeger logs (collector, agent, ingester, etc.).

**Comment by jpkrohling** [comment]
It should be possible to accomplish that with the `production` strategy, disabling `jaeger-query` as there won't be any storage to read spans from (which is why `allInOne` won't work).

> We can see in the Seldon model's logs that the traces were sent.

Could you also turn on the `debug` logs for the agent/collector? This way, you can confirm that the spans were received by Jaeger.

**Comment by bbarn3y** [comment]
Thank you, disabling query was the missing link, we managed to read the traces from Kafka this way! This was the Jaeger yaml we used:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  strategy: production
  query:
    replicas: 0
  storage:
    type: kafka
    options:
      kafka:
        producer:
          brokers: my-kafka:9092
          topic: mytopic
          encoding: json
  agent:
   strategy: DaemonSet
```

We have two remaining questions:

1. Is there a better way to turn off jaeger query? As you can see we set the replicas to 0, but that still creates the deployment and the service.
2. We start the agent as a DaemonSet, which becomes a bit problematic when we want to set the JAEGER_AGENT_HOST environment variable in our SeldonDeployment, however we'd like to reference the agent as a service and not as an IP address if possible.
Is there a way to tell the agent to start a service that we can reference?
