### ISSUE TITLE
How to use AWS Elasticsearch with access key and secret key?

### ISSUE THREAD

**Issue by cuihaikuo** [jaegertracing/jaeger-operator#796]
Here is my jaeger.yaml:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://vpc-prod-aws-nx-es-jaeger-pipzm3***ltjqi.cn-northwest-1.es.amazonaws.com.cn                                                                        
  dependencies:
    enabled: true
    ElasticsearchNodesWanOnly: true
  agent:
    strategy: DaemonSet
    options:
      log-level: debug

```
due to the aws security strategy, I have to specify the access key, how to pass it into jaeger?
