### ISSUE TITLE
Question: DaemonSet simple-prod-agent service for JAEGER_AGENT_HOST env

### ISSUE THREAD

**Issue by jodagm** [jaegertracing/jaeger-operator#797]
The incubator/jaeger creates jaeger-agent demand set with a service, which makes it possible to configure jaeger-client 
```
JAEGER_AGENT_HOST=jaeger-agent
```
jaeger-operator is not creating the service, so the monitored app deployment chart needs to have this:
```
- name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

Can the operator create simple-prod-agent service can for DaemonSet?

Thanks for your help, 
Jonathan
