### ISSUE TITLE
Deploy Query with Type:load balancer Using K8s Operator 

### ISSUE THREAD

**Issue by orlando-jamie** [jaegertracing/jaeger-operator#801]
Hello,
    I am trying to deploy the K8s operator to expose the query service as an internal load balancer via the following yaml, but it does not seem that the CRD passes type:LoadBalancer or the annotation to the query service definition.  

``` yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-test
spec:
  ingress:
    enabled: false
  query:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

Are there any ways to make sure the query service gets deployed as in internal load balancer via the operator? Or do I need to manage the deployment myself? We are not currently using any ingress-controller.

**Comment by jpkrohling** [comment]
@orlando-jamie, right now, it's indeed possible that the annotation isn't being propagated down to the service, only to the deployment. We should consider propagating it down, though.

In the meantime, you can manage your own service resource (not deployment).

For our own reference, here's the Kubernetes documentation about load balancer services: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

**Comment by orlando-jamie** [comment]
Thanks for the feedback @jpkrohling. 

Could you potentially advise on a jaeger definition that would not install the default query K8s service, so that I could manage it myself? When I launch with the following, the operator still seems to create the query service.

``` yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-test
spec:
  ingress:
    enabled: false
```

``` yaml
NAMESPACE     NAME                              TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
default       jaeger-test-agent                 ClusterIP      None             <none>        5775/UDP,5778/TCP,6831/UDP,6832/UDP      7m15s
default       jaeger-test-collector             ClusterIP      172.20.33.189    <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   7m15s
default       jaeger-test-collector-headless    ClusterIP      None             <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   7m15s
default       jaeger-test-query                 ClusterIP      172.20.0.155     <none>        16686/TCP                                7m15s
```
