### ISSUE TITLE
Reuse values from externally created secrets

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#846]
At the moment Jaeger CR supports specifying secreat name  e.g. `storage.secretName: jaeger-secret` which is used to define env variables on deployments https://www.jaegertracing.io/docs/1.16/operator/#secrets-support. This is often used to define storage user/pass.

However often times passwords already exist in secrets created by other components deploying storage (operator, heml chart). To use this password one has to copy password value to a new secret that properly defines env variable names:

```
kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=changeme --from-literal=ES_USERNAME=elastic
```

**Comment by jpkrohling** [comment]
As discussed on IRC, I think the best approach would be to add support for references in the Options object, so that we can have something like what's [possible with env vars](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables):

```yaml
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
```
