### ISSUE TITLE
Duplicated "Injecting sidecar" message

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#855]
When deploying an application that should have a sidecar injected, the following message is duplicated:

```
INFO[0270] Injecting Jaeger Agent sidecar                deployment=tracegen jaeger=simplest jaeger-namespace=default namespace=default
INFO[0270] Injecting Jaeger Agent sidecar                deploymentName=tracegen deploymentNamespace=default instance=simplest namespace=default
```

Using  the `simple-prod` CR as example, the following deployment can be used to reproduce:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      containers:
      - name: tracegen
        image: quay.io/jpkroehling/jaeger-tracegen:latest
        args: ["-duration", "10s", "-workers", "1"]
```
