### ISSUE TITLE
Operator is not creating Service for Daemonset.

### ISSUE THREAD

**Issue by berahac** [jaegertracing/jaeger-operator#882]
When creating production Deployment of jaeger configuration, Agent service does not get created.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod-es
spec:
  agent:
    strategy: DaemonSet
  ingress:
    enabled: false
  strategy: production
  storage:
    type: elasticsearch
    options:
.
.
.

```  

 Get pods command returns this:

```
NAME                                               READY   STATUS      RESTARTS   AGE
jaeger-op-prod-jaeger-operator-9dd6bb756-qrmgz     1/1     Running     0          4d19h
jaeger-prod-es-agent-daemonset-9886b               1/1     Running     0          4d17h
jaeger-prod-es-agent-daemonset-mfr9s               1/1     Running     0          4d17h
jaeger-prod-es-collector-59bcfb5c97-69hqk          1/1     Running     0          135m
jaeger-prod-es-es-index-cleaner-1580514900-p44xm   0/1     Completed   0          2d18h
jaeger-prod-es-es-index-cleaner-1580601300-pbqtd   0/1     Completed   0          42h
jaeger-prod-es-es-index-cleaner-1580687700-gkx49   0/1     Completed   0          18h
jaeger-prod-es-query-7c99b4db5b-ncjgg              2/2     Running     0          135m
```

I had to create the Agent Service locator manually. it is supposed to be created automatically...

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger-prod-es
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-prod-es-agent
    app.kubernetes.io/part-of: jaeger
  name: jaeger-prod-es-agent
  namespace: observability
spec:
  clusterIP: None
  ports:
  - port: 5775
    targetPort: 5775
    name: zk-compact-trft
    protocol: UDP
  - port: 5778
    targetPort: 5778
    name: config-rest
    protocol: TCP
  - port: 6831
    targetPort: 6831
    name: jg-compact-trft
    protocol: UDP
  - port: 6832
    targetPort: 6832
    name: jg-binary-trft
    protocol: UDP
  selector:
    app: jaeger
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: jaeger-prod-es
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-prod-es-agent
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
```

Service Listing from get svc command:
```
NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
jaeger-op-prod-jaeger-operator-metrics   ClusterIP   10.100.189.158   <none>        8383/TCP,8686/TCP                        4d21h
jaeger-prod-es-agent                     ClusterIP   None             <none>        5775/UDP,5778/TCP,6831/UDP,6832/UDP      62m
jaeger-prod-es-collector                 ClusterIP   10.100.119.107   <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   4d19h
jaeger-prod-es-collector-headless        ClusterIP   None             <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   4d19h
jaeger-prod-es-query                     ClusterIP   10.100.130.96    <none>        16686/TCP                                4d19h
```
