### ISSUE TITLE
UI is not loading with custom query.base-path

### ISSUE THREAD

**Issue by vladkolodny** [jaegertracing/jaeger-operator#926]
While changing the base-path to any directory UI is not loading.
It is falling back to serving the contents of index.html instead of any other static files.
When we set query.static-files there is instead an error that the query service cannot find index.html at the specify directory

An example of jaeger manifest:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: default-jaeger
spec:
  strategy: production
  query:
    options:
      query:
        base-path: /jaeger
      log-level: debug
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://XXXXXXXXXXXXXXX:9200
  ingress:
    hosts:
      - XXXXXXXXXXXXXXX.com
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ops
```

**Comment by objectiser** [comment]
I tried using the following CRs with Jaeger operator 1.16 on minikube:
```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "my-jaeger"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.16
    options:
      log-level: debug
      query:
        base-path: /tracing
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking: 
        gaID: UA-000000-2
      menu:
        - label: "About Jaeger"
          items:
            - label: "Documentation"
              url: "https://www.jaegertracing.io/docs/latest"
  storage:
    options:
      memory:
        max-traces: 100000
```
(the `deploy/examples/all-in-one-with-options.yaml` with updated all-in-one image version), and
```
# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  query:
    options:
      log-level: debug
      query:
        base-path: /tracing
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: http://elasticsearch.default.svc:9200
```
(the `deploy/examples/simple-prod.yaml` with the additional `query` node).

Both worked fine - I was able to open the Jaeger UI at the `/tracing` path.

So appears the the problem may be related to the ingress?

@jpkrohling Any ideas?
