### ISSUE TITLE
Configuring a Kafka based Jaeger architecture

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#95]
Currently Kafka support is being added to Jaeger in two places, as a storage plugin and an ingester.

The aim of this approach is to have a collector configured with Kafka as storage, to publish spans to Kafka, and then ingesters that can consume those messages and store the spans in a real storage backend (e.g. elasticsearch/cassandra).

We need to consider how such a configuration would be defined in the operator's CR?

Currently kafka is being listed as a storage type - but an operator CR can only support a single storage type - so either

1) We need to treat this kafka based configuration as something else - i.e. the storage type is specified as the real storage used by the ingester, but the collector using kafka and the ingester need to be configured from a different spec?

2) There would be two separate CRs - one defining the collector with Kafka storage, and the other defining the ingester with real storage. Issue with this approach is that only a subset of the components may need to be configured in each CR - so query will only be defined in the second CR (as it will also use the same real storage), and agent may potentially be defined in the first, as it will use the collector.

Although Kafka not yet fully supported, we need to consider how its introduction may impact the spec structure.

**Comment by objectiser** [comment]
My preference would be to go with option 1 - treating this Kafka based configuration as a virtual collector - so the current config still applies to the collector and backend storage used by the ingester.

The additional part is a Kafka based configure that connects the two parts - and if defined, it would result in the collector being configured to use Kafka storage, and the ingester being deployed.

**Comment by objectiser** [comment]
There is also the option to have multiple storage plugins configured within the collector - e.g. kafka and elasticsearch.

So possibly we need more than two `strategy` values - one for `allInOne` but three or more 'production' type strategies. One for simple collector/storage, one for collector/multistorage and one for "distributed collector" using kafka.

The first two could potentially be collapsed into a single 'strategy', by simply allowing a comma separated list of storage types, with kafka options listed in the `storage.options` section.

**Comment by jpkrohling** [comment]
How about having a `JaegerKafkaStorageSpec` as a child of `JaegerStorageSpec`, like `CassandraCreateSchema` currently is?

This spec could then hold an `Options` object, related to the configuration of the backing storage.

**Comment by objectiser** [comment]
Possible suggestions. First for the use of kafka as a secondary storage plugin within the collector:

```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: with-es-and-kafka-storage
spec:
  strategy:production
  storage:
    type: es,kafka
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
        password: changeme
      kafka:
        brokers: xyz
        topic: spans
```
and using the ingester approach:

```
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: with-ingester
spec:
  strategy:production
  ingester:
    enabled: true
  storage:
    type: es
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
        password: changeme
      kafka:
        brokers: xyz
        topic: spans
```
this means that, as the ingester has been enabled, then the collector will use the kafka storage plugin (using the config from `storage.options`), and the 'enabled' ingester will use the actual storage type (i.e. elasticsearch in this case). So the change in deployment structure is triggered by the `ingester,enabled` being true.

Note: the kafka options are optional, if defaults are appropriate - although likely that the `kafka.brokers` option would be required in practice.
