### ISSUE TITLE
Operator works not intuitively way when haven't got hpa permissions.

### ISSUE THREAD

**Issue by dm3ch** [jaegertracing/jaeger-operator#989]
I installed jaeger operator to my cluster using official helm chart version 2.14.0 with default values.
And realised that changes in jaeger custom resource are applied only after operator pod restart.

In operator logs I had next lines:
```
E0325 19:06:41.586604       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
```

*Reproduce guide:*
* Install jaeger operator via https://github.com/jaegertracing/helm-charts v2.14.0 with default values in some namespace
* Create jaeger custom resource in same namespace:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  ingress:
    hosts:
      - jaeger.test
```
* Wait until pods,svcs and ingress would be created
* Change jaeger custom resource:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  ingress:
    hosts:
      - jaeger1.test
```
* Check that ingress host wasn't changed
* Restart operator pod and wait until it would be ready
* Check that ingress host was changed.

So it seems that when operator haven't got hpa permissions it process custom resource changes only on start and then falls into some error loop.
This behaviour is not intuitive, cause with such problem you could easily create jaeger instances (and pods and other would be created), but you would be confused why later changes are not applied.

Link to the issue with missing hpa permissions in chart: https://github.com/jaegertracing/helm-charts/issues/84
