### ISSUE TITLE
confused about the service generated by operator

### ISSUE THREAD

**Issue by schecterdamien** [jaegertracing/jaeger-operator#990]
hi.  
 		
I follow the steps of the official website document to deploy step by step。there are some problem, the deploy.yml look like this:
    
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: agent-as-daemonset
spec:
  agent:
    strategy: DaemonSet
    options:
      log-level: debug

```

jaeger run in observability namespace and my app run in another namespace. I want to run agent as daemonset and open a port in host machine so all my app could cross namespace pass span to agent，but:
   
<img width="845" alt="截屏2020-03-2619 49 36" src="https://user-images.githubusercontent.com/22927604/77644375-db6a1d00-6f9b-11ea-8d36-1014d544a7fe.png">

I find all service is ClusterIP，what i expect is agent-as-daemonset-agent service run in NodePort type，so i am confused.

my purpose is to run the application and jaeger in two different namespaces and could send span to the agent. Is there any correct way to do this?
