### ISSUE TITLE
Updating collector's sampling config does not restart all collector pods

### ISSUE THREAD

**Issue by linjmeyer** [jaegertracing/jaeger-operator#999]
I have a Jaeger operator with 3 collector pods.  When the sampling config is updated only 2 of 3 the pods are restarted, leading to the clients getting the old remote sampling configuration.  As a test I also tried changing the minReplicas to 4 but there is still 1 pod that is not restarted.  It is the same pod as when there were 3 replicas, seems like maybe the oldest pod gets stuck.

Jaeger version: 17.0
Jaeger object:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-production
  namespace: observability
spec:
  strategy: production  
  sampling:
    options:
      default_strategy:
        param: 0.3
        type: probabilistic
      service_strategies:
      - param: 1
        service: test.test.delete.me
        type: probabilistic     
  collector:
    autoscale: true
    minReplicas: 3
    maxReplicas: 8
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
    options:
      collector:
        num-workers: 200 
        queue-size: 4000 
  ingress:
    enabled: false 
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: "?????"
        num-shards: 5
        num-replicas: 0
        version: 7
    esIndexCleaner:
      enabled: true                                
      numberOfDays: 3                    
      schedule: "0 0 * * *" 
 ```

Example kubectl get pods output:

```
jaeger-production-collector-86cc94b4d5-4gtt8           1/1     Running     0          8h
jaeger-production-collector-86cc94b4d5-mr7pq           1/1     Running     0          11m
jaeger-production-collector-86cc94b4d5-qw7fg           1/1     Running     0          11m
```
